### ISSUE TITLE
IntlService not working well with lazy loaded modules

### ISSUE THREAD

**Issue by jackjoy** [telerik/kendo-angular#1037]
Currently IntlModule provide CldrIntlService as IntlService's default implementation.If i want to provide a custom IntlService to replace the default implementation, i not only need to provide the custom service in root AppModule, but also in every lazy loaded modules. So i think IntlModule should use .forRoot() pattern to avoid such inconsistencies.

**Comment by danielkaradachki** [comment]
Unfortunately, switching to the forRoot/forChild pattern will require a breaking change since the module itself should not declare the provider. Therefore, we will not the change how the providers are declared at least for now. If the scenario becomes a common case we will consider it for version 2.
