### ISSUE TITLE
Columns Not Aligned When Using kendo-grid-checkbox-column in a Grid with Material Theme

### ISSUE THREAD

**Issue by cloworm** [telerik/kendo-angular#1047]
## I'm submitting a...

* Bug

## Current behavior
An empty header is not automatically created when using a kendo-grid-checkbox-column with the material theme.

## Expected behavior
An empty header will be created for a grid checkbox column like in the official documentation using the default theme:

[https://www.telerik.com/kendo-angular-ui/components/grid/selection/](https://www.telerik.com/kendo-angular-ui/components/grid/selection/)

## Minimal reproduction of the problem with instructions
Reproduced by using the plunkr linked in the official documentaion above and changing the theme import from `kendo-theme-default` to `kendo-theme-material`
[http://plnkr.co/edit/gI594PUvlupdLIcbuq17?p=preview](http://plnkr.co/edit/gI594PUvlupdLIcbuq17?p=preview)

## What is the motivation or use case for changing the behavior?

All themes should have the same behavior.

Browser:
- Chrome (desktop) version 58.0.3029.96

System:
- TypeScript version: 2.3.3
- Node version: 6.11.1
- Platform:  Windows

**Comment by gyoshev** [comment]
@cloworm the reason for this problem is that the Material theme does not provide styles for the Grid yet. We will be improving the Material theme for the upcoming release. The Grid styles depend on the input elements, so we need to finish them first. The components available in the Material theme [can be seen in the preview application](http://www.telerik.com/kendo-angular-ui/components/styling/theme-material/).

**Comment by cloworm** [comment]
Understood, I look forward to the next release.
