### ISSUE TITLE
Migration from HttpModule to HttpClientModule

### ISSUE THREAD

**Issue by Raisolution** [telerik/kendo-angular#1055]
## Current state

- The Upload component depends on the old `HttpModule`, which is [deprecated in Angular 5.0](https://blog.angular.io/version-5-0-0-of-angular-now-available-37e414935ced).

```
import { HttpModule } from '@angular/http';

@NgModule({
  imports: [ BrowserModule, HttpModule, UploadModule, BrowserAnimationsModule ]
  ...
})
```

## New state

- The Upload component now depends on the `HttpClientModule`, which was introduced in Angular 4.3.

```
import { HttpClientModule } from '@angular/common/http';

@NgModule({
  imports: [ BrowserModule, HttpClientModule, UploadModule, BrowserAnimationsModule ]
  ...
})
```

## New features

- Progress tracking and `uploadProgress` event.
```
<kendo-upload (uploadProgress)="uploadProgressEventHandler($event)" ...></kendo-upload>
```
- Specifying the [responseType](https://angular.io/api/common/http/HttpRequest#responseType). Default one is `json`.
```
<kendo-upload [responseType]="'text'"></kendo-upload>
```
- Ability to utilize [HttpInterceptors](https://angular.io/api/common/http/HttpInterceptor) to modify upload requests.

**Comment by Raisolution** [comment]
New features are currently available in version `v2.0.0-dev.201711021309` and will soon be released in `v2.0.0`.

**Comment by Raisolution** [comment]
`v2.0.0` is now available.

**Comment by rvovard** [comment]
Is there a way to know what else has been fixed in this version?
Actually, are there no changelogs for new versions of kendo-angular-* packages?

**Comment by alexeikostevich** [comment]
Dropping of @angular/http is really great news! Thank you for the making the transition to @angular/common/http happened.

I have accidentally noticed that API docs still reference [Headers](https://angular.io/docs/ts/latest/api/http/index/Headers-class.html) from _angular/http_ instead of [HttpHeaders](https://angular.io/api/common/http/HttpHeaders) from _angular/common/http_: https://www.telerik.com/kendo-angular-ui/components/upload/api/UploadComponent/#toc-saveheaders

It would be great to update docs to avoid possible confusion.

Thank you for looking at this!

**Comment by Raisolution** [comment]
Hi @alexeikostevich,

thank you for noticing this discrepancy. We are going to update the docs right away.
