### ISSUE TITLE
kendo-angular-upload 2.0.0 import failing -> node_modules incomplete

### ISSUE THREAD

**Issue by DGolverdingen** [telerik/kendo-angular#1063]
## I'm submitting a...
* Regression report 

## Current behavior
Cannot find module of kendo-angular-upload when importing FileState

![image](https://user-images.githubusercontent.com/29942500/32489012-e6a5e262-c3ae-11e7-8d92-80667d14177c.png)

Node_Modules incomplete:
![image](https://user-images.githubusercontent.com/29942500/32489559-b1edb5b6-c3b0-11e7-8659-b34090faefc6.png)

## Expected behavior
Should be able to import FileState from upload module

## Minimal reproduction of the problem with instructions
Update from 1.2.1 -> 2.0.0 and import FileState.

System:
![image](https://user-images.githubusercontent.com/29942500/32489173-61ab4bdc-c3af-11e7-946a-c84eb745689b.png)

**Comment by tsvetomir** [comment]
Thanks for the bug report. We've managed to identify the problem and released a fix in v2.0.1

The issue was caused by missing `rootDir` setting for the Typescript compiler. This lurked for a while in our codebase, but [turned destructive](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-does---outdir-moves-output-after-adding-a-new-file) after upgrading to Typescript 2.4

Unfortunately the change did not trigger an update to the dev channel so we couldn't catch it in time. We'll be adding automated checks to safeguard against such regressions.
