### ISSUE TITLE
[Grid] filter-menu popup not showing

### ISSUE THREAD

**Issue by pfoedermayr** [telerik/kendo-angular#1066]
## I'm submitting a...
* Bug report

## Current behavior
When clicking the filter-menu-button the first time, the filter-popup opens normally.
All subsequent clicks on other filter-menu-buttons will not open the popup, but will raise an error.
`Cannot read property 'popupElement' of null`

## Expected behavior
The filter-menu to open on every click.

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/Qu55zGdNehd2ZqkZfNNo?p=preview (From the grid-docs)

1. Click the filter-icon on one column
2. Click outside of the filter-popup to close it
3. Click on the filter-icon on another column

The popup is not opening and an error is shown in the console.

## Environment

Package versions:
**Can be observed on the demo page**
https://www.telerik.com/kendo-angular-ui/components/grid/data-operations/filtering/#toc-filter-menu

Browser:

- Chrome (desktop) version 64

**Comment by rkonstantinov** [comment]
Hi @pfoedermayr, thanks for the report. The issue you have described is related to a [regression in Angular 5](https://github.com/angular/angular/issues/20274). 
However, we manged to workaround it in our code and the fix is available with the [@dev channel](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) latest build.

**Comment by ipeshev** [comment]
Fixed in v1.6.1
