### ISSUE TITLE
kendo-datepicker can not disable side-navigation

### ISSUE THREAD

**Issue by ykanomata** [telerik/kendo-angular#1110]
kendo-datepicker can not disable side-navigation.
I want to use like calender component. 

<kendo-datepicker [(value)]="object.dateValue" [navigation]="false"></kendo-datepicker>

**Comment by ggkrustev** [comment]
Hi @ykanomata,
indeed, the component won't hide the calendar navigation, because it doesn't expose such property like now:

https://www.telerik.com/kendo-angular-ui/components/dateinputs/api/DatePickerComponent/

We will expose the calendar.navigation property to the DatePicker in order to be able to hide it. I will update the thread once the required functionality is available.

**Comment by ggkrustev** [comment]
Hi @ykanomata, the option is available in the latest @dev release. You can try it running the following command:
`npm i @progress/kendo-angular-dateinputs@dev`

**Comment by ykanomata** [comment]
Hi ggkrustev,
I confirmed navigation parameter work well.
Thank you so much for your prompt response.

**Comment by ggkrustev** [comment]
Closing as resolved.
