### ISSUE TITLE
ExportAsPDF and ExportAsExcel don't work on mobile devices

### ISSUE THREAD

**Issue by mak633** [telerik/kendo-angular#1118]
Hello. I have an issue with export to pdf and excel on mobile devices. 
Step to reproduce: 
1. Open this page https://www.telerik.com/kendo-angular-ui/components/grid/export/pdf-export/ on iphone or ipad.
2. Click to button download as pdf
I suppose this is a bug.

**Comment by tsvetomir** [comment]
The problem is that the iOS Safari browser does not support the [download attribute](https://caniuse.com/#feat=download). Hence, the file is generated, but it's not possible to save it without setting up as [Server-side Proxy](https://www.telerik.com/kendo-angular-ui/components/filesaver/#toc-server-proxy).

Please note that the PDF Export module [does not claim any support](https://www.telerik.com/kendo-angular-ui/components/pdfexport/limitations-browser-support/#toc-supported-browsers) for mobile browsers. Exports mail fail completely or be partially broken.
