### ISSUE TITLE
Charts rendering issue

### ISSUE THREAD

**Issue by SeriousLemon** [telerik/kendo-angular#1121]
## I'm submitting a...
* Bug report

## Current behavior
The tops of the line series markers are being cut off in some cases.

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/yISxnL1hTgOu4GB2Lfuz?p=preview

Browser:
- Chrome (desktop) version
- Firefox version

**Comment by danielkaradachki** [comment]
By default the charts points are clipped between the axes. This can usually be controlled via the pane [clip](https://www.telerik.com/kendo-angular-ui/components/charts/api/Pane/#toc-clip) option, but it seems that clipping is still applied due to the line series animation. We will look into it. For now it is possible to avoid it by using margin:
http://plnkr.co/edit/6vrsJ2KiL4FymvohoCML?p=preview

**Comment by tsvetomir** [comment]
Released in v3.2.0
