### ISSUE TITLE
ComboBox text is not displayed, when list source is empty.

### ISSUE THREAD

**Issue by ykanomata** [telerik/kendo-angular#1123]
ComboBox text is not displayed, when list source is empty.
DropDownList will display text even if list source is empty.

I expect ComboBox to display text as well as DropDownList.
If I want to load list source lazy, DropDownList behavior is convenient.

http://plnkr.co/edit/KXvt2bMPM29BIkQYyBwS?p=preview

**Comment by tapopov** [comment]
Hi @ykanomata 
The ComboBox will display the text once the data arrives. This behavior is expected, as before getting the data there is no way to know if that's a custom item or existing one. Since the ComboBox rejects [custom values](https://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/custom-values/) by default, the text is not displayed. You can enable the allowCustom option (temporarily) to get around this. [Here](http://plnkr.co/edit/ZmOqLoTnKQ9N0FDhu5Rg?p=preview) is an example.

**Comment by ykanomata** [comment]
Hi @tapopov 
It worked fine. Thank you so much.
