### ISSUE TITLE
DatePicker adjusting date for leap year

### ISSUE THREAD

**Issue by AkunaMatata** [telerik/kendo-angular#1126]
## I'm submitting a...
* Bug report 

## Current behavior
Try to enter manyally leap date ( example 2/29/2000)
when entering first number of year the "29" automatically became "28".
Note it's possible to enter a leap date only when year value entered first.

## Expected behavior
Control should allow to type leap date sequentially.

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/GjHPz9yqizJLFc5lmAPt?p=preview

Just try to type "2/29/2000"

**Comment by ggkrustev** [comment]
Hi @AkunaMatata,
I agree that although expected the described behavior is somewhat undesired. It is expected, because the first valid date entered by the user (2/29/2) is not a leap year. In this moment, the component will re-validate the rest of the values and will change `29` to `28`.

Nevertheless, I believe that if the component "waits a bit" before to auto-correct the value will be more useful. Such behavior will play nice with a complete "auto-correction" behavior too (https://github.com/telerik/kendo-angular/issues/879).

Will consider the change in future.

**Comment by AkunaMatata** [comment]
But is here any possiblity to disable auto correction of dates manually ? For instance validate only only on blur or smth like it.

**Comment by ggkrustev** [comment]
I'm afraid that the component is designed to validate during typing and there is no configurable way to change that behavior.

As a side note, IMHO validating/restricting value on blur is a sign of bad UX, because the automatic changes will happen on leave and user won't (in most cases) see them. This will lead to magic behavior that nobody wants.

**Comment by svetq** [comment]
to be tracked in https://github.com/telerik/kendo-angular/issues/2008
