### ISSUE TITLE
Multiselect does not sync ngModel with data.

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#1177]
## I'm submitting a...

* Bug report 

## Current behavior

Initially ngModel binding is not updated when data arrives.

## Expected behavior

It should update ngModel when data arrives.

## Minimal reproduction of the problem with instructions
[Open this url](https://plnkr.co/edit/yydrbn5G1z1U6YErBTI4?p=preview)

Package versions:

```
v1.5.0
```

**Comment by mbrookson** [comment]
Although the description of this issue in minimal, I believe this is that same thing I am seeing.

There is an issue that has appeared with binding values to a multiselect (and potentially other dropdowns).

This is the element

    <kendo-multiselect [data]="options" textField="name" valueField="id" name="vesselIds" [(ngModel)]="editor.selected" [valuePrimitive]="true"></kendo-multiselect>

I initialise my options with an empty [] when the view loads

    options = [];
    editor = new Editor();  //editor.selected is initialised as []

Then do a call to my API to get the option values and set the list

    getData().subscribe(result => {
      this.options = result.options;
      this.editor.data = result.data;
    });

This worked fine in `@progress/kendo-angular-dropdowns` 1.1.2, but in greater versions (I've seen it definitely on 1.4.0) it is not binding properly. Instead, the id (valueField) value binds instead of the name (textField) so the user just sees numbers as the selected options.

 - If you then select a value from the list, all current values in the component are bound correctly with the textField
 - If a default value is given (options = [new Options()];) then the data binding works as expected

**Comment by valchev** [comment]
@mbrookson 

You're correct, this is a regression that occurs in cases when the component is bound to asynchronous (not initially available) complex data and primitive values. The root of the problem was a change in the algorithm used to resolve the values that do non exist in the current data (initially empty array).

I've just pushed a fix for the issue, but it will take a few days before it becomes available for download. I will get back to you as soon as a dev build of the package is ready for download.

**Comment by ipeshev** [comment]
Shipped with v1.6.1
