### ISSUE TITLE
[Grid] Grid reorder demo does not work in FF/Edge

### ISSUE THREAD

**Issue by PeterStaev** [telerik/kendo-angular#1186]
## I'm submitting a...

* Bug report 

## Current behavior
Grid row reordering does not work in Firefox or MS Edge browser while it works perfectly fine in Chrome. 

## Expected behavior
Grid row reordering should work on all browsers. 

## Minimal reproduction of the problem with instructions
1. Go to https://www.telerik.com/kendo-angular-ui/components/grid/advanced-features/row-reordering/
2. Try to move a row under FF/Edge.

**Comment by rgantla** [comment]
Hi @PeterStaev ,

As mentioned in the link you have provided, the Kendo-grid makes use of the HTML5 Drag and Drop API which is only supported by Chrome browser at this point in time. You can see if a feature is supported by a browser by using the website here: https://caniuse.com/#search=drag%20and%20drop

The information provided in the link is factual most of the times but, although I am running Firefox v57.0.4 the HTML5 Drag and Drop feature still remains unsupported as of now.

Hope that helps.

**Comment by PeterStaev** [comment]
Hi @rgantla , 

Actually DnD API is quite well supported in both latest FF and Edge. Take a look at this example page: http://mereskin.github.io/dnd/ which from what I see uses the same HTML5 DnD API. I've tested with Edge on Win10 and FF 57.0.4 and things seem to work quite well there.

**Comment by rgantla** [comment]
@PeterStaev Indeed, thanks for the link! We had implemented a custom Drag and Drop list (inside angular 4/5) using the HTML5 Drag and Drop API which worked fine on chrome and not on other browsers. That made me believe it is not supported on other browsers just like the <input type="date"/> some time ago.

Also, were you able to implement the Kendo Grid Row Reordering feature in your environment ? I am unable to replicate what is shown in their example. The main reason for that I suspect, is a small piece of code which retrieves all the nodes for table rows (tr tags) using the dopcument.querySelectorAll('.kendo-grid-content tr'). I console logged the node list and I can only see 1 element inside the node List i.e **tr.k-grid-nonrecords**

Also I have had a tough time using the **.forEach** loop because my tsLinter is throwing an error saying 
**[ts] Property 'forEach' does not exist on type 'NodeListOf<Element>'.** For this reason I had to tweak it a little bit like so: **const frameZones = Array.from(document.querySelectorAll('.k-grid-content tr'));
    frameZones.forEach** still unsuccessful at this point

**Comment by PeterStaev** [comment]
@rgantla , yes I made it to work using their example (only to find it does not work in other browsers 😢 ). You need to make sure you renew the subscription after you populate the grid with the data. Initially I missed that and was calling it a bit before the data is loaded, so i was getting a similar behavior of what you describe above.

**Comment by rgantla** [comment]
@PeterStaev I have solved this issue partially i.e. for Edge.

I tweaked the code they have in the example section a little bit. Chrome was able to use the Query selector to get all the table row tags properly but Edge was not.

so I changed 
`document.querySelectorAll('.k-grid-content tr')`
 `.forEach(item => {}`

to 
`const tableRows = Array.from(document.querySelectorAll('.k-grid-content tr'));`
`tableRows.forEach(item => {}`

and that took care of it for Edge. Here is a plunker that depicts the same: https://plnkr.co/edit/QGCGPeebmhKqFJwwVrAC?p=preview

@tsvetomir @gyoshev @elena-gancheva could you please look into this? - Thanks

Hope that helps.

**Comment by dtopalov** [comment]
The discussed example does not work in FF and IE due to some specifics or unsupported methods or interfaces:

- No support for closest() in IE (add polyfill)

- FireFox needs transfer data to be set via the dataTransfer.setData() method in the dragStart event handler

- ... however this is not supported in IE

- as mentioned above, the collection returned from document.querySelectorAll() cannot be foreached in IE

Here is a working cross-browser solution:

[https://plnkr.co/edit/eThLHHjcJclibTadeqBH?p=preview](https://plnkr.co/edit/eThLHHjcJclibTadeqBH?p=preview)

We will update the online demo accordingly.

**Comment by PeterStaev** [comment]
@dtopalov @rgantla thanks for your input! I was able to make it work with the notes that you outlined above 👍
