### ISSUE TITLE
Kendo Grid Row Reordering - Async Data

### ISSUE THREAD

**Issue by rgantla** [telerik/kendo-angular#1187]
## I'm submitting a...

* Bug report (Probable) 
* Documentation issue or request

## Current behavior

**When the Grid is dealing with data fetched via an Ajax call, the reordering of rows does not work until the view changes** (for ex: until the user clicks on the 2nd page in the pagination in this example)

## Expected behavior

The Grid should allow the user to Reorder the Rows as mentioned in the documentation(Drag and Drop - HTML5 Drag and Drop API) referring to this link https://www.telerik.com/kendo-angular-ui/components/grid/advanced-features/row-reordering/

Also, as pointed out by @PeterStaev in the post #1186 the drag and drop feature does not work on browsers other than Chrome as of today.

## Minimal reproduction of the problem with instructions

since the data fetching is asynchronous, I am using the **process** method imported from kendo-data-query inside the ajax call to map the data correctly to the grid.

Plunker Here: https://plnkr.co/edit/QGCGPeebmhKqFJwwVrAC?p=preview

Note: I have tried resubscribing to the handleDragAndDropevent in my Ajax data call but that didn't work either.

## What is the motivation or use case for changing the behavior?

Working with Async Data

## Environment

Browser:

- Chrome (desktop) version XX

System:
- Platform:   Windows

**Comment by rgantla** [comment]
I have figured out how to use Async data with my grid and still make the drag and drop work.
Here is a plunker which shows the same : https://plnkr.co/edit/QGCGPeebmhKqFJwwVrAC?p=preview

I hope this would help someone with the same question.

**Comment by wlumetsberger** [comment]
@rgantla, the Issue is still open. The Plunker provided  does not work either. 
The root cause of the Problem is that we do not really know when the grid finished rendering the rows, but the handle drag and drop Handler Method has to be executed after the grid component has rendered every row, otherwise the selector won't work and not every row has drag and drop enabled.

Is there any solution? 
Passing the Attributes to the renderer?
