### ISSUE TITLE
Scroll is missing in TreeView demo

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#1189]
* Bug report

## Current behavior
When you open 3 tree view nodes, there is no scroll.

## Expected behavior
Scroll should appear in [this demo](https://www.telerik.com/kendo-angular-ui-develop/components/treeview/data-binding/#toc-remote-heterogeneous-data).

## Minimal reproduction of the problem with instructions
Open 3 nodes in provided link.

## What is the motivation or use case for changing the behavior?
It is a bug.

Browser:
- Chrome (desktop) version XX

**Comment by MaklaCof** [comment]
Also both demos [here](https://www.telerik.com/kendo-angular-ui-develop/components/treeview/disabled-state/).

> Can't bind to 'disabledKeys' since it isn't a known property of 'kendo-treeview'.

**Comment by ggkrustev** [comment]
Hi @MaklaCof,

Thanks for the report. Indeed the demo doesn't display a scrollbar, because the page is placed inside an iframe with a static height. We will tweak the demo and use a scrollable container. We will upload an update soon. Until then, you can just open the demo as plunker and review the behavior of the component there.

As to the second issue, the `disabled state` demos work just fine on my end. Could you verify that the issue still present? If it does, could you provide more details how to observe the problem. Thanks in advance.

**Comment by MaklaCof** [comment]
Hi, demos mentioned in second issue is working now.

**Comment by ggkrustev** [comment]
The demo in question is made scrollable when the component is expanded.
Closing the thread as resolved.
