### ISSUE TITLE
the ngModel will still have old value inside dropdownlist selectionChange

### ISSUE THREAD

**Issue by madani2010** [telerik/kendo-angular#1198]
When checking the ngModel bound value inside the selectionChange handler, the value is not changed to the new one.The correct behaviour is working in valueChange event handler but not in selectionChange.
[https://plnkr.co/edit/h8dy60XWsgR1xTp3u1Wf?p=preview](url)

Madani

**Comment by tapopov** [comment]
Hello @madani2010 
This behavior is expected and by design. The component's value should not changed during the navigation if the popup list is open. The `valueChange` event is triggered during navigation if the popup is closed. In case the popup is open, the `valueChange` event is triggered on blur or Enter keypress. This is how the native <select> element works.
