### ISSUE TITLE
Treeview nodes is undefined

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#1205]
## I'm submitting a...
* Bug report

## Current behavior
Not sure if this is bug, but treeview.component.d.ts has property nodes:
```
export declare class TreeViewComponent implements OnChanges, OnInit, OnDestroy {
    .....
    /**
     * The nodes which will be displayed by the TreeView.
     */
    nodes: any[];
```
But when I try to get value from code:
```
@ViewChild("columnsTreeview") private treeviewColumns: TreeViewComponent;
console.info(this.treeviewColumns.nodes);

```
I get undefined.

## Expected behavior
I get whatever nodes are.

## Minimal reproduction of the problem with instructions
[Plunkr](https://plnkr.co/edit/H9j9yItwkzOpWWlUxWhB?p=preview).

## What is the motivation or use case for changing the behavior?
I need to get nodes so I can do something with checked nodes.

Browser:
- Chrome (desktop) version XX

System:
`"@progress/kendo-angular-treeview": "^1.0.0",`

**Comment by ggkrustev** [comment]
Hi @MaklaCof,

The `nodes` property is a `setter`, which cannot be accessed after the data is set. In most cases, it won't be an issue, because the developer is the one that provides the nodes anyway.
If you want to access the internal data, which in most cases won't be needed, then you can check the `data` Observable. Please note that this Observable won't contain whole data, because it is used between treeview groups. *The best option will be to avoid using it and just manipulate the data that is provided to the `nodes` property.*

As to the second question, the `checkedKeys` field is provided by the [`CheckDirective`](https://www.telerik.com/kendo-angular-ui/components/treeview/api/CheckDirective/), which collects the keys based on the TreeView [`checkedChange`](https://www.telerik.com/kendo-angular-ui/components/treeview/api/TreeViewComponent/#toc-checkedchange) event.
You can get the `checkedKeys` wiring the `checkedKeysChange` event provided by the same directive. **Note, that the default implementation of the directive will collect the hierarchical indices into a simple array structure.**

If you would like to gather checked keys in a different manner, then you will need to implement custom check directive as it is shown in our documentation.

https://www.telerik.com/kendo-angular-ui-develop/components/treeview/checkboxes/#toc-modifying-the-checked-state

In the custom directive, you can collect the checked items into a hierarchical manner if this is the business requirement you need to achieve.
