### ISSUE TITLE
TreeView: suggestion for adding checked to checkedChange event

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#1208]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
Currently `checkedChange` event data is `TreeItemLookup`. But from `TreeItemLookup` interface I can not determine if `TreeItemLookup.item` was `checked` or `unchecked`.

## Expected behavior
I expect I can get data if item was checked or unchecked without looking checked keys.

## What is the motivation or use case for changing the behavior?
Now I need to check `ckeckedKeys` if item was checked or unchecked.

**Comment by ggkrustev** [comment]
Hello @MaklaCof,

The TreeView emits `checkedChange` event when an item checkbox is clicked. The TreeView doesn't know anything about the check state of the item when checkbox is clicked. This is determined by the developer who defines the `isChecked` callback. The same function can be used inside the `checkedChange` event to determine the check state of the item.

From the TreeView stand point of view, the checked, expanded and etc. states are persisted outside the component, into special directives. This architecture gives an extremely customizable TreeView component with a lot built-in features provided by specific directives, like the CheckDirective. With that in mind, the TreeItemLookup structure provides information about the current TreeItem, its parents and children. Those details don't include any information about the selected, checked or expanded state, because as I mentioned, they are persisted outside the TreeView component.

We will consider in future whether we could provide more details about the aforementioned state, but for the time being we do not plan to modify the TreeItemLookup structure.

I will close the the thread for now. Please consider posting your suggestion in our UserVoice portal, which will help us to verify users interest in it.

http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback

**Comment by Meerownymous** [comment]
Correct me if I am wrong, but at the time the event is fired, the state is not yet updated. So inside the event handler for checkedChange, I can only determine if the emitted node is selected or not, if I look into the state and see if it is not yet there. This is a bit counterintuitive.
