### ISSUE TITLE
TreeView: checkedChange should be called after checkedKeys are set

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#1209]
## I'm submitting a...
* Bug report 

## Current behavior
Now checkedChange is called before checkedKeys are set.

## Expected behavior
checkedChange is called after checkedKeys are set.

## Notes
I think this is similar to the [past issues](https://github.com/telerik/kendo-angular/issues/627).
I think it is logic to check checkedKeys in checkedChange event, since we do not have information if node was checked or unchecked. ([Related](https://github.com/telerik/kendo-angular/issues/1208))

## What is the motivation or use case for changing the behavior?
I think reasons are the same as in issue [627](https://github.com/telerik/kendo-angular/issues/627).

**Comment by ggkrustev** [comment]
Hello @MaklaCof,

The `checkedChange` event is emitted by the TreeView once an item checkbox is modified. The CheckDirective depends on this event in order to modify its internal checkedKeys state.
That being said, the TreeView `checkedChange` event should be raised before the keys are updated. More details about the architecture of the component can be found in [a related thread](https://github.com/telerik/kendo-angular/issues/1208).

If you would like to be notified once the keys are updated, then just wire the `checkedKeysChange` event, provided by the `CheckDirective` instance:

https://www.telerik.com/kendo-angular-ui/components/treeview/api/CheckDirective/#toc-checkedkeyschange
