### ISSUE TITLE
Treeview: CheckableSettings:enabled (show checkboxes based on input)

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#1225]
## I'm submitting a...
* Documentation issue or request

## Current behavior
I need to display/hide checkboxes based on boolean value. I though [enabled](https://www.telerik.com/kendo-angular-ui-develop/components/treeview/api/CheckableSettings/#toc-enabled) property of CheckableSettings is the one it should do it. But in [this plunk](https://plnkr.co/edit/TjBDJaVtNgHyIzJACihq?p=preview) I don't see any difference what enabled should do.

If enabled is not the right place is there an option in [mode](https://www.telerik.com/kendo-angular-ui-develop/components/treeview/api/CheckableSettings/#toc-mode) settings? None for example.

**Comment by MaklaCof** [comment]
Setting `[kendoTreeViewCheckable]="false"` does do anything either.

**Comment by ggkrustev** [comment]
Indeed, the `enabled` property doesn't hide the checkboxes. Instead, it disables the `checkedChange` event and hence the it stops the update of the attached CheckDirective.
I agree that hiding the checkboxes will be a better solution. We will modify the code in order to do that. The fix will be available most probably next week. I'll update the thread once the fix is out.

**Comment by ggkrustev** [comment]
Another runnable example, just for reference:

https://stackblitz.com/edit/angular-tbwgzw

**Comment by ggkrustev** [comment]
The latest DEV release includes a fix for the discussed issue. Please give it a try and let us know if the problem still persists.
- v1.1.0-dev.201801241312
