### ISSUE TITLE
Grid: column orderIndex property is missing

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#1240]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
Grid column doesn't have input property for order.

## What is the motivation or use case for changing the behaviour?
I want to set order. I think it would make sense, since grid columns (`ColumnBase`) has `orderIndex` which I use on `columnReorder` event.

Special when columns are created with [ngFor](https://www.telerik.com/kendo-angular-ui-develop/components/grid/columns/hidden/#toc-using-structural-directives).

**Comment by rusev** [comment]
`orderIndex` property is not part of the public API of the column. It is implementation detail, required by the column reordering feature. It is intentionally left undocumented in the [column API](https://www.telerik.com/kendo-angular-ui/components/grid/api/ColumnComponent/).

[columnReorder](https://www.telerik.com/kendo-angular-ui/components/grid/api/ColumnReorderEvent/) arguments provides information on old/new index of the column. You can use that index to re-order the columns collection used in the `ngFor` directive.

**Comment by MaklaCof** [comment]
I know that I can use columnReorder event. But why should I be forced to do it?
Problem is I have to recalculate all columns order before I send to server new columns order.

If I move column from 2 to 5 all columns greater then 5 needs to get increase in order. How can I know which columns? Wouldn't be a lot easier to just get all columns order from grid.

**Comment by rusev** [comment]
Currently the public API exposes the `columnReorder` event with the new state for a given column. We may consider exporting more details in the future, but for the time being our suggestion is to use the event and calculate the new order of columns if required.

**Comment by tecsined** [comment]
I think we this could be a great feature for the application. For instance my use case requires to reorder the columns dynamically so if the grid has something that column order  index I could just set that to a variable and have the other of my columns dynamically applied to fix templates. Also I can allows to save grid custom configuration on columns order

**Comment by MaklaCof** [comment]
Basically we need [PersistState](https://demos.telerik.com/kendo-ui/grid/persist-state) of KendoUI for jQuery feature.

**Comment by ngiebel** [comment]
For whatever help it may be to others this is the official documentation on how to persist the settings [https://www.telerik.com/kendo-angular-ui/components/grid/how-to/persist-state/](). Note that it does seem to rely on and expose `ColumnBase` and `orderIndex`.

```TypeScript
public saveGridSettings(grid: GridComponent): void {
   const columns = grid.columns;  //undocumented, returns QueryList<ColumnBase>

   const gridConfig = {
       state: this.grid1Settings.state,
       columnsConfig: columns.toArray().map(
           item => Object.keys(item)
               .filter(
                   propName => !propName.toLowerCase().includes('template')
               )
               .reduce((acc, curr) => ({...acc, ...{[curr]: item[curr]}}), <ColumnSettings> {});
              // ColumnSettings in the example has orderIndex as a property, it would be serialized out anyways
       )
   };

   this.persistingService.set('gridSettings', gridConfig);
}
```

**Comment by tsvetomir** [comment]
There are no plans to expose an input for column order at the moment. The existing read-only field will be listed on [ColumnBase](https://www.telerik.com/kendo-angular-ui-develop/components/grid/api/ColumnBase/#toc-orderindex) which is now included in the public API.

The recommended approach to apply the column order is by creating columns from metadata using ngFor, as in the [Persist State example](https://www.telerik.com/kendo-angular-ui/components/grid/how-to/persist-state/).

**Comment by vtachkov** [comment]
A proper solution would be useful for my organization. The recommended solution here does not work when using column templates and isn't very reusable. How would you recommend being able to save the grid state (at a minimum column order, width, hidden) while also supporting column templates in a application that can have potentially tens of different grid instances?

I've used Kendo UI in AngularJS and it was a much simpler process to save and restore the grid state when loading a page, but it seems to be much more unreasonably difficult with Kendo Angular. I am still learning the nuances with Angular, however, so I don't know how everything works yet.

**Comment by dtopalov** [comment]
After discussing the case with @tsvetomir we decided not to implement the discussed enhancement, as the Grid columns will be rendered in the order they are provided in in the template markup. To implement custom column order when the columns are generated through `*ngFor`, apply the necessary sorting to the column configurations array as demonstrated in the following example:

https://www.telerik.com/kendo-angular-ui/components/grid/how-to/persist-state/

In the latest versions of the package, the event data (more specifically - the old and new column index after manual reordering) available in the Grid `columnReorder` event, provides the actual indexes of the reordered column regardless of whether there are hidden columns present (see https://github.com/telerik/kendo-angular/issues/2810).

**Comment by flogy** [comment]
@dtopalov This is not very helpful as `*ngFor` cannot be used when using columns with column templates, as @vtachkov mentioned. Would it be possible to provide an alternative method to reorder columns programmatically?

**Comment by aldrashan** [comment]
> @dtopalov This is not very helpful as `*ngFor` cannot be used when using columns with column templates, as @vtachkov mentioned. Would it be possible to provide an alternative method to reorder columns programmatically?

Just to chime in here. We started working with the Angular version (coming from the mvc version) of Telerik/Progress like 2-3 years ago, when the persist-state function wasn’t even available.
We had to write a whole wrapper around the GridComponent, just to give our users the same functionality they had in the MVC version, including automatically saving grid state. 

In mvc, for our devs, we could easily define standard columns they could use for numbers, dates, … which would then have standard headertemplates, celltemplates, … . These were easily customizable if need be. This was incredible to have for our junior developers, which were not familiar with the kendo library. In angular, we also had to write column-wrappers to enable this.

While it was, and still is, a bit of a pain to maintain sometimes, we were indeed able to (amongst other things) restore the saved column order, like in this feature request/issue, using *ngFor and with template support.
That said, I would also really have liked to have these things available in the library itself instead of requiring wrappers (for example), as it took quite a chunk of development time and multiple iterations.

**Comment by aldrashan** [comment]
> @dtopalov This is not very helpful as `*ngFor` cannot be used when using columns with column templates, as @vtachkov mentioned. Would it be possible to provide an alternative method to reorder columns programmatically?

Just to chime in here. We started working with the Angular version (coming from the mvc version) of Telerik/Progress like 2-3 years ago, when the persist-state function wasn’t even available.
We had to write a whole wrapper around the GridComponent, just to give our users the same functionality they had in the MVC version, including automatically saving grid state. 

In mvc, for our devs, we could easily define standard columns they could use for numbers, dates, … which would then have standard headertemplates, celltemplates, … . These were easily customizable if need be. This was incredible to have for our junior developers, which were not familiar with the kendo library. In angular, we also had to write column-wrappers to enable this.

While it was, and still is, a bit of a pain to maintain sometimes, we were indeed able to (amongst other things) restore the saved column order, like in this feature request/issue, using *ngFor and with template support.
That said, I would also really have liked to have these things available in the library itself instead of requiring wrappers (for example), as it took quite a chunk of development time and multiple iterations.
