### ISSUE TITLE
Kendo Grid Paging and Filtering not working with Row Reordering

### ISSUE THREAD

**Issue by rgantla** [telerik/kendo-angular#1263]
## I'm submitting a...

* Bug report (Probable)
* Documentation issue or request

## Current behavior

**The Row Reordering (Drag & Drop rows) feature works as expected but, I am cannot get the successive events to work i.e. 
Issue 1: The pagination does not work after dragging and dropping a row.
Issue 2: Upon Filtering, the view gets updated but the underlying data does not**

## Expected behavior

The Filtering, pagination and Row Reordering should work as expected or advertised on the website.

## Minimal reproduction of the problem with instructions

PLUNKER HERE: https://plnkr.co/edit/YUNGYMBvjLSM89BZyVW8?p=preview

**steps to recreate Issue 1: Drag and Drop a row anywhere inside the grid and then click on any page number**

**steps to recreate Issue 2: Type 'vero' (or anything you like) in the filter and then click on the View Details button on the right side to see the selected object below the grid. Compare the value of the object that is populated below the grid to the one you selected (by clicking on View Details button) They are not same.**

**Note: I have tried re mapping the data inside the (filterChange) event but that didn't work. I was able make it work more or less when the pagination was removed.**

## What is the motivation or use case for changing the behavior?

Making the features co exist.

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version 64

System:
- TypeScript version: 2.4.2 
- Node version: 8.9.1
- Platform: Any

**Comment by danielkaradachki** [comment]
Sorry, seems we have missed this issue.

The problem with the paging will occur because this code `this.userData = this.gridData.data` in the drop handler assigns the current view to the original data from which the paging is performed.

The incorrect dataItem is found because the rowIndex is relative to the view. You can either get the dataItem directly from the edit event argument or from the current view by taking the current skip into account:

    viewDetails(eventData) {
        const index = eventData.rowIndex;
        this.selectedItem = this.gridData.data[index - this.state.skip];
        console.log(this.selectedItem, eventData.dataItem);
    }

Also, please note that this issue tracker is for bug reports only. If you have questions regarding implementation scenarios or configuration please open a support ticket.
