### ISSUE TITLE
TreeView: childs are not opened when kendoTreeViewHierarchyBinding and isExpanded

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#1267]
## I'm submitting a...
* Bug report

## Current behavior
Childs are not opened if `isExpanded` is used with `kendoTreeViewHierarchyBinding`.

## Expected behavior
Childs are opened.

## Minimal reproduction of the problem with instructions
Run this [Plunkr](https://plnkr.co/edit/wZtkaDAAnJSr7hXq7Cjt?p=preview).
Open one child.

**Comment by ggkrustev** [comment]
The [`HierarchyBindingDirective`](https://www.telerik.com/kendo-angular-ui-develop/components/treeview/api/HierarchyBindingDirective/) works as expected with a custom [`isExpanded`](https://www.telerik.com/kendo-angular-ui-develop/components/treeview/api/TreeViewComponent/#toc-isexpanded) callback if the returned value is of the correct type, `boolean` in this case. Here is the modified plunker demo:

https://plnkr.co/edit/grHFn5wDdldCCgjh3zuB?p=preview

Could you let me know if I am missing something?

**Comment by MaklaCof** [comment]
Still doesn't work. Updated [plunker](https://plnkr.co/edit/wZtkaDAAnJSr7hXq7Cjt?p=preview). (now it returns boolean)
Screenshot:
![2018-01-29_12-59-57](https://user-images.githubusercontent.com/1589573/35509406-545a0ad2-04f4-11e8-9436-a53d4f24902d.gif)

With your Plunkr I can not collapse childs.

I am searching for a way to expand complete tree view on button click. I think the best/fastest/cleanest solution is to recursively update model (set isOpen to true) and refresh TreeView.

**Comment by ggkrustev** [comment]
Thanks for the clarification. Indeed, this won't be enough to enable proper expand/collapse in the TreeView.

Basically, the component won't expand anything because the 'isOpen' state is never modified. Hence all of the nodes are marked explicitly as collapsed. This is why the treeview shows loading icon forever.
The solution is to simply update the `isOpen` state manually on expand/collapse of the node. Check the updated the plunkr:

https://plnkr.co/edit/o0w1KViFH6yMXuUz0Jms?p=preview

As to the desired functionality 'I am searching for a way to expand complete tree view on button click', I absolutely agree that traversing the data structure and setting the 'isOpen' state to true will be the best solution in this case. It should be done recursively in order to handle multiple levels. The provided demo in my reply works with only one level.

**Comment by ggkrustev** [comment]
Will close the thread as resolved. Please feel free to comment if needed.
