### ISSUE TITLE
[TreeView]: children are not checked if collapsed

### ISSUE THREAD

**Issue by pfoedermayr** [telerik/kendo-angular#1274]
## I'm submitting a...
* Bug report

## Current behavior
When checking a parent node (while the children are collapsed, and was never expanded) the children are not checked.

## Expected behavior
The children shall also be checked even when they are collapsed.

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/ZU1Dx1Rw3CLo4mTSntCy?p=preview

1. Expand 'Furniture'
2. Check 'Furniture'
3. Expand 'Occasional Furniture'
--> Children of 'Occasional Furniture' are unchecked

## Environment

Package versions:
The example is from the demo page for 'Checkboxes' I just added the `kendoTreeViewExpandable` directive.

Browser:
- Chrome (desktop) version 66

System:
- TypeScript version: 2.5
- Node version: 8
- Platform:  Windows

**Comment by ggkrustev** [comment]
The current implementation of the CheckDirective excludes checking the children that are not present in the TreeView. Once the nodes are expanded, then become available and the component check check them automatically.
The solution is to check the children manually, documented in the `Checkboxes` section:
- https://www.telerik.com/kendo-angular-ui-develop/components/treeview/checkboxes/#toc-check-all-children-feature

Please note that we've prepared an enhancement in the CheckDirective that will do the automatic checking on expand out of the box. The feature is released in the DEV channel of the package. You can check the modified plunker that uses this 2.1.0-dev version.
- https://plnkr.co/edit/uBKUajWzUwXdv8YTRPCj?p=preview

**Comment by pfoedermayr** [comment]
Thanks for your answer. And I do understand why it is that way.

Are there any plans to provide all locally available (not necessarily rendered) children withing the `TreeItemLookup` interface on the `checkedChange` event?
(Right now we are comparing `TreeItemLookup.dataItem` which also contains the children to `TreeItemLookup.children`, and use the former one if they do not exist in the `TreeItemLookup`.)

**Comment by ggkrustev** [comment]
@pfoedermayr,
The TreeView component and TreeView groups in particular, knows only the data that was requested on expand. In other words, only the rendered (at least once) groups will be available in the TreeViewLookup table. The other information is not known to the component.  The main reason is that the component treats whole nodes as async data stream even in the cases where the whole required nodes (all levels) are initially provided.

The best I can suggest is to traverse the initial data, which is provided by the developer, in order to access the unexpanded nodes. Also as it was demonstrated in the modified plunker, the directive will dynamically extend the `checkedKeys` on expand. Is this behavior somewhat undesirable or insufficient for your business case?

Could you provide a runnable demo that demonstrates the limitation I am missing the point? This will help us to review the particular scenario and come up with a better solution if possible.

**Comment by pfoedermayr** [comment]
We are currently trying to replace a custom tree implementation with your `kendo-treeview` component.
This tree allows the user (admin) to provide access-permissions to certain areas of our applications.

The checked items in the tree are persisted, and validated if a user tries to access these areas.
Due to this we need to save 'all' checked keys.

### Example
I've prepared an example, which shows what we are doing (simplified), and also contains the workaround we are currently using, to also check all (possibly not yet rendered) children.
https://plnkr.co/edit/ICErlFXc1up6nby7rQhZ?p=preview
(This is a extended version of the `CustomCheckDirective` from your demos)

### Scenario Parent -> Child
Admin allows a user to access area `Permission A` (think of it as a kind of dashboard - grouping certain functionality), by doing this he also grants access to all child-areas (`Permission A1`, `Permission A2`, `Permission A3`).

As a result we save all 4 keys  (`Permission A`, `Permission A1`, `Permission A2`, `Permission A3`), which is also the reason why are we are not loading the children on demand.

### Scenario Child -> Parent
Admin grants access to `Permission A1`, this results in also granting access to `Permission A`.
We are going to save `Permission A`, `Permission A1`.

**Comment by ggkrustev** [comment]
Thanks for the detailed explanation. I fully understand the limitation you are hitting and I do believe that with a custom CheckDirective and a few more tweaks the desired functionality could be achieved. 

#### Scenario Parent -> Child
In this case, you won't be able to rely on the TreeItemLookup as it contains only the loaded nodes. The solution is to traverse the whole data and gather the children checked keys. This whole exercise should be done in the `checkedChange` event.

#### Scenario Child -> Parent
This is relatively easy, because the provided TreeItemLookup is sufficient. Of course, the built-in logic of the CheckDirective for checking the parents in this business scenario is irrelevant. The one should gather the parents' checked keys and update the keys collection.

Here is the modified demo that utilizes the suggested implementation:

https://plnkr.co/edit/w3QyrZFlxL6RrcjY0214?p=preview

- Parent -> Child check is based on the relation between the parent and child data items
- Child -> Parent is based on the TreeViewLookup state

Please note that the given demo doesn't claim full and bug free implementation. You will need to tweak the custom CheckDirective implementation to fully cover your business needs.

**Comment by pfoedermayr** [comment]
Thanks you for your effort, really appreciated.

We will incorporate your suggestions/tweaks into our custom `CheckDirective`.
