### ISSUE TITLE
TreeView: css - item not expanded to full content

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#1279]
## I'm submitting a...
* Bug report

## Current behavior
Treeview item:
```
<span class="k-in" data-treeindex="0">
```
is not properly expanded if content is flex layout.

## Expected behavior
Upper(`<span class="k-in" kendotreeviewitemcontent ...`) element has correct width.

## Minimal reproduction of the problem with instructions
Run [this plunkr](https://plnkr.co/edit/JokFKBzPDdrIvFdwhtrs?p=preview).
Click(select) first item

## What is the motivation or use case for changing the behavior?
This looks wrong:
![chrome_2018-02-01_08-02-48](https://user-images.githubusercontent.com/1589573/35665377-50ac371e-0726-11e8-8e13-220551444789.png)

**Comment by gyoshev** [comment]
@MaklaCof the `.k-in` element width is controlled by its content width. In the provided example, the flexbox container (`div.item`) does not have correct width, because of its items' styles. Using `width` instead of `flex-basis` to set the items width solves the problem. [See this Dojo](https://dojo.telerik.com/unEKuP) for an illustration of the problem.

**Comment by MaklaCof** [comment]
But you [demo](https://www.telerik.com/kendo-angular-ui-develop/components/treeview/#toc-basic-usage) has similar problem.

`<span is to large`:

![chrome_2018-02-05_18-16-13](https://user-images.githubusercontent.com/1589573/35818654-ed0fff28-0aa0-11e8-89cc-e5f4c9264a7b.png)

**Comment by gyoshev** [comment]
@MaklaCof while this may look similar, this is a different problem caused by other styles. The item content currently does not allow horizontal scrolling due to the example's styles (which hide the scrollbar) and the TreeView group styles (which do not allow items to be larger than the group contents. The latter is not correct, and can be addressed with the following workaround:

```css
.k-treeview .k-item > .k-group,
.k-treeview > .k-group {
  overflow: visible;
}
.k-treeview .k-item > .k-group.ng-animating,
.k-treeview > .k-group.ng-animating {
  overflow: hidden;
}
```

We'll be adding this fix to the themes, but it won't address the issue with using `flex-basis` instead of `width`.

**Comment by gyoshev** [comment]
A fix for this has been released in `@progress/kendo-theme-default@2.47.6`

**Comment by MaklaCof** [comment]
Hi @gyoshev 
I still think this is a bug. I prepare another example [here](https://plnkr.co/edit/7E4MA6RYQcHlZOZCMzE1?p=preview).

I really think that item should use all width space that is available for kendo-treeview.
TreeView width is 100% (green background), but item width is not (yellow background). 

I don't see any reason, why item(`<span class="k-in"...`) width is not automatically stretched to all available width.

**Comment by gyoshev** [comment]
@MaklaCof I'm afraid that changing the `k-in` elements to stretch to the whole width of the row will break the look of selection and focus states that are currently in place. You can add a `.k-in { width: 100%; }` rule to fix this in your application, here is the [updated plunker](https://plnkr.co/edit/G94WVx6PmlTpqR4GmACn?p=preview).
