### ISSUE TITLE
TreeView: refresh method missing

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#1287]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
There is no refresh method.

## Expected behavior
Refresh method on TreeView.

## What is the motivation or use case for changing the behavior?
I have a `TreeView` with `kendoTreeViewExpandable` and `kendoTreeViewHierarchyBinding`.
Complete `TreeView` is expanded.
Then I remove one (out of 100) child node and add new one, but change is not visible in `TreeView`.
I must collapse parent node and then expand to view changes.

I think refresh would solve my problem. But any solution how to force `TreeView` to re-render child nodes would be OK.

**Comment by ggkrustev** [comment]
Hi @MaklaCof, we changed the change detection strategy of the component in order to mitigate such dynamic mutations. Could you verify that you are using the latest release of the component, namely 2.1.1?

If yes, could you share a repro demo that demonstrates the issue? Thus we will be able to better understand the case and find a suitable solution.

**Comment by MaklaCof** [comment]
It works very nicely. Animation (closing removed and expanding added nodes) looks really good. 👏
