### ISSUE TITLE
PDF Export from Sorted Grid renders wrong header icons

### ISSUE THREAD

**Issue by mav442** [telerik/kendo-angular#1317]
Using the most recent build of Kendo UI for Angular, when exporting a grid with sorted data as a PDF, the up arrow renders as an apostrophe "'" and the down as a left parentheses "(".

This can be reproduced directly from any of the Plunkers in the PDF export section of the online documentation. I have extended one here: https://plnkr.co/edit/bOgXLOo9ZMbvnQMucleE?p=preview.

Is there a workaround for this issue?

**Comment by danielkaradachki** [comment]
Sorry for the delayed reply.

The problem occurs because the theme is loaded from a different domain. The icon should be exported correctly if the theme is loaded from the same domain or if the server includes a CORS header and there is a crossorigin attribute on the link:
https://plnkr.co/edit/3irgVh5KVSzCSjjcAvOo?p=preview

Note that there is still an issue with the font icons export in Internet Explorer. We are currently working on it and I will update the issue as soon as there is a fix.
