### ISSUE TITLE
Grid: OnPush strategy -> detectChanges just on single row

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#1325]
Hi to all,
i have a paginated grid with onPush strategy and i just would like to call a detectChanges on single row and not an all grid component just because i change status property of single dataItem.

I don't use immutable for this approach so i go directly on dataItem property binded to a row class callback.

Thanks.

**Comment by rkonstantinov** [comment]
Hi @meriturva,

I'm afraid that this is not possible. The row is not a component, nor if it was, it should have its changedetector exposed and accessible from the outside world. 

If you want to update only a single item, then you will need to change its instance instead of mutating its properties. Such approach is demonstrated in [this plunker](https://plnkr.co/edit/e1jBxNmLqWoVqdf9k6RD?p=preview).

**Comment by meriturva** [comment]
Hi @rkonstantinov ,
what i mean is that detection check will be done on every rows.
See: https://plnkr.co/edit/C3gsmvvbecipSLo9JOgZ?p=preview

```
public click() {
      const [ firstItem ] = this.gridData;
      this.gridData[0] = {...firstItem, ProductName: Date.now() };
      this.gridData[1].ProductName = Date.now();
    }
```
We know that with virtualisation and pagination we don't have so much rows on DOM but i just would like to have a feedback on a strategy to directly dirty a single row.

**Comment by rkonstantinov** [comment]
Indeed, clicking on the button in the sample will trigger a change detection check. This is how the change detection in angular works. In order to prevent this you will need to detach the change detector. However, this will require manually tracking and triggering refresh for the appropriate child components. Which I find quite inconvenient or event impossible for general use, due to the complex structure of the Grid component.
Thus, such fine grain control over the Grid change detection, will require a different implementation of the component. As it will completely change the way developer can interact with it, as well as remove some of the "automagical" functionalities.

**Comment by meriturva** [comment]
You are right about change detection!
Many thanks for your answer!
