### ISSUE TITLE
Not locked column not properly displayed in IOS devices

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1354]
When using a custom `<ng-template kendoGridToolbarTemplate>` the toolbar is misaligned. Furthermore, if we use a `<kendo-switch></kendo-switch>` within the ng-template the content of the locked column will not be displayed.

Check the following sample plunker demonstrating the undesired behavior:

[https://plnkr.co/edit/xeY4wuaKaTveC0TT2wCc?p=preview](https://plnkr.co/edit/xeY4wuaKaTveC0TT2wCc?p=preview)

**Comment by gyoshev** [comment]
A workaround for the issue is to set a `background-color` of the grid table:

```ts
@Component({
  encapsulation: ViewEncapsulation.None,
  styles: [`
    .k-grid-table {
        background-color: #fff;
    }
  `]
})
```

It appears that the kendo-switch triggers a glitch that hides the content -- interestingly enough, the text in the column can still be selected. I'll open a PR for the theme shortly.

I could not observe the toolbar misalignment on iPhone 6s with the latest iOS, and discussing that will dilute the issue from the title, so consider opening another issue if that persists.
