### ISSUE TITLE
Error while loading Kendo UI Grid angular 4.2.2

### ISSUE THREAD

**Issue by naouaro** [telerik/kendo-angular#1376]
I have updated Rxjs to 5.5.7 as mentioned on documentation 
but I got this error 

 Error Uncaught (in promise) TypeError : 
this.changegedSource.asObservable(...).pipe is not a function 

Is anyone facing this Error ?

**Comment by tsvetomir** [comment]
Please check that the package version is not being held back by package-lock.json. Remove it and re-install the packages to be certain.

**Comment by naouaro** [comment]
Actually, I have found two versions of Rxjs in package-lock.json, but they are both higher than 5.5.
However, I built a fresh project which meets all requirements with no package-lock.json at all, but still get the same error.
I am working on ASP.Net/Angular project.

**Comment by tsvetomir** [comment]
Please, submit a support ticket and include the sample project, if possible. We'd love to help!

I'll close this issue as it seems to be related to the specific project.

**Comment by andrewgpl** [comment]
Hi,
could you please describe the solution? I have exactly the same error (ASP.NET Core 2.0, Angular 5.2.9, RxJS 5.5.7, Kendo Grid 2.1.2).

**Comment by tsvetomir** [comment]
@andrewgpl do you have as sample project we can test with? Also, what does `npm ls rxjs` print in your project?

**Comment by andrewgpl** [comment]
@tsvetomir npm ls rxjs returns rxjs@5.5.8 (rxjs was updated recently)
I have a sample project - how can I send it to you?

**Comment by moutono** [comment]
Hi. I have the same problem.
I am trying to update my libraries and got this error:
this.changedSource.asObservable(...).pipe is not a function.

It only happens when I navigate to a component that contains a grid.

I deleted package-lock.json.
Using rxjs@5.5.8. 
I have tried different grid versions. 
Currently I am on:
@progress/kendo-angular-grid       2.1.3-dev.201803221421

But the error still occurs.

**Comment by tsvetomir** [comment]
@andrewgpl thanks for the sample project. I started it with `npm install && dotnet run`, but I didn't get any errors. I'm using dotnet 2.1.3. Did I miss something?

@moutono try removing node_modules as well, as a previous install might have dropped concurrent rxjs versions.

**Comment by andrewgpl** [comment]
@tsvetomir thanks for checking the sample. And you didn't miss anything - everything is ok when running from the console. Seems like a workaround for the time being ;) Now I have to find what is wrong with my VS setup... Thanks anyway!

**Comment by tsvetomir** [comment]
We recommend the [new project template](https://docs.microsoft.com/en-us/aspnet/core/spa/angular?tabs=netcore-cli) for .NET Core projects, see the [updated help article](https://www.telerik.com/kendo-angular-ui/components/installation/dotnet-core/). It's built around the Angular CLI instead of a custom build which makes it a lot more predictable.

**Comment by craghavendra21** [comment]
Hi, I am also facing the same issue. Please let me know what should i do for resolving this

**Comment by tsvetomir** [comment]
@craghavendra21 the pacage list looks okay. Please delete "package-lock.json",  "node_modules" and reinstall the packages.
