### ISSUE TITLE
Kendogrid ellipsis style issues with scrollable="none"

### ISSUE THREAD

**Issue by rdnscr** [telerik/kendo-angular#1388]
* Bug report

## Current behavior
If i use a kendo grid and have one column with a width of "*" and all the other have fixed sizes there are layouting issues if scrollable is none.
The ellipsis functionality is in this case not properly working for the "*" column. It only works if i set there reandomly a max-width. If scroll mode is not set to none everything works as expected.

## Expected behavior
I should not be required to set max-width for td's in case of scroll mode none and the described conditions.

## Minimal reproduction of the problem with instructions
You can reproduce the issue with this plunkr:
https://plnkr.co/edit/cyiX3KG9f0aPsiuqtje3?p=preview
The plunkr originates from your scrollmode none example and i added the existing conditions. If max-width is removed from the custom styles you can see the issue.

## What is the motivation or use case for changing the behavior?
I don't understand why max-width is implicating here and i assume therefore this is not intended beahvior.

**Comment by elena-gancheva** [comment]
Hi, @rdnscr, thank you for submitting this. The case is that is you have a Kendo Grid **without** scroll mode (or its property `scrollable` set to `none`) we render a table with `auto` sizing, so that it can be resizable and its content too. Because of this the `text-overflow` is not `ellipsis` clipped. When you have a **scrollable** Kendo Grid, we render a table with fixed layout, because of the scrolling functionality and because the advantage of speed rendering time over the ‘automatic’ layout. When fixed layout, cells use `overflow` property to determine whether to clip any overflowing content, **but** only if the table has a known width. This is a desired behavior and if you want to clip your text when Kendo Grid has `scrollable=”none”` property you could try:
1. Set `table { table-layout: fixed; }` css rule, **but** it will disable the automatic resize of the table.
2. Set `max-width` on each `td` of the `col`, which text is overflowing and should be clipped. For responsive layouts use the `max-width` CSS property to specify the effective minimum width of the column, or just use `max-width: 0;`. Also, the table will need a specific width, and the columns will have their width set as percentage of the total width. 

Hope this helps!
