### ISSUE TITLE
Popup problem

### ISSUE THREAD

**Issue by Kalemstorm94** [telerik/kendo-angular#1397]
Hello!

I would like to report a bug on the Popup component. If I have a popup too big, then the component will not allow me to scroll the page, to see the bottom of the popup. 
https://plnkr.co/edit/Ezq6Isq1u02RdT9djU3U?p=preview

This is happening inside every browser (Firefox, Chrome, Edge). 
I didn't post the versions of the packages because I've used the Plunkers that are on the KendoUI Angular website: 
Popup (first example on page)- https://www.telerik.com/kendo-angular-ui/components/popup/ 
Dropdowns (first example on page)- https://www.telerik.com/kendo-angular-ui/components/dropdowns/dropdownlist/.

**Comment by ggkrustev** [comment]
The Popup element is absolutely positioned in the document. Because of that and the HTML/BODY `overflow: hidden` styling, the popup won't be visible.

The issue is CSS based and is not related to the Popup functionality nor to its rendering. The case should be handled with proper HTML styling. For instance, you can enable scrolling inside the Popup and restricts its height to smth specific, e.g. 600px.

https://plnkr.co/edit/1O6wlzszQDUqY9p8BMe2?p=preview

I will close the thread as the discussed issue is not a bug or feature request.
