### ISSUE TITLE
Splitter not emitting events

### ISSUE THREAD

**Issue by beauxjames** [telerik/kendo-angular#1409]
I'm submitting a bug

* Bug report

There are some basic event emitters. In the following Plunker, note that collapseChange is not getting emitted and an undefined is coming back from the layoutChange emitter on resize and an empty object on collapse. SizeChange is getting fired but returns no information about which panel may be changing.

Expected Behavior:
Splitter core to emit events on all changes with additional information on what changed.
Panels to emit events for both change in size and collapsing.

Minimal reproduction of the problem with instructions
https://plnkr.co/edit/zUsTuJir30ko82FyfPFV?p=preview

Need to track all the events for resizing purposes of the content.

## Environment
@progress/kendo-angular-layout @2.2.1
Chrome/Mac

**Comment by gyoshev** [comment]
The collapseChange event is misspelled, thus not triggered -- the name of the event is collapse**d**Change, in order to allow two-way binding of the `collapsed` property. Here is the [updated plunker](https://plnkr.co/edit/JaqeWnkKCKYjt6AYg5gg?p=preview).

Can you please elaborate what "resizing purposes of the content" means?

**Comment by gyoshev** [comment]
Closing this due to a month of inactivity. In case the problem persists, please provide more information to reopen the issue.
