### ISSUE TITLE
Issue on locked column grids when using kendo popup as a dropdown menu.

### ISSUE THREAD

**Issue by abogdan0505** [telerik/kendo-angular#1411]
I'm trying to use kendo-popup inside a grid with locked columns.

Steps to reproduce: 
1. Scroll to the last column of the grid.
2. Click the show popup button on the last row of the grid

Result: the dropdown is going under the grid.

Plunker: https://plnkr.co/edit/UIxjefbFIDS6M9bVCBYJ?p=preview

The issue seems to come from the grid having the overflow hidden property. Therefore no matter what dropdown I use, for locked column grids I will still have this issue.
A possible fix would be for the popup to change its orientation but that doesn't happen either.

Is there a way in which I can have a fully visible dropdown menu inside a grid with locked columns ?

**Comment by rkonstantinov** [comment]
The behavior you have described is due to the fact that the popup is placed within the Grid. As the Grid content is scrollable, the popup element cannot "escape" the stacking context. 

In order to correct this you will need to use `PopupService` instead of `PopupComponent` and use its `appendTo` option to attach the popup to container  higher in the DOM tree. More details on this can be found in [this help article](https://www.telerik.com/kendo-angular-ui/components/popup/service/#toc-appending-to-specific-containers). 

[Here](https://plnkr.co/edit/qASrmjerehHggEPdLtbI?p=preview) you can find a modified version of the plunker, which demonstrates this in action. Please note that the `AppComponent` expose its `ViewContainerRef` as a field. It is later accessed in the `DropdownComponent`, where the `AppComponent` is injected in order to provide an append container for the popup.

**Comment by rkonstantinov** [comment]
To detect that anchor is outside the viewport you could use the `anchorViewportLeave` event. 
https://www.telerik.com/kendo-angular-ui/components/popup/#toc-closing-after-leaving-the-viewport
If you have additional questions please open a [support ticket](https://www.telerik.com/account/support-tickets).

**Comment by abogdan0505** [comment]
That's the point. You cannot use anchorViewportLeave in that scenario because there is no kendo-popup component to put it on.

**Comment by rkonstantinov** [comment]
The PopupRef instance returned by the PopupService also has a [anchorViewportLeave](https://www.telerik.com/kendo-angular-ui/components/popup/api/PopupRef/#toc-popupref) event

**Comment by abogdan0505** [comment]
I really appreciate your help. 
Is there any documentation on how we could use the anchorViewportLeave event when using popupService ?
Or can you help me out with an example on the [plunker ](https://plnkr.co/edit/qASrmjerehHggEPdLtbI?p=preview) that you provided above?

**Comment by abogdan0505** [comment]
Should this work ?
@HostListener('window:resize')
  ngDoCheck() {
    if (this.popupRef) {
      this.popupRef.popupAnchorViewportLeave.subscribe((e) => {
        this.popupRef.close();
        this.popupRef = null;
      })
    }
  //   const w = this.popupRef.popupAnchorViewportLeave;
  }
