### ISSUE TITLE
Kendo Dialog in kendo Grid Detail rows style error

### ISSUE THREAD

**Issue by baiyunchen** [telerik/kendo-angular#1431]
When we use kendo dialog in Kendo Grid Detail row, the style is error.
Version Info:
 "progress/kendo-angular-dialog": "^3.2.0",
  "progress/kendo-angular-grid": "^1.8.0",

Chrome: 65.0.3325.181

please reference  picture:
![2018-03-31_09-58-05](https://user-images.githubusercontent.com/10071911/38158613-864edb7a-34ca-11e8-8b42-c6bc8ab44313.gif)

**Comment by gyoshev** [comment]
To resolve this issue, the `kendo-dialog` element must be outside the `kendo-grid` element. This can be resolved either by moving it outside of the detail row, or by using the [Angular service](https://www.telerik.com/kendo-angular-ui/components/dialogs/dialog/service/).

The root cause of the issue is that the `kendo-dialog` element is inside an element with a `transform` style (the `kendo-grid` content container), which prohibits the `position:fixed` style of the `kendo-dialog` element to fill the whole page.
