### ISSUE TITLE
Are there plans for a responsive grid?

### ISSUE THREAD

**Issue by jawache** [telerik/kendo-angular#145]
Whats the best solution to render the grid responsively?

Is this possible right now and if not is it in the works?

I've noticed 3 things when looking at the official plunker (and my implementation) http://plnkr.co/edit/wifRDOYEmZNEu0dL3UHn?p=preview

1. When the viewport is small and **no explicit widths have been set** then it just squeezes everything together like so:

![selection_014](https://cloud.githubusercontent.com/assets/897523/21400105/66796c8a-c7a6-11e6-9335-dd05404b4741.png)

2. When the viewport is small and explicit widths **have** been set for **all** columns. It's scrolls horizontally.

3. When the viewport is small and explicit widths have been set for **only a subset** of columns then the **_columns w/out widths disappear_**, e.g. in the plunker above the ProductName column disappears because it's the only column without an explicit width.

I think a good solution is to be able to set either a min-width for columns so it scrolls horizontally on mobile and stretches to fit the viewport on desktop.

Or collapse into a responsive table like bootstrap.

Cheers,

Asim

**Comment by yordanov** [comment]
There are two rational aspects of rendering responsive Grid:
1. Hide columns under specific break point (screen width).
In this case one would need an option to specify which column to be or not to be hidden.
The implementation could be similar to what we have in the [jQuery Grid](http://docs.telerik.com/kendo-ui/api/javascript/ui/grid#configuration-columns.minScreenWidth).

2. Trigger horizontal scroll when grid’s width is less than sum of columns’ widths.
That means, as you suggest, there must be an option for one to set different min-width values per column. 

In addition, custom responsive logic could also be achieved using ` ngIf` directive inside `<kendo-grid-column>`.

We do not consider Bootstrap’s table [reflow](http://v4-alpha.getbootstrap.com/content/tables/#reflow) approach applicable for a Grid component, as the Grid is not just an html table and has a lot of UI-related features to consider, such as grouping, frozen columns, inline-editing etc.

Would you mind sharing what would be the application scenario in your case, and what type of configurations would you expect?  This will help us define what set of options we need to expose in order to achieve the most common expected behavior.

**Comment by tsvetomir** [comment]
We decided to implement a set of responsive features that will address the initial concerns. Details to follow.

**Comment by gyoshev** [comment]
The [responsive columns](http://www.telerik.com/kendo-angular-ui/components/grid/responsive/) feature was shipped with version **0.26.0** of the grid. It offers flexibility for changing the column layout on different devices (see the demo in the docs) -- you can linearize columns or hide them altogether, depending on the size of the viewport.
