### ISSUE TITLE
Masked textbox is wrongly marked as invalid

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1461]
When adding a valid number to the masked textbox it is marked as invalid.

Check the following sample plunker:

[https://plnkr.co/edit/wEgohT3J8iOzUvnEHmY7?p=preview](https://plnkr.co/edit/wEgohT3J8iOzUvnEHmY7?p=preview)

a possible workaround is to disable the mask validation by setting the maskValidation input property to false - [maskValidation]="false"

**Comment by rusev** [comment]
This behavior is because empty string is set as prompt character. I'm not 100% sure that we should support this as it seems like bad UX; the user will not be able to see that there are more characters to fill.

We don't support it with the current validation logic right now. We should re-work it if we need to support the scenario. Can someone justify the usefulness of having empty char for placeholder?
