### ISSUE TITLE
Chart legend color become black when use custom color

### ISSUE THREAD

**Issue by kokhooi** [telerik/kendo-angular#1476]
* Bug report 

## Current behavior

When use custom color on bar chart, legend color doesn't match

## Expected behavior

When use custom color on bar chart, legend color should match

## Minimal reproduction of the problem with instructions
Plunker link :- https://plnkr.co/edit/ZPJuZhZxLFTQFhGm8OGM?p=preview

**Comment by danielkaradachki** [comment]
With the code that you are using you are setting the series color to 'color' which is not a valid color.
If you wish to specify the field from the data that holds the points color then you should use the [colorField](https://www.telerik.com/kendo-angular-ui/components/charts/api/SeriesItemComponent/#toc-colorfield) option(defaults to 'color').

Otherwise you should bind a valid color to the series:
https://plnkr.co/edit/2sG516mKkqj148TtgTOA?p=preview
