### ISSUE TITLE
Window maximizing unpolished

### ISSUE THREAD

**Issue by Neaco** [telerik/kendo-angular#1489]
## I'm submitting a...

* Bug report 

## Current behavior

Maximizing the window leaves a white space on the right and under (for scrollbars I guess).
Also, the window can still be moved.

## Expected behavior
When there is no scrollbar, the window should take the whole space and be unmovable.

## Minimal reproduction of the problem with instructions

Open the plunker of the example window.
https://www.telerik.com/kendo-angular-ui/components/dialogs/window/

## What is the motivation or use case for changing the behavior?

I am considering kendo UI for an enterprise application, and I am looking for a framework that offers good UX. Users would not like a maximized window that can be moved and leaves white spaces.

This might not be at the top of the priority list, but I still think it should be considered as a bug and fixed.

**Comment by Raisolution** [comment]
Hi @Neaco,

Thank you for reporting this. The initial bug regarding the white space on the sides is a problem in the `kendo-theme-default` package and the fix will be published soon.

Regarding the second question, this behavior is by design. The maximizing is considered changing of the state and in this case only the [stateChange](https://www.telerik.com/kendo-angular-ui/components/dialogs/api/WindowComponent/#toc-statechange) event is emitted. The `height` and `width` property would still store the actual values that the Window should be restored to.

**Comment by Raisolution** [comment]
Hi @Neaco,

the fix for the white space on the sides is available in the `kendo-theme-default` package v2.46 and later.

Also a new version 3.5.0 of the `kendo-angular-dialog` package has been released, in which the Window is not draggable when maximized.
