### ISSUE TITLE
Kendo Components + Bootstrap z-index bug

### ISSUE THREAD

**Issue by anagram92** [telerik/kendo-angular#1506]
When I use a component from the ngx-bootstrap library inside your components, they are always rendered behind the kendo's components.
This was detected on the grid.

It follows an example here there's a dropdown inside a cell (column ID) and outside the grid.
https://plnkr.co/edit/EAntQav6eRUYorMeFSiZ?p=info

Something similar happens when a modal is used inside the tab-strip component where it gets broken.

**Comment by danielkaradachki** [comment]
The grid cells have `overflow:hidden` style by default. You can override it for the column in order to allow the popup to be shown. The ngx-bootstrap dropdown also seems to have `container="body"` configuration that can be used to render the popup outside the cell which should also resolve the problem.

Also please note that this issue tracker is for bug reports only. If you have questions regarding implementation or integration scenarios please open a support ticket.
