### ISSUE TITLE
Window : unwanted resizing when dragged to the right of the screen if width not set

### ISSUE THREAD

**Issue by Neaco** [telerik/kendo-angular#1508]
## I'm submitting a...

* Bug report 

## Current behavior

If a window is created without a width and its content has no defined width, it will resized when dragged to the right of the screen.
If the window is resized this behavior stops.

## Expected behavior

Window shouldn't resize.

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/KODngVdaUXlDc8yW7qn7?p=preview

## What is the motivation or use case for changing the behavior?

Small UX fix.

## Environment

Browser:

- Chrome (desktop)
- Firefox

**Comment by Neaco** [comment]
Also, if you try to resize the window from the left side to a width larger than the screen, it will drag the window instead.

![2018-05-03_15-13-29](https://user-images.githubusercontent.com/22844693/39563975-d22bcdda-4ee4-11e8-94dd-953d803a7641.gif)

**Comment by Raisolution** [comment]
Hi @Neaco ,

Thank you for reporting the problems. The fix for the initial issue (dragging a Window without explicitly set width to the edge of the screen) is available in version `3.6.1`. The width will be applied the first time the Window is dragged.

The reason for the second issue was incorrectly applied `max-width / max-height` styles and the fix is available in the latest versions of all Kendo theme packages.

**Comment by Neaco** [comment]
Thanks for the answer and the quick fix.
