### ISSUE TITLE
Wrong overlay posistioning for dialog inside bootstrap grid inside tabstrip tab in IE

### ISSUE THREAD

**Issue by markasztalos** [telerik/kendo-angular#1513]
If I try to apply the structure above, the dialogs overlay and the dialog itself fills only the current tab.

Bootstrap grid means a row and a column div, for exampe: `<div class="row"><div class="col-12"></div></div>`

The error can be reproduced only in Internet Explorer, not in Edge (not even in emulation mode).

Please check the following demonstration
https://plnkr.co/edit/j6BGnbSdMM7XjDcFc85G?p=preview

**Comment by gyoshev** [comment]
It appears that this problem is caused by the specific configuration of the dialog. You can workaround it in one of the following ways:

- setting `position:static` on the `col-12` element ([see plunker](https://plnkr.co/edit/SNqFWdMrpsadHCcSvClD?p=preview))
- moving the dialog element outside the bootstrap grid using the [dialog service](https://www.telerik.com/kendo-angular-ui/components/dialogs/dialog/service/)
