### ISSUE TITLE
ValueAxis narrowRange property should not be applied to the 100% stacked series

### ISSUE THREAD

**Issue by vbakavets** [telerik/kendo-angular#1526]
## I'm submitting a...
* Bug report 

## Current behavior
If the **narrowRange** property  is set to _true_ for a 100% Stacked Bar Chart it can lead to a wrong appearance.

## Expected behavior
I think that the **narrowRange** property should not affect value axis and it's min value should be always 0.

## Minimal reproduction of the problem with instructions
See the plunk: [example](https://plnkr.co/edit/xNAbvkK8cRGxyg48i6GX?p=preview).
Notice that the first value is two times bigger than the second but visually it looks vice versa.

**Comment by danielkaradachki** [comment]
I am not sure if I understand the issue but by setting narrowRange to true you are explicitly specifying that the axis should not start from zero. If you always want the axis to start from zero set the narrowRange option to false. Ignoring the user configuration because a specific series are used is not something we are willing to do.
