### ISSUE TITLE
kendo-menu: Possibility to define the men u expand arrows

### ISSUE THREAD

**Issue by EricSch** [telerik/kendo-angular#1531]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
There is no way to get rid of the expand arrow in the top menu item. There is always this span element present 
```
<span class="k-icon k-menu-expand-arrow k-i-arrow-60-down" role="presentation">
        </span>
```

## Expected behavior
Possibility to replace the expand arrow with a own icon or to disable it

## Minimal reproduction of the problem with instructions
See samples

## What is the motivation or use case for changing the behavior?
We need a top menu with only an icon/symbol, no text

**Comment by MaklaCof** [comment]
It also cause problems if you use template and inside template `a` html tag. I think `<span class="k-icon k-menu-expand-arrow...` should be visible (`*ngIf`) only when there are any sub-childs.

Idea with `a` tag is that user can open menu item in new tab (middle mouse click) and that is possible only with `a` and not with select event as your [routing demo](https://www.telerik.com/kendo-angular-ui-develop/components/menu/routing/) suggested.
But because of `span` not the whole menu item is clickable:
![chrome_2018-05-12_07-37-31](https://user-images.githubusercontent.com/1589573/39954017-5927293c-55b7-11e8-94ed-306442565af1.png)
Here is [plunkr](https://plnkr.co/edit/dIf3u6hAICVJGoKExlZ0?p=preview) from screenshot.

**Comment by danielkaradachki** [comment]
@EricSch 
Currently there isn't an option to skip rendering the arrows. You could hide them via CSS:

        .k-menu-item .k-menu-expand-arrow {
          display: none; 
        }

@MaklaCof 
The arrow should be rendered only if the item has children. The right side will not be clickable because of the items padding style which can be overridden via css:
https://plnkr.co/edit/URmDvCNhedrv6O0ifxeV?p=preview

The solution is not ideal as the keyboard navigation will not work for the link. A possible solution is to set the items [url](https://www.telerik.com/kendo-angular-ui/components/menu/api/MenuItem/#toc-url) field and prevent the link navigation on left click in the select event.

In general, one approach that we have considered but dismissed as overly complicated, is to provide a template for the entire content and some directives that enable the default behavior for the elements in the template. @EricSch, @MaklaCof will this work for you?

**Comment by EricSch** [comment]
@danielkaradachki 
This will help, but I think, the component should provide that option. But as long I can't open the menu always with a click (see #1530), I can't use it. Thanks

**Comment by MaklaCof** [comment]
I already solve it with overriding css. Normally I don't like overriding css. (You never know what will not work in the future).

@danielkaradachki  I think template for the entire content would work for me.

**Comment by danielkaradachki** [comment]
Link template which represents the entire content is available in the latest version. 
https://www.telerik.com/kendo-angular-ui/components/menu/templates/#toc-link-template
https://www.telerik.com/kendo-angular-ui/components/menu/routing/

At least for now we will not include an option for the arrows. Will reconsider if this becomes a common request.
