### ISSUE TITLE
How to Check all Children in TreeView Without having not Expanded it

### ISSUE THREAD

**Issue by brad1218008** [telerik/kendo-angular#1643]
## I'm submitting a...

* Bug report 

## Current behavior
Here is Plunker Example:
https://next.plnkr.co/edit/wm5juqbDiFkjv0WJ

Checked the first Item "Furniture" without expanding it.
the Checked Keys would just get Item only"Furniture" even if I had 
checked "Check all children" on the top.

## Expected behavior

I want to checked all children even thought I hadn't expanded it.

I had try to expand all node at initial, but It would face asynchronous problem.
And If data Source is large , It will take a long time to expand and unexpand.
So I don't think it's a good solution for it.

## Environment

Package versions:

```
+-- @progress/kendo-angular-treeview@2.2.0
```

Browser:

- Chrome (desktop) version 67.0.3396.87

System:
- Node version: 8.11.2
- Platform:  Windows 10

**Comment by ggkrustev** [comment]
Hi @brad1218008,

indeed, the component won't be able to add aa checked keys before all nodes are expanded. Due to asynchronous data load the child nodes are not available before the expansion is done. Hence the component doesn't know anything about their existence beforehand. This is documented in the *Checkboxes* section:

https://www.telerik.com/kendo-angular-ui/components/treeview/checkboxes/#toc-check-all-children-feature

The best solution in this case is to map the data, as you are in control over it, and extract the checked keys to the treeview. Once they are set, the component will mark the newly expanded nodes as checked.

I will close the thread as the discussed behavior is known and documented flavor of our implementation. Please comment below if I am missing something.

**Comment by vickyadi3** [comment]
Hi,
I am also facing same issue. If parent are not in expanded state, So without expaneding parent I want  to checked(checked all children) all his related Children how to do that? Plze help someone help me regarding this. I will share my scenario with below image.
![tree](https://user-images.githubusercontent.com/29104204/77999399-3b701300-7350-11ea-9012-a7420c0a689c.PNG)

**Comment by dimitar-pechev** [comment]
@vickyadi3 As explained above, this behavior is by design. You can implement a custom directive that sets the checked state of a node and its children regardless of the expanded state of the node.

If you need further assistance on the topic, open a support ticket. This repository is for bug reports.

**Comment by markzolotoy** [comment]
Never seen a control working like this. What a .....

**Comment by cdtapay** [comment]
After opening a support ticket, only got a suggestion to get the children's keys from the data. 
So I ended up writing this. Hope it helps:

```
    // TDataItem is a generic TS type
    // type TreeViewResponse = (number | string)[];

    this.checkByField = 'id';
    this.childrenField = 'items';
    this.data = [{ id: 1, items [ { id: '1-1' }] }, { id: 'b', items: [ { id: 'b-1'}, { id: 'b-2'} ] },  { id: 3, items: [ { id: '3-a' } ] }];

    const checkedParentNodeKeys = [ 1, 'b' ];
    const childrenKeys = this.getChildrenKeys(this.data, checkedParentNodeKeys);

    private getChildrenKeys(allItems: TDataItem[], nodeKeys: TreeViewResponse): TreeViewResponse {
        const parentNodes = this.getParentNodes(allItems, nodeKeys);

        return parentNodes.reduce((acum: TreeViewResponse, item: TDataItem[]) => {
            const childrenKeys = this.setAllIndexesRecursively(item);
            return [...acum, ...childrenKeys];
        }, []);
    }

    private getParentNodes(items: TDataItem[], nodeKeys: TreeViewResponse): TDataItem[][] {
        return items.reduce((acum: TreeViewResponse, item: TDataItem) => {
            let nodes = [];

            if (item[this.childrenField]) {
                if (nodeKeys.includes(item[this.checkByField])) {
                    nodes = [item[this.childrenField]];
                } else {
                    nodes = this.getParentNodes(item[this.childrenField], nodeKeys);
                }
            }

            return [...acum, ...nodes];
        }, []);
    }

    private setAllIndexesRecursively(items: TDataItem[]): TreeViewResponse {
        return items.reduce((acum: TDataItem[], item: TDataItem) => {
            const childrenItems = item[this.childrenField]
                ? this.setAllIndexesRecursively(item[this.childrenField])
                : [];

            return [...acum, item[this.checkByField], ...childrenItems];
        }, []);
    }
```
