### ISSUE TITLE
DatePicker: Wrong timezones

### ISSUE THREAD

**Issue by EricSch** [telerik/kendo-angular#1648]
## I'm submitting a...
* Bug report 

## Current behavior
The picked dates having different and wrong time zones. I'm aware that it is a "Date" picker, but the type 'Date' has a time part, so it is revelant also.

## Expected behavior
Both dates having the correct time Zone ((UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna)

## Minimal reproduction of the problem with instructions
Using a datepicker sample from your site, adding a second date picker and changing culture to 'de-CH':
https://plnkr.co/edit/XvdyXftTyUnyLGrHD0ov?p=preview

Change first date, then change second date.
The dates having different time zones.

**Comment by ggkrustev** [comment]
Hi @EricSch,

The [JavaScript Date object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date), by specification, always uses the browser local timezone. This cannot be changed or altered by any means. More details about the possible timezone support that Kendo UI for Angular provides (not built-in the DatePicker) is to offset the date by some time. Note that the timezone won't be changed, as it is not possible by spec.

https://www.telerik.com/kendo-angular-ui-develop/components/datemath/timezones/

With that in mind, the date created by the DatePicker is also in the browser local timezone (as it is a native JavaScript Date instance) and it inherits all specifics of the browser timezone.

My assumption for the observed difference is a possible DST change, which happens in March.

https://www.timeanddate.com/time/change/netherlands/amsterdam?year=2000

I am afraid that the only issue that is available in this case is to notify the users that they operate in their local timezone although a different one is specified. This is mainly due to the DST changes which cannot be controlled.

I will close the thread as it doesn't report a bug report.

**Comment by EricSch** [comment]
Oh. seems you're right. I failed into the DST trap. Sorry for that.
