### ISSUE TITLE
How do i implement context menu for treeview

### ISSUE THREAD

**Issue by afsalcodehack** [telerik/kendo-angular#1661]

**Comment by ggkrustev** [comment]
Hello @afsalcodehack,

You can wire the click event of the TreeView host element and extract the LI hierarchical index in order to find the corresponding data item. Another option is to render a custom Item template and wire its click event. Thus, you can pass the corresponding data item to the click handler easier.
Once the tree data item is available, you can use it to modify the content of the Context menu and display it. For the context menu, you will need to combine Popup and Menu components. The former will position next to the clicked item and the Menu component will render the menu items/actions.

If you need further assistance, please open support ticket in Progress account. Thus the most appropriate support officer will handle the case and will provide more details about the desired functionality.

I will close this thread as the Github issues are used only for bug reports and enhancement requests. All other questions need to be handled either with support ticket or by the community in StackOverflow.
