### ISSUE TITLE
DropDownList with filtering does not allow tabbing to the next input

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1686]
When the filtering is enabled in the DropDownList, the user cannot tab to the next focusable element:

[https://plnkr.co/edit/XEqAnR6veaHWe7ETE2et?p=preview](https://plnkr.co/edit/XEqAnR6veaHWe7ETE2et?p=preview)

The issue is not present when "filterable" is not set or is set to **_false_**.

Seems related to [https://github.com/telerik/kendo-angular/issues/1008](https://github.com/telerik/kendo-angular/issues/1008)

**Comment by dimitar-pechev** [comment]
@scacchif The fix for the issue is available in the [development channel](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the `@progress/kendo-angular-dropdowns` package v3.2.1-dev.201810291301. Within a few weeks it should be available in the official release.

**Comment by dimitar-pechev** [comment]
The fix is included in v3.3.0 of the `@progress/kendo-angular-dropdowns` package.
