### ISSUE TITLE
DropDownButton Renders Multiline when 

### ISSUE THREAD

**Issue by joefosterx** [telerik/kendo-angular#1706]
## I'm submitting a bug
* Bug report

## Current behavior
When the DropDownButton is on the right edge of a window, the drop-down behavior for longer items goes to multi-line rendering.  Buttons on the left edge expand fine and render on one line.

## Expected behavior
The drop down items would render in the same way (one line) as they would if it was anchored on the left edge.

## Minimal reproduction of the problem with instructions
Using the DropDownButton demo as the basis, I added a second <kendo-drop-down-button>, lengthened one of the drop-down options, and made the preview window small enough so that the buttons were side by side, but not yet on top of each other.
Plunker: https://plnkr.co/edit/OWaNH8kB6QTzxuHVtHbl?p=preview
Clicking on the first button shows each item rendered on one line,
Clicking on the second button shows the long item split into two lines.

```

Browser:

- Chrome (desktop) version  67.0.3396.99
- Firefox version 61.01

**Comment by gyoshev** [comment]
Both wrapping lines and non-wrapping lines are a viable option, as wrapping lines allow users to read the complete item text, without hiding it or relying on scrolling. You can achieve the described behavior by setting the `white-space` CSS property of the items ([demo](https://plnkr.co/edit/OWaNH8kB6QTzxuHVtHbl?p=preview)):

```css
.k-list > .k-item {
    white-space: nowrap;
}
```

This functionality can be provided through a theme variable in a future version of the framework, if there is enough interest. Feel free to [suggest this on UserVoice](http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback) so that it is evaluated when planning new releases.
