### ISSUE TITLE
Tooltip: position by pixel

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#1731]
is it possible to define tooltip position by X,Y values?
I see just component anchors. Am i right?

Thanks.

**Comment by elena-gancheva** [comment]
Hi @meriturva, thanks for submitting this.

Currently the Tooltip does not support this functionality. The Tooltip requires an `anchor` element in order to position in accordance to it. Could you please provide some more information about how do you want to use the extended positioning? Would it be valuable for your case if the [`show` ](https://www.telerik.com/kendo-angular-ui-develop/components/tooltip/api/TooltipDirective/#toc-show ) method accepts `anchor` element **or** object with `{X, Y}` values?

**Comment by meriturva** [comment]
Hi @elena-gancheva and thanks for your question.

I have canvas (fabricjs) and i just would like to show a tooltip on it. The only way is to address tooltip location is by x,y values. I just would like to use kendo tooltip solution because we have already used on other components of same application (already styled) and because we have few commercial licenses (so support for us is really important)

Another aspect is about "moving" tooltip. We have to update tooltip value related to pixel value of canvas. So when user just moves mouse we have: move tooltip, update tooltip content.

Actual solution is just based on old javascript vanilla way.

Thanks.

**Comment by elena-gancheva** [comment]
Hi @meriturva, thanks for the further details.

We can extend the Tooltip's show method to allow positioning by `X,Y` values. Once ready, I will update this issue.

To create a moving Tooltip, it seems that having a `TooltipService` that returns a TooltipRef fits the use-case. What do you think about that? If this sounds reasonable, please submit this as a feature request in our [UserVoice portal](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback/filters/top), so that we can scope and plan this for the next release.

Thanks.

**Comment by meriturva** [comment]
Thanks.
Done:

http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback/suggestions/35121778-tooltipservice

**Comment by Graphictank** [comment]
This may be a bit off since my issue was to hover & left justify a tooltip directly over the top of my text. The "position" of top, right, bottom, left just wasn't cutting it for my UX Architect. Unfortunately I had to specify the .k-animation-container in my components scss with transform: translate(100%,0);  as well as assigning the position="left" in the kendoTooltip span.

My co-worker did have some success with the offset attribute but that only works for Y, not X. The transform may bring you some success if you fiddle around. Setting where the filter attribute spawns should help as well.

Hope this helps someone.

**Comment by svetq** [comment]
also requested in 1454346

**Comment by Raisolution** [comment]
Along the request about a Tooltip service, we have transferred the other feature request from this issue to the feedback portal, namely - the positioning of Tooltips by pixel:

https://feedback.telerik.com/kendo-angular-ui/1543776-tooltip-position-by-pixel

Please cast your votes there. This will allow us to measure the customer demand for the feature, and plan it accordingly for future product releases.

I am closing this issue for the time being, as it is not used for development tracking.
