### ISSUE TITLE
Gantt chart?

### ISSUE THREAD

**Issue by pat-son** [telerik/kendo-angular#1740]
## I'm submitting a...
* Documentation issue

The changelogs mention a [Gantt chart](https://en.wikipedia.org/wiki/Gantt_chart) in a [few places](https://www.telerik.com/kendo-angular-ui/search/?q=gantt), but I can find any information anywhere else in the documentation. Is there a Gantt chart component for Kendo UI for Angular?

**Comment by gyoshev** [comment]
@pat-son At the time of writing, the Gantt component is not part of Kendo UI for Angular and is not on our short-term roadmap.  The mentions of the component in the changelogs are because the theme packages support all flavors of Kendo UI (jQuery, Angular, React, Vue), and the component is available in Kendo UI for jQuery.

As an immediate solution, [use the jQuery Gantt component in an Angular application](https://www.telerik.com/kendo-angular-ui-develop/components/framework/kendo-jquery/). The linked article provides a general approach for all missing components in the Angular packages.
To influence our planning for future releases, and get a natively Angular component, [vote for the Gantt chart on UserVoice](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback/suggestions/16637128-gantt-chart-component).
