### ISSUE TITLE
Grid sort indicator not visible in scrollable mode

### ISSUE THREAD

**Issue by l3cram** [telerik/kendo-angular#1742]
## I'm submitting a...

* Bug report 

## Current behavior
When scrollable in a kendo grid is set to null, the column width resizes automatically to the content width. But when scrollable is set to true, the width doesn´t change and the current sort state isn´t visible in the header. 
## Expected behavior

The columns width should automatically resize and the sort state should be visible in the header.
## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-wsvvfu

## Environment
Browser:

- Chrome (desktop) version XX
- Firefox version XX
- Edge version XX

**Comment by gyoshev** [comment]
Hello @l3cram, and thanks for the feedback.

We are aware of this Grid limitation, and we track it in https://github.com/telerik/kendo-theme-default/issues/708. Since this requires a change to the Grid header rendering, it may take some time until it is implemented. There is a provided workaround in the linked thread that you can use today.
