### ISSUE TITLE
Add a file name template for the Upload

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular#1758]
## I'm submitting a...
* Suggestion for improvement  

## Current behavior
The [kendoUploadFileTemplate](https://www.telerik.com/kendo-angular-ui/components/upload/templates/) overrides built-in elements like progress bar, file icon, validation messages and action. For many scenarios this is too coarse, making minor additions like a button next to the file name very hard to implement.

## Expected behavior
The Upload should support a template for the file name only (.k-file-name), e.g. kendoUploadFileNameTemplate that keeps all built-in functionality.

![image](https://user-images.githubusercontent.com/247917/44642207-dade5e80-a9d3-11e8-93a1-63df9b13e22b.png)

**Comment by stevenholder** [comment]
I'm commenting on this as I agree there is not fine-grained enough control over what is displayed by the upload widget. 

For example, I would like to be able to display server-side errors at a file-level by manipulating the validationErrors collection. This would provide a consistent development experience between the client-side FileRestrictions and server-side error message handling and a consistent user-experience because any file error/validation failure would be displayed in an expected space. 

Having to re-implement the entire kendo-upload-file-list-single-item just to enhance the error handling to be consistent makes the widget much less useful as we lose all the work that makes the widget nice!

**Comment by mikef907** [comment]
Hello,

I am commenting here to encourage this feature development.  I have found that the upload is templating is "all-or-nothing" which typical use case for it has been a little frustrating.  For my users, they expect that they will be able to download a file that has been uploaded, using this component is a convenient way to manage files, however, trying to add a simple download link essentially has lead me down the path of rolling my own template.  This is a shame since the built in template actually looks really nice and has some good looking visual effects that I'd like to keep whilst also allowing users to simply download a file by clicking on the file name.

**Comment by preslavapetrova1** [comment]
Released in `v7.1.0` of the `kendo-angular-upload` package
