### ISSUE TITLE
Floating label for drop downs

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#1778]
## I'm submitting a...
* Bug report
* Documentation issue

## Current behavior
Floating label doesn't work.

## Expected behavior
It does work.

## Minimal reproduction of the problem with instructions
I read [here](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback/suggestions/33345202-hi-i-need-a-float-label-angular-component-for-the) that you completed floating labels for drop downs.

Unfortunately example [here](https://www.telerik.com/kendo-angular-ui/components/inputs/textbox/#toc-implementing-floating-labels) doesn't show how to do that for drop downs.

I tried, if floating labels really work with dropdowns but it seems it doesn't.
![chrome_2018-09-08_09-18-49](https://user-images.githubusercontent.com/1589573/45251542-36034000-b348-11e8-81b8-8a9c938739eb.png)

[Plunkr](https://stackblitz.com/edit/angular-uum6vx?file=app/app.component.ts).

**Comment by danielkaradachki** [comment]
The [textboxcontainer](https://www.telerik.com/kendo-angular-ui/components/inputs/api/TextBoxContainerComponent/#toc-textboxcontainercomponent) requires the components to use Template or Reactive Forms in order to work correctly.

https://stackblitz.com/edit/angular-uum6vx-x315ff?file=app/app.component.ts

**Comment by MaklaCof** [comment]
Nice.
