### ISSUE TITLE
The maximized window component does not completely cover the browser window.

### ISSUE THREAD

**Issue by GavinEnjoy2017** [telerik/kendo-angular#1801]
## I'm submitting a...

* Regression report 
* Bug report 
* Suggestion for improvement  
* Documentation issue 

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by dtopalov** [comment]
As we do not believe it would be correct to restrict the end user dragging behavior and alter the resulting expected browser behavior in such cases, we will consider providing a fix for the second part of the issue only.

**Comment by Raisolution** [comment]
We inspected the issue further. Implementing this out of the box would require the Window component to intervene with the `overflow` CSS of the body element in order to remove the scrollbar while it is maximized. As this is something we generally tend to avoid, we decided to not provide the requested functionality out of the box.

As a workaround, one could use the Window component event handlers to manually manipulate the scrollbar of the body as needed. Here is an example that demonstrates the workaround in action, which we will also provide as a Knowledge Base article on our documentation - https://stackblitz.com/edit/angular-azpjet-bv8dhz
