### ISSUE TITLE
Splitter broken in IE9

### ISSUE THREAD

**Issue by bernatgy** [telerik/kendo-angular#1823]
## I'm submitting a...

* Bug report 

## Current behavior

The Splitter component is completely broken in Internet Explorer 9. 
In **Google Chrome**:
[![image.png](https://i.postimg.cc/d3CLv8h7/image.png)](https://postimg.cc/1V99rVcP)
In **Internet Explorer 9**:
[![image.png](https://i.postimg.cc/qBNmyzfz/image.png)](https://postimg.cc/Z0hFhY5S)

## Expected behavior

I expect the splitter not to break the UI and to be able to resize the panes.

## Minimal reproduction of the problem with instructions

Create any project with Kendo UI and add a splitter anywhere on the page.

## Environment

Package versions:

```
"@angular/*": "4.4.x"
"@progress/kendo-angular-l10n": "^1.2.1",
"@progress/kendo-angular-layout": "^3.1.3",
"@progress/kendo-angular-treeview": "^2.3.1",
"@progress/kendo-theme-default": "^2.56.0",
```

Browser:

- Chrome (desktop) version 69.0.3497.100 (Official Build) (64-bit)
- IE version 9

System:
- TypeScript version: 2.3.x
- Node version: 6.11.4, NPM: 3.10.10
- Platform: Chrome: Windows 10, IE9: Windows 7 Pro, SP1

There's no output in console, all Angular polyfills are enabled, and the [Kendo UI Browser Compatibility](https://www.telerik.com/kendo-angular-ui/components/styling/ie9-support/) guide has been followed.

Please respond quickly, we're working in an Enterprise environment with heavy deadlines.
I can help with any questions you've got.

Similar issue: #1408

**Comment by gyoshev** [comment]
@bernatgy I am afraid that the Splitter component depends on the Flexbox CSS module to function correctly, and that module is not available in IE9. The Browser Compatibility guide does not explicitly state this about the component, which is an important point and will be added shortly. I am afraid that we cannot provide this missing functionality for the Angular component in a timely manner, since this requires a significant development effort and is not in our short-term plans.

As a workaround for this, consider using the jQuery Splitter component, like shown in the [Integration with Kendo UI for jQuery guide](https://www.telerik.com/kendo-angular-ui/components/framework/kendo-jquery/). In case you need assistance with the implementation, please open a support ticket.

**Comment by gyoshev** [comment]
Documentation has been updated in this regard.
