### ISSUE TITLE
MultiSelect - selecting item when pressing 'enter' with filterable and custom elements

### ISSUE THREAD

**Issue by jornare** [telerik/kendo-angular#1834]
## I'm submitting a...
* Bug report 

## Current behavior
Using Multiselect with allowCustom and filterable set to "true", pressing enter after typing a filter will clear the filter without adding an item (neither from the suggestions or custom)

## Expected behavior
If there is a suggestion match, the suggestion should be added otherwise a new custom item.

## Minimal reproduction of the problem with instructions
https://angular-it51xd.stackblitz.io/

## Environment
See Stackblitz

Browser:
- Chrome (desktop) version 69

System:
See Stackblitz

**Comment by valchev** [comment]
@jornare thank you for bringing this to our attention. I will investigate the case further and address it as soon as possible.

**Comment by dimitar-pechev** [comment]
@jornare Your expectations for how the MultiSelect should work are quite correct. For the most part, however, what you are describing as an issue and what is seen in your example is a result actually of incorrect component configuration. 

When enabling the `filterable` and `allowCustom`, the focus on user input moves to the first match in the filtered list as you can see in [this example](https://stackblitz.com/edit/angular-ahsyvm).

The reason why it's not working in your example is that no actual filtering is performed. When you set `filterable` to true, you also have to handle the `filterChange` event. If no filtering is performed the focus is not correctly set. This is just the way the component works. You can refer to [this article](https://www.telerik.com/kendo-angular-ui/components/dropdowns/multiselect/filtering/) in the docs related to filtering for a detailed example.

We noticed, however, that the custom item was not focused when there were no matches in the suggestions list. Thank you for pointing our attention in this direction. 

The fix for that was just released a few days ago and is available in the kendo-angular-dropdowns package v.3.2.0.

**Comment by jornare** [comment]
Thank you. We will try the update in our next iteration, and hopefully we'll get it to work as wanted.
