### ISSUE TITLE
Resizable property on Window has no effect

### ISSUE THREAD

**Issue by clintsinger** [telerik/kendo-angular#1871]
## I'm submitting a...

* Bug report 

## Current behavior

The `resizable` property of the `kendo-window` class doesn't appear to have any effect.  I tried it in my own project and tried it in the demo (https://www.telerik.com/kendo-angular-ui/components/dialogs/window/dimensions-resizing/) and the behavior is the same.  The actions for resizing the window stay the same regardless of how the property is set.

## Expected behavior

I would expect when set to `false` that the minimize and maximize would disappear and I am unable to resize the window.

## Minimal reproduction of the problem with instructions

See your own demo at https://www.telerik.com/kendo-angular-ui/components/dialogs/window/dimensions-resizing/ and click on the "Enable/Disable resizing".  Observe that the text in the dialog changes but the buttons and the resizing behavior doesn't.

## Environment
Browser:

- Edge version 44.18262.1000.0

System:
- Platform:  Windows

**Comment by Raisolution** [comment]
Hi @clintsinger,

The current behavior is by design. Setting the `resizable` option to `false` prevents the Window to be resized using the handles on it's edges and corners. It does not change the visibility of the minimize and maximize buttons. In order to show them conditionally, you could [specify custom titlebar](https://www.telerik.com/kendo-angular-ui/components/dialogs/window/action-buttons/), list the action buttons and manage their visibility depending on the resizable value.
