### ISSUE TITLE
kendo comobox  required field not showing border color red default after page load   

### ISSUE THREAD

**Issue by vinodn4** [telerik/kendo-angular#1874]
but is sowing read border after touching 

need emergency fix

**Comment by dimitar-pechev** [comment]
@vinodn4 By design, the error styles of a ComboBox inside an `NgForm` are applied when the value of the control is invalid and the control is touched or dirty. That is indeed the intended behavior. 

When you come across an issue with a component, you should provide a runnable example as we can do little without a code sample or at least a detailed description of the problem.

If you need help with the usage of the component, you should [submit a support ticket](https://www.telerik.com/account/support-tickets).

If I've misunderstood the problem and there is an issue with the component, please provide more details on the observed unexpected behavior. We'll reopen the issue and take it from threre.

**Comment by IT-CASADO** [comment]
This week I encountered the same issue.

I think the issue is, that Telerik changed the behavior in the newest bootstrap theme.
I'm currently using version 2.13.6 and see the same issue as vinodn4.

[Demo with version 2.13.6](https://stackblitz.com/edit/angular-kendo-bootstrap-validation-old?embed=1&file=app/app.component.ts)

But in latest version you see the red border not on initial load:

[Demo with newer version](https://stackblitz.com/edit/angular-kendo-bootstrap-validation)

Unfortunately the older version is what I'm want...

What is now the best solution to highlight all invalid controls on initial load?

**Comment by vinodn4** [comment]
hi @dimitar-pechev and @IT-CASADO  

the below link the name will load with red border but not age 
https://stackblitz.com/edit/angular-kendo-bootstrap-validation-old?embed=1&file=app/app.component.ts
but i need age should load with read border.

**Comment by dimitar-pechev** [comment]
@vinodn4 @IT-CASADO Thank you for the code samples.

The inputs are supposed to indicate errors only after the user has touched them and they remain invalid, as the [basic guidelines](https://angular.io/guide/form-validation#why-check-dirty-and-touched) of Angular suggest. So the newer version of the theme holds the correct behavior.

You can, however, easily change it if you need to always indicate invalid input even if the user has not yet started editing the form content (e.g. on page load). Here are two possible options depending on your needs:
  * [override the css theme](https://stackblitz.com/edit/angular-kendo-bootstrap-validation-wxxkyr)
  * [programmatically `touch` all form controls after component view init to trigger error indication](https://stackblitz.com/edit/angular-kendo-bootstrap-validation-wkjdyz) - more on the topic of using this approach of marking the controls as `touched` to trigger error indication [here](https://github.com/angular/angular/issues/19400)

**Comment by IT-CASADO** [comment]
I think it would be really nice if we can control this in themes by a variable.
