### ISSUE TITLE
In IE scrolling is applied to the parent element instead of only to the PopUp element

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1882]
## I'm submitting a...
* Bug report 

## Current behavior

In IE, when we have a scrollable content inside a PopUp and we scroll to the bottom of the content, then the scroll is applied to the parent element. 

## Expected behavior
Scrolling should be limitted to the content of the PopUp when scrolling inside the content.

## Minimal reproduction of the problem with instructions
Check the following example in IE 11:

[https://stackblitz.com/edit/angular-fdcbe4?file=app/app.component.ts](https://stackblitz.com/edit/angular-fdcbe4?file=app/app.component.ts)

and the following video demonstrating the undesired behavior:
[https://www.screencast.com/t/aeTfPa31OIY](https://www.screencast.com/t/aeTfPa31OIY)

**Comment by danielkaradachki** [comment]
The behavior is not related to the popup. The same behavior can be reproduced with the content rendered outside of the component:
https://stackblitz.com/edit/angular-fdcbe4-29ybqa?file=app/app.component.ts

If required, the scroll event can be prevented once the scroll reaches the bottom in order to avoid this.
