### ISSUE TITLE
DropdownList incorrectly changing value onBlur when using new FilterDirective

### ISSUE THREAD

**Issue by VishalMadhvani** [telerik/kendo-angular#1885]
## I'm submitting a...

* Bug report 

## Current behavior

After filtering and selecting a value other then the first, clicking away from the dropdown list will cause a valueChange to be emited with the first value. The dropdown still shows the selected value, and hence there value shown, and then actual value are different.

## Expected behavior

valueChange with incorrect value should not be fired.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-znivsa
![2018-10-31_16-27-27](https://user-images.githubusercontent.com/1994627/47804029-b5e7ce00-dd2b-11e8-9736-1a8f168a385d.gif)

## Environment

Browser:

- Chrome (desktop) version 69

**Comment by VishalMadhvani** [comment]
Any updates on this? As currently the DropdownFilter Directive is unusable...

**Comment by dimitar-pechev** [comment]
@VishalMadhvani Thanks for bringing the issue to our attention and sorry for the delayed response!

The fix for the issue introduced in the [**dev build**](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the `@progress/kendo-angular-dropdowns` package **v3.4.0-dev.201811190903**. After some further testing it will be included in the official release.

**Comment by dimitar-pechev** [comment]
Shipped in **v3.4.0** of the `@progress/kendo-angular-dropdowns` package.
