### ISSUE TITLE
Kendo Grid "[navigable]='true'" attribute does not work in Microsoft Edge

### ISSUE THREAD

**Issue by cor2879** [telerik/kendo-angular#1895]
## I'm submitting a...

Support request

* Regression report 
* Bug report 
* Suggestion for improvement  
* Documentation issue 

Bug Report

## Current behavior

Kendo Grid is not navigable via keyboard (as described here https://telerik.com/kendo-angular-ui/components/grid/keyboard-navigation/#toc-keyboard-navigation) in Microsoft Edge when the [navigable]="true" attribute is set.

## Expected behavior

The grid should be navigable via keyboard as described.  This works in Chrome but not in Edge.

## Minimal reproduction of the problem with instructions

It's actually quite easy to reproduce.  Just load up a UI that uses KendoGrid.  Make sure the [navigable] attribute is set to 'true' and populate the grid with any data.  Then attempt to navigate it via keyboard.  It works in Chrome but does not work in Edge.

## Environment

Package versions:

```
Kendo-angular-buttons@4.1.3
kendo-angular-dateinput@3.4.2
kendo-angular-dropdowns@3.0.2
kendo-angular-excel-export@2.1.1
kendo-angular-grid@3.51
kendo-angular-inputs@2.2.0
kendo-angular-intl@1.4.1
kendo-angular-l10n@1.2.0
kendo-angular-upload@3.0.3
kendo-data-query@1.4.0
kendo-drawing@1.5.6
kendo-theme-bootstrap@2.13.6
```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

Chrome desktop version 70.03538.77
Edge version 44.17763.1.0

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:  

Node version v8.12.0
Windows 10

**Comment by tsvetomir** [comment]
@cor2879 this particular version of Edge seems to be included in the [Windows 1809](https://en.wikipedia.org/wiki/Windows_10_version_history#Version_1809_(October_2018_Update)) update. This update is no longer available due to [data loss issues](https://blogs.windows.com/windowsexperience/2018/10/09/updated-version-of-windows-10-october-2018-update-released-to-windows-insiders/).

I'd appreciate it if you could point us to a VM image that we can use for testing. Otherwise we'll have to wait for a fixed version to be released.

**Comment by cor2879** [comment]
Thanks for the response.  I'll see if we can set up a VM for that.  I
suspect though that it won't be approved.

**Comment by tsvetomir** [comment]
I'll check if we can get the fixed update through Insiders, thanks!

**Comment by LanceMcCarthy** [comment]
@cor2879 Hi David, my name is Lance McCarthy and I'm a Senior Support Engineer at Progress (Telerik/Kendo). I'm also a Microsoft MVP ([verify here](http://mvp.microsoft.com/en-us/mvp/Lance%20McCarthy-5000553)) and have access to 1809 to test this.

I'm using:
- Microsoft Edge 44.17763.1.0
- Microsoft EdgeHTML 18.17763

I loaded [the Kendo Grid Keyboard Navigation demo](https://www.telerik.com/kendo-angular-ui/components/grid/keyboard-navigation/#preview-0) but wasn't able to notice any problems moving around the Grid using keyboard arrow keys there. 

Just to make sure it wasn't a demo site environmental condition, I ran the code in a standalone StackBlitz, but the issue did not present there either. Here is a very short video (8s) of me tabbing in from the address bar and moving through the Grid using keyboard arrow keys: [https://www.screencast.com/t/wyknxR7Ns1q](https://www.screencast.com/t/wyknxR7Ns1q)


Did I miss any other steps? I will be creating a VM (with our enterprise keys) for @tsvetomir to keep testing this.

**Comment by LanceMcCarthy** [comment]
Angular is outside my area of expertise, I had access to the 1809 environment so I helped out with testing the initial report :) I will need to defer to Tsvetomir for further investigation.  Since he's located in the UTC+2 timezone (Sofia, BG), he might not be able to respond until the morning. 

In any case, I have completed building a VM for him to test on. If there is anything else you can share here, please do so that he has all the info to get started.

If you're not able to share the code publicly, [open a Support Ticket here](https://www.telerik.com/account/support-tickets/contact-support-team) and attach/paste the code, private Support Tickets carry our support agreement's NDA. Then come back here and share the ticket number with us.

**Comment by cor2879** [comment]
Sounds good.  Thank you, Lance!

**Comment by tsvetomir** [comment]
My tests with the [KB Navigation demo](https://www.telerik.com/kendo-angular-ui/components/grid/keyboard-navigation/#preview-0) did not reveal any issues either. Edge version used:

![image](https://user-images.githubusercontent.com/247917/48262865-b6b7e880-e42c-11e8-8982-1fccb689f393.png)


 I would also recommend opening a support ticket, especially if you can share a project that can be used to replicate the issue.

**Comment by cor2879** [comment]
Thank you Tsvetomir, I will look into opening a support ticket.
