### ISSUE TITLE
Tabstrip, when selected tab hidden by code the tabstrip has no selected tab

### ISSUE THREAD

**Issue by Abdullah0991** [telerik/kendo-angular#1938]
## I'm submitting a...
* Suggestion for improvement.

## Current behavior
My application has a tab-strip with two tabs, and a third tab shown only when a condition is true.
When the condition is set to false and the third tab is selected, the tab-strip is shown with no selected tab.

## Expected behavior
Like these scenarios the tab-strip have to select the first tab automatically.

## Minimal reproduction of the problem with instructions
[demo](https://stackblitz.com/edit/angular-pejuxf?file=app/app.component.ts)

## Environment

Browser:
- Chrome (desktop) version 70.0.3
- Firefox version 63.0.3

System:
- TypeScript version: 2.6.2
- Node version: 8.11.3
- Platform:  Windows 10

**Comment by danielkaradachki** [comment]
The tabstrip does not and should not select any tab automatically by design. In the provided example the first tab is selected initially because of the `selected` input. You can use the [selectTab](https://www.telerik.com/kendo-angular-ui/components/layout/api/TabStripComponent/#toc-selecttab) method or bind a property to the [selected](https://www.telerik.com/kendo-angular-ui/components/layout/api/TabStripTabComponent/#toc-selected) input in order to change the selection when removing an item.
