### ISSUE TITLE
Mobile keyboards with auto-suggest produce unexpected behavior

### ISSUE THREAD

**Issue by tapopov** [telerik/kendo-angular#1958]
## I'm submitting a...

* Bug report 

## Overview
Mobile devices with keyboards that have autocomplete/suggest feature enabled produce composition input events when user is typing. It seems that mobile browsers ignore the attributes which should disable those keyboard features (see [here](https://bugs.chromium.org/p/chromium/issues/detail?id=303883)), meaning we have no control over it. On the other hand, composition events are handled differently in order to support multibyte characters, such as Tradition and Simplified Chinese, which in turn creates the unwanted behavior when working on mobile device with auto-suggesting keyboard.  
 
## Current behavior
For example user start typing, however matching item is highlighted only after the word is completed or selected from the keyboard's suggestions bar. 

## Expected behavior

Selecting matches or emitting filter events should happen on every keystroke.

## Environment
Browser:
- Chrome (Android) 
- Firefox (Android)
- Possibly others

**Comment by dimitar-pechev** [comment]
Fixed in the [dev channel](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of `@progress/kendo-angular-dropdowns` **v3.5.2-dev.201903141745**.  Filtering, popup opening, searching and other functionalities related to the user input should now all work as expected with auto-correction and/or suggestions enabled on an android device.

**Comment by tsvetomir** [comment]
Shipped in v3.5.2
