### ISSUE TITLE
Kendo Dropdown sorting is not working properly

### ISSUE THREAD

**Issue by vkumar279** [telerik/kendo-angular#1961]
## I'm submitting a...

* Regression report 
* Bug report 
* Suggestion for improvement  
* Documentation issue 

## Current behavior
 "Bredgade","Bredmosevej", "Brednsvej", "Bredfaj"
If i press Bred on ddl the it sort by Bred and focus on the "Bredmosevej" option which is wrong.
It should focus on the "Bredgade" option because after Bred string, the order of sorting is alphabetical which is Bredgade then Bredmosevej.
-->

## Expected behavior

Press Bred then focus should be on "Bredgade" option rather then "Bredmosevej".

Browser:

- Chrome (desktop) version 70.0.3538.102 

System:
- Platform:

**Comment by vkumar279** [comment]
any update on this..

**Comment by dimitar-pechev** [comment]
@vkumar279 I can confirm it's an issue on our side. We will provide a fix as soon as possible.

**Comment by vkumar279** [comment]
@dimitar-pechev : Please provide us a custom fix so that we can fix this issue on our end and deliver our system to client. We have licence.

**Comment by vkumar279** [comment]
any update ..?

**Comment by dimitar-pechev** [comment]
@vkumar279 The fix is included in the latest development build of the `@progress/kendo-angular-dropdowns` package **v3.4.1-dev.201812070843**. 

If it's urgent for you, you can use it even now in your project as demonstrated in [this example](https://stackblitz.com/edit/angular-s3nsyh-bpnp3r) which uses the dev version of the package as you can see in the `package.json` file. After some additional tests are run, the package will be added to the official release which ususally happens within a few weeks of the dev release.

**Comment by vkumar279** [comment]
Where i need to update this version into my AngularJs Project b/c you mention this into angular2 project.

**Comment by dimitar-pechev** [comment]
The fix is shipped in **v3.4.1** of the `@progress/kendo-angular-dropdowns` package.
