### ISSUE TITLE
SplitterPane: Scrollbar not working when using flexbox

### ISSUE THREAD

**Issue by MarkusSchneider** [telerik/kendo-angular#1983]
## I'm submitting a...
* Bug report 

## Current behavior

When I use flexbox and an horizontal aligned splitter, the scroll bar of the splitter pane is not working when the content overflows the visible area. The whole page is scrolling an not only the splitter pane.

## Expected behavior

Only the splitter pane with overflowing content should scroll.

## Steps to reproduce
1) Run stackblitz example: https://stackblitz.com/edit/kendo-angular-splitter-scroll-demo
-> The complete site is scrolling
2) If the hight is defined of the splitter pane -> modify details.component.css, the scroll bar is working

## Environment
Browser:

- Chrome (desktop) version 70.0.3538.110 (Offizieller Build) (64-Bit)

**Comment by gyoshev** [comment]
The splitter expands to the size of its content by design. If the desired application layout is to have a splitter with 100% height, this is achieved by styling the splitter container. One way to achieve this in this particular example is to set `style="height: 100vh"` on the splitter; the approach may vary from application to application.
