### ISSUE TITLE
[DatePicker: regression] Popup does not open within a Bootstrap modal

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1984]
Since version 3.5.2 of the DateInputs package the DatePicker does not open when placed within a Bootstrap modal:

[https://stackblitz.com/edit/angular-iuy2g2](https://stackblitz.com/edit/angular-iuy2g2)

Works as expected with v. 3.5.1:

[https://stackblitz.com/edit/angular-iuy2g2-ixuvm9?file=app/app.component.ts](https://stackblitz.com/edit/angular-iuy2g2-ixuvm9?file=app/app.component.ts)

**Comment by danielkaradachki** [comment]
The bootstrap modal keeps the focus inside it. Because the datepicker popup is added by default outside of the element, the modal steals the focus and when the focus is lost the datepicker popup should be closed. The problem can be avoided by using the [popupSettings.appendTo](https://www.telerik.com/kendo-angular-ui/components/dateinputs/api/PopupSettings/#toc-appendto) option to render the popup inside the modal:

https://stackblitz.com/edit/angular-iuy2g2-corfxk?file=app/app.component.ts

**Comment by clabough** [comment]
Thanks for the fix. The only concern I have is that this changed between 3.5.1 and 3.5.2 - a patch version increment. To me - and my users - this was a breaking change.
