### ISSUE TITLE
Adding custom value in mulstiselect when [data] is Array<number>

### ISSUE THREAD

**Issue by destus90** [telerik/kendo-angular#2015]
## I'm submitting a...

* Bug report 

## Current behavior

If you have a multiselect with an allowCustom parameter is set to true and [data] is array of numbers you won't be able to add custom value

## Expected behavior

Custom value should be added in select
## Minimal reproduction of the problem with instructions

1. Open demo example https://stackblitz.com/edit/angular-5vgfdb-qwj3hz?file=app/app.component.ts
2. Type '-1' in input box and press Enter
3. See that custom value wasn't marked as selected

## Environment

Package versions:
```
v.3.4.2 of dropdowns
```

**Comment by dimitar-pechev** [comment]
Just want to make it clear that a `valueNormalizer` is always used. If you don't define the function yourself, the component uses its own default implementation. So it's not a case of defining **when** to use a `valueNormalizer`, it's a case of **what** `valueNormalizer` function to use for that purpose.

Having said that, it depends on what exactly you are trying to achieve. What do you mean that the array can sometimes be for numbers and on other occasions for strings? If you want to implement a reusable component that wraps the **MultiSelect** and only **initially** set either your custom `valueNormalizer` or use the default one, you can use a ternary operator like in [this example](https://stackblitz.com/edit/angular-5vgfdb-1uzhot).

If you want to change the data of the component at multiple times and respectively change the `valueNormalizer`, it is a bit trickier. Since the default function will be overridden the first time you assign your own function, the initial implementation will be lost. If that's the behavior you are after, then you will have to implement a `valueNormalizer` function that handles each of your use cases - if the array is with numbers - parse the user input to a number, and if it's a string - return the string.

I would encourage you to [submit a support ticket](https://www.telerik.com/account/support-tickets) if you need further assistance on this, as the **GitHub** repo is really not the place for discussing specific implementations. As already mentioned, it really depends on what exactly are you trying to achieve.

**Comment by destus90** [comment]
@dimitar-pechev ternary operator is what I wanted. I tried to resolve the issue in a similar way, but couldn't get ```valueNormalizer``` with a template reference variable. Thanks for help.

**Comment by dimitar-pechev** [comment]
Fixed in the latest [dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the **DropDowns** package (`@progress/kendo-angular-dropdowns@3.5.0-dev.201901311002`). 

Here's an [updated example](https://stackblitz.com/edit/angular-bo8jaq). As mentioned before, the default `valueNormalizer` creates the custom values as strings.

**Comment by dimitar-pechev** [comment]
Shipped with `@progress/kendo-angular-dropdowns@3.5.0`.
