### ISSUE TITLE
Switch animations not working with Angular 7.2

### ISSUE THREAD

**Issue by Rethic** [telerik/kendo-angular#2017]
## I'm submitting a...

* Bug report 

## Current behavior
Kendo Switch control slider does not appear or react correctly. The animated slider does not begin or stop at the proper location. Labels do not display at all.

## Expected behavior
Control animations should work as they do in the demo.

## Minimal reproduction of the problem with instructions
1. Visit: https://stackblitz.com/edit/angular-switch-test
2. Click the switches and watch the animations

## Environment

Package versions:
This is using:
- @progress/kendo-angular-inputs 3.5.0
- @progress/kendo-theme-bootstrap 3.0.0
- Angular 7.2

Browser:
- Chrome (desktop) version 71.0.3578.98
- Firefox version 64
- IE version 11

**Comment by tsvetomir** [comment]
This issue is a result of a breaking change in the latest version of the themes - see https://github.com/telerik/kendo-angular/issues/2018 for more details.

The solution is to either update the `@progress/kendo-angular-inputs` package to v4.0 or downgrade the theme to v2.x ([sample <img src="https://i.stack.imgur.com/3H2PQ.png" alt="opens in a new window">](https://stackblitz.com/edit/angular-switch-test-tx8b4a?file=index.html)). Apologies for the caused inconvenience.

**Comment by Rethic** [comment]
I just loaded version 4.0.0 and it is looking great.
Thank you!
