### ISSUE TITLE
Multiselect includes empty tag on keyboard combination

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#2062]
## I'm submitting a...

* Bug report 

## Current behavior
Multiselect includes empty tag 

## Expected behavior
It should not include empty tag.

## Minimal reproduction of the problem with instructions
1. Open [this sample](https://stackblitz.com/edit/angular-zpis3k?file=app/app.component.ts).
2. Focus input and close popup ( press BACKSPACE ) 
3. Press SPACE and ARROW_UP(twice) , hit ENTER.

## Environment

Package versions:

```
broken in v3.5.0-dev.201901311605
```

Browser:

N/a
System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by dimitar-pechev** [comment]
The fix is available in the [dev channel](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of `@progress/kendo-angular-dropdowns` **v3.5.0-dev.201902151002**.

When there's no focused item, the first one is focused on up arrow press to make it consistent with the navigation behavior of the rest of the **DropDowns**.

**Comment by dimitar-pechev** [comment]
Included in **v3.5.0**.
