### ISSUE TITLE
Low performance for a few grids on page

### ISSUE THREAD

**Issue by bssergy** [telerik/kendo-angular#2077]
I have a page with 7 grids, but I noticed that if I add a few grids on page, it becomes very slow (i.e. Chrome browser). Just try to input something in text field and you will see this lags.

https://angular-1tq3m8.stackblitz.io

Also I need to add droppable container for each row, but then page becomes very slow.

Is it possible to use kendo grid in this way or they just have very low performance for this purposes?

**Comment by danielkaradachki** [comment]
The delay is caused by the change detection triggered by the input change. On each change detection angular will recheck each row of each grid in the component. Try reducing the data that is rendered by using paging:
https://stackblitz.com/edit/angular-1tq3m8-f2fmnn?file=app/app.component.ts

or to wrap the grids in OnPush components:
https://stackblitz.com/edit/angular-1tq3m8-1ols7z?file=app%2Fapp.component.ts

Also, please note that the repository is for bug reports only. Please open a  [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.
