### ISSUE TITLE
Combobox: value not shown if not present in the data array

### ISSUE THREAD

**Issue by moxival** [telerik/kendo-angular#2090]
**Describe the bug**
Since version 3.5.0 of the dropdowns package, if the initial value of the combobox is not present in the data array it will not be shown but the value of the combobox will change.

**To Reproduce**
Stackblitz for combobox not working correctly: https://stackblitz.com/edit/angular-pj4jpt?file=app/app.component.ts

Stackblitz for dropdown list working as expected: https://stackblitz.com/edit/angular-aynhk1?file=app/app.component.ts

**Expected behavior**
Before version 3.5.0 the combobox was showing the initial value no matter if it were in the data array or not. In the case of remote loading/filtering the combobox should show the initially selected value even if it is not in the data array.

**Comment by moxival** [comment]
Hey guys any updated on this issue?

**Comment by tapopov** [comment]
Hey @moxival 
Apologies for the late reply. 
Indeed, the ComboBox does not extract the text from the assigned object value. This is by design and was introduced long before the 3.5.0 release. The reasoning behind this decision is rather simple. First, we cannot always extract a meaningful text. Here's an example where `valuePrimitive` is true and there's no text that we could show:
```JavaScript
    <kendo-combobox
        textField="text"
        valueField="value"
        [data]="listItems"
        [valuePrimitive]="true"
        [(ngModel)]="selectedValue"
    >
    </kendo-combobox>
    ...
    public listItems: Array<Item> = [ ];
    public selectedValue: number = 2;
```
Furthermore, if we decide to show the text extracted from the initial object value and the users edit the said text while the data is still empty, there is no way they can re-select it. To avoid further inconsistencies in the behavior, we'd rather show text only when it is extracted from the data. If the whole object, containing both the text and the value is available initially, then it is really easy to just add it to or merge it with the dataset. Here are a couple of examples:
https://stackblitz.com/edit/angular-hmw6jj?file=app/app.component.ts
https://stackblitz.com/edit/angular-hmw6jj-rh2vmw?file=app/app.component.ts

**Comment by moxival** [comment]
Thanks for your reply @tapopov, but doesn't this make the combobox inconsistent in regards to the other components from the drop downs module (say dropdown list)? 

If you guys really insist on keeping this behaviour for the combobox I believe it should be marked prominently in the documentation to avoid any confusion why the combobox behaves differently than the other components. 

Also the fact that the value of the component is changed but the GUI does not reflect that change is really a poor developer experience and later (if the dev is kind of blind :) ) a very very poor user experience. If the combobox cannot take an initial value (hence not showing the value) that is not part of the data set can you throw an error, that at least will give the developer a clue that something is wrong?

**Comment by tapopov** [comment]
Thanks for the input @moxival, it really is appreciated. 
There certainly isn't a 100% right or wrong behavior when in comes down to those scenarios. While displaying a blank component is poor UX, so is displaying a number that is later replaced with an actual text or allowing users to deselect the initial value with no way for them to select it again.
Indeed, the ComboBox behaves differently from the DropDownList. Although that is so due to differences in their nature, you are correct - it should be explicitly mentioned in the documentation. We will do so as soon as possible. We will also consider throwing error in dev mode with links to the documentation.

**Comment by siyka-marinova** [comment]
The official documentation [sample](https://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/value-binding/#toc-unresolved-text) is also available now.
