### ISSUE TITLE
Navigating using arrow keys in a button group when selection is set to 'single'

### ISSUE THREAD

**Issue by alexanderromanov** [telerik/kendo-angular#210]
If button group `selection` property is set to `single` lots of its buttons get `tabindex` set to -1. What are the reasons for this?

Plunker to check the behaviour: [http://plnkr.co/edit/6nVkzsnNcNvY2Ylo6mSd](http://plnkr.co/edit/6nVkzsnNcNvY2Ylo6mSd)

**Comment by nstoychev** [comment]
Hi @alexanderromanov 

By design tab key in a button group with selection single should behaves like a tab key on native [radio buttons](http://dojo.telerik.com/uboTEH). This can be achieved by applying tabindex="-1" to buttons which we do not want to navigate on. Here is a similar radio button group example: http://oaa-accessibility.org/examplep/radio1/

**Comment by alexanderromanov** [comment]
@nstoychev yeah, but there is a difference here: you can navigate to needed radio button by using arrow keys. In case of ButtonGroup it seems impossible to choose proper option using keyboard only

**Comment by nstoychev** [comment]
@alexanderromanov, you are right. I will modify this issue to be for fixing the navigating with arrow keys in a radio buttons group.

**Comment by valchev** [comment]
Fixed.
