### ISSUE TITLE
Grid: Poor performance with inline row editing

### ISSUE THREAD

**Issue by prabh-62** [telerik/kendo-angular#2105]
**Describe the bug**
Kendo Grid takes ~2-3 seconds to switch into inline row editing mode. It should feel instantaneous like Microsoft Excel.

**To Reproduce**
- Modify the example in the official documentation to have 1000 rows in grid: https://www.telerik.com/kendo-angular-ui/components/grid/editing/editing-row-click/
- Stackblitz URL: https://stackblitz.com/edit/angular-b8dclq?file=app/products.service.ts
- In kendo grid, scroll down to the last few rows (around 990 of 1000)
- Click on any row to switch row editing mode and you shall see 2-3 seconds lag depending on the machine hardware

**Expected behavior**
Row editing should feel instantaneous like Microsoft Excel.

In our application, we have 5 kendo grids for different features. While working on one grid to enable inline row editing with just 5 rows and 10 columns, I noticed a massive slowdown. To simulate the same problem, I had to create 1000 rows in the example.

**Screenshots**
GIF attached. UI takes few seconds to respond.

![grid_editing](https://user-images.githubusercontent.com/13006107/53777601-f0bf6580-3ec7-11e9-9faa-d16db71be658.gif)

**Browser**
 - OS: Windows 10
 - Browser Google Chrome
 - Version 72

**Additional context**
Upon profiling in Chrome, looks like recursive function is the culprit
File: `/node_modules/@progress/kendo-angular-grid/dist/es2015/rendering/common/dom-queries.js`
```javascript
export const findElement = (node, predicate, matchSelf = true) => {
  if (!node) {
    return;
  }
  if (matchSelf && predicate(node)) {
    return node;
  }
  node = node.firstChild;
  while (node) {
    if (node.nodeType === 1) {
      const element = findElement(node, predicate);
      if (element) {
        return element;
      }
    }
    node = node.nextSibling;
  }
};
```

**Comment by Sheing** [comment]
I have the same issue too when I display 1000 rows per page, took really long to render.

**Comment by Sheing** [comment]
Any new updates on this open case? It's been nearly a year ?

**Comment by mbechev** [comment]
Hi @prabh-62, @Sheing,

In most cases, the bad performance is caused by the number of rendered DOM elements. Basically, the more HTML elements that have to be rendered by the Angular framework, the worse the performance will be. This is valid for all browsers.

Indeed the mentioned behavior is expected when 1000 rows should be rendered on the page.

There are multiple optimization techniques available for Angular applications outlined in [this article](https://www.telerik.com/kendo-angular-ui/components/grid/browser-performance/) from our documentation. Indeed, when it comes to a Kendo UI for Angular Grid-related performance optimization technique the most optimal one is to use [paging ](https://www.telerik.com/kendo-angular-ui/components/grid/paging/) or [virtual scrolling](https://www.telerik.com/kendo-angular-ui/components/grid/scroll-modes/virtual/) with a smaller **pageSize**. Both approaches limit the number of rendered items at once by Angular and thus optimize the performance.
