### ISSUE TITLE
Multiselect with complex binding always using first value, cannot remove items

### ISSUE THREAD

**Issue by jaredgermano** [telerik/kendo-angular#2116]
**Describe the bug**
When binding to a multiselect with complex data and reactive forms, selecting an item always shows the same item and prevents removal from the multiselect box. 

**To Reproduce**

Stackblitz: https://stackblitz.com/edit/angular-v3kzzt?file=app/app.component.ts

Simply select any couple of items from the list.

**Expected behavior**
Multiselect should properly show selected items and allow removal of items.

**Browser**
 - Windows 10, Chrome 72.0.3626.121

**Comment by dimitar-pechev** [comment]
@jaredgermano, the weird behavior in your example is due to incorrect configuration of the component. More specifically these two couple of lines of code:

![image](https://user-images.githubusercontent.com/18740853/54120145-a8400480-43ff-11e9-929f-ede67e4c0a75.png)

The `textField` and `valueField` are used by the multiselect when the latter is bound to object data, to extract the display text and value of the object entries. Against `textField` you specify which field of each object should be read for display text value (if you don't provide an item and tag template), and for `valueField` you specify which field should be read to get the value of the entry. 

And in your example you specify for text and value field 'text' and 'value' - property names that don't exist in your object data. Which causes the unexpected buggy behavior you describe.

I've modified your example [here](https://stackblitz.com/edit/angular-v3kzzt-m1ehrt) and it seems to be working as expected when the value and text field names are provided correctly.

@jaredgermano, try the updated example and if I'm not missing something, we could close the issue.

**Comment by jaredgermano** [comment]
That did the trick. You can close this, sorry for the false alarm!
