### ISSUE TITLE
ComboBox dropdown shows only after deleting a value on Android

### ISSUE THREAD

**Issue by MaraZ1** [telerik/kendo-angular#2133]
**Describe the bug**

This does not work only on certain Android device versions/mobile Chrome versions. 
- Android 9 ONEPLUS A6013 - Chrome v 73.0.3683.75

The behavior:
- Combobox dropdown does not open after some text is written. Only after writing some text and then deleting it.

**To Reproduce**

1. Find an example in documentation in mobile Android with the version mentioned above https://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/
2. Write something
3. Delete the written text

**Expected behavior**

The dropdown should open after writing some text.

**Browser**
 - OS: Android 9 ONEPLUS A6013 
 - Browser Chrome 
 - Version 73.0.3683.75

**Comment by dimitar-pechev** [comment]
Seems related to #1958 which was actually just fixed in the latest version of the dropdowns package (**v3.5.2**) just a few days ago. 

I think it's an issue with the example - the one in the website is still not pulling the latest version of the package. Try it out on **StackBlitz** (above the example window the `Open in StackBlitz` button). Works as expected there with the latest version when I test it. 

Can you try it out there as well and get back if you are still having this issue?

**Comment by MaraZ1** [comment]
Yeah, it work in StackBlitz. Thanks.

**Comment by dimitar-pechev** [comment]
So it's just a problem with the version of the package loaded in the example then. Closing the issue now.
