### ISSUE TITLE
ComboBox with filter "crashes" when typing enter

### ISSUE THREAD

**Issue by sigVince** [telerik/kendo-angular#214]
See following Plunker: http://plnkr.co/edit/EuOjVOSsQYo4IWx7dcMT?p=preview

When I type anything and type Enter, whether it's a value in the list or not, I get an exception:
EXCEPTION: Error in ./e class e - inline template:2:12 caused by: Expected initial value of type Object. See http://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/#toc-value-selection

When I type Tab, it erases the box. Might be related to https://github.com/telerik/kendo-angular2/issues/162 ?

If I remove filtering it works well with Tab and Enter.

**Comment by tapopov** [comment]
Hello @sigVince 

This happened due to an issue that we resolved in version 0.26.8. Basically, pressing Enter should work exactly as tabbing out and in this case this means clearing the input. This is because the ComboBox does not allow custom values unless its `allowCustom` property is set to `true`. That's something that was not well explained in the documentation, so we are now improving the help topics and examples.
Feel free to close the issue if no further questions or problems arise.

**Comment by sigVince** [comment]
Works fine with the latest package.

Behavior is OK, I'm combining it with Suggest, so Tab selects the suggested item (if any) :)

Thanks!
