### ISSUE TITLE
Multiselect with kendoMultiSelectSummaryTag in filter row of Grid, which renders Tooltips for Grid Cells, behaves strangely

### ISSUE THREAD

**Issue by kunajs** [telerik/kendo-angular#2235]
**Describe the bug**
I have a grid wrapped inside div with kendoTooltip to [Render Tooltips for Grid Cells](https://www.telerik.com/kendo-angular-ui/components/tooltip/how-to/show-grid-cells-content/). In the same grid I am using reusable multiselect-filter component for row filtering (based on [this](https://www.telerik.com/kendo-angular-ui/components/grid/filtering/reusable-filter/#toc-row-filtering) example).
This multiselect component is using kendoMultiSelectSummaryTag. When I select some values in the multiselect, the summary value is displayed, but problem occurs when:
- I mouse over the summary tag (it is "blinking", if you look closer)
- I want to remove the items by clicking on X for the summary tag (it is not working)

**To Reproduce**
I prepared the Stackblitz example here: https://stackblitz.com/edit/angular-gr9fwg
1) select some Category filter - it is displayed as "x selected..."
2) try to remove the filter value by clicking on the X (see red arrow in attached image)
3) notice that hover the summary tag causes some "blinking"

Take notice of the fact that if you use [kendoMultiSelectSummaryTag]="2", the first two multiselect values are working fine. **The problem occurs only within the summary tag**.
If you remove (mouseover)="showTooltip($event)", the multiselect is working as expected, but the tooltips are not working anymore, of course.

**Expected behavior**
Multiselect should work as everywhere else.

**Screenshots**
![image](https://user-images.githubusercontent.com/39991506/56806056-224f1000-682b-11e9-9b19-f8c0f39d2097.png)

**Browser**
 - OS: Windows 10
 - Browser Chrome
 - Version 73.0.3683.103

**Comment by danielkaradachki** [comment]
An event handler bound through the markup will trigger the change detection each time it is called. Because the multiselect is passed a new array instance on each change detection, its tags are updated which causes a new event. You can avoid the problem by subscribing to the event outside the angular zone and binding the same array instance as demonstrated in the [demo](https://www.telerik.com/kendo-angular-ui/components/grid/filtering/built-in-template/#toc-customizing-filter-menus):

https://stackblitz.com/edit/angular-gr9fwg-gnj8jt?file=app/app.component.ts

**Comment by kunajs** [comment]
Thanks
