### ISSUE TITLE
kendoTextArea autoSize wrong height in Firefox

### ISSUE THREAD

**Issue by okoska79** [telerik/kendo-angular#2287]
In Firefox, the height of the textarea using autoSize is too big if there is only one row. It seems to be fine in Chrome. 

You can find an illustration here: https://stackblitz.com/edit/kendo-textarea-autosize

**Comment by elena-gancheva** [comment]
Hi @okoska79, it looks like you did not include the styles from `kendo-theme-default` npm package.
By default, the textarea has a `min-height` css property set to `88px` for both Chrome and Firefox, and it is loading from our [themes](https://github.com/telerik/kendo-themes).

I have prepared an example of the textarea with the loaded styles in `index.html` [here](https://stackblitz.com/edit/kendo-angular-textarea-autosize-height).

Is this the desired behavior you want to achieve?

**Comment by tsvetomir** [comment]
Closing until more information becomes available.

**Comment by okoska79** [comment]
> Hi @okoska79, it looks like the styles from `kendo-theme-default` npm package are not included.
> By default, the textarea has a `min-height` css property set to `88px` for both Chrome and Firefox, and it is loading from our [themes](https://github.com/telerik/kendo-themes).
> 
> I have prepared an example of the textarea with the loaded styles in `index.html` [here](https://stackblitz.com/edit/kendo-angular-textarea-autosize-height).
> 
> Is this the desired behavior you want to achieve?

First of all, thank you for you time. As for the textarea, in your example, its height for a one liner text is
- in Firefox: 44px (34px without border and padding),
- in Chrome: 30px (20px without border and padding).

I'd like to achieve that the height of the textarea in Firefox is the same as it is in Chrome.

**Comment by okoska79** [comment]
> Closing until more information becomes available.

Could you please open the issue?

**Comment by joneff** [comment]
@okoska79,

the behaviour in question is related to a 20 year old bug in Firefox (actually Netscape at the time of the bug) -- https://bugzilla.mozilla.org/show_bug.cgi?id=33654. In short, it adds one extra line in `textarea` e.g. you specify 2 lines and it adds 3.

Unfortunately, there is no quick way to workaround this issue -- we only set minimal height for `textarea` to ensure it does not shrink beneath a certain size.

You could, however, specify `max-height` on the element and handle it dynamically on [value change event](https://www.telerik.com/kendo-angular-ui/components/inputs/api/TextAreaDirective/#toc-valuechange).

Since this is a browser-related bug, I am closing this issue.
