### ISSUE TITLE
Using grid component, getting weird behaviors setting custom column width 

### ISSUE THREAD

**Issue by guille-uruit** [telerik/kendo-angular#2317]
**Describe the bug**
In a grid I'm setting custom columns width through a class which is working. Then if I try to group by a column the column header preserve the specified width while the other cells get the default width, just like if I wouldn't specified any. This only happens when an horizontal scroll is being displayed.

**To Reproduce**
- Create a grid with let say 6 columns.
- Create a class with a width of 50vh and assign it to every column (headerClass and class).
- Enable to group by some columns.
- Run the app
- The columns should have the specified width
- Group by one of the columns

**Expected behavior**
The specified width should be kept when the user group or remove the group by.

**Screenshots**

**Browser**
 - OS: Windows Server 2016, Linux Mint 19.1
 - Browser Chrome
 - Version 75.0.3770.80

**Comment by danielkaradachki** [comment]
The grid supports setting column widths only through the columns [width](https://www.telerik.com/kendo-angular-ui/components/grid/api/ColumnComponent/#toc-width) configuration.

**Comment by guille-uruit** [comment]
Hello @danielkaradachki. The columns width configuration can only be set in pixels. What I need and probably lots of apps will need is that the user be able to set the columns width in relative unit like vw, rem, etc.
Thanks for your consideration

**Comment by tsvetomir** [comment]
@guille-uruit this limitation is by design and is needed to make many of the built-in features feasible. For example, column resizing would have hard time working with relative units. Locked columns, in their current form, also rely on fixed column widths.

That said, it might be possible to achieve similar behavior by implementing a directive that listens on `window.resize` and computes the column widths as needed.
