### ISSUE TITLE
Grid: Glyph icon inside a cell not triggers in-cell edit 

### ISSUE THREAD

**Issue by ZbigniewKrzystanek** [telerik/kendo-angular#2323]
**Describe the bug**
When a glyph icon(added by a pseudo class :before) is set inside a cell, click over this icon prevent user from going in edit mode, but clicking on any other area outside the glyph triggers that. 

**To Reproduce**
https://stackblitz.com/edit/angular-ggnhcb

**Expected behavior**
Click on an icon should trigger in-cell editor

Bug appears on every browser

**Comment by danielkaradachki** [comment]
The behavior is by design. Click on icons is ignored as they usually have their own click action. You can bind a click handler and use the [API](https://www.telerik.com/kendo-angular-ui/components/grid/api/GridComponent/#toc-editcell) to put the cell in edit mode if this is required in your scenario.
