### ISSUE TITLE
Scrollevent only working with onCapture turned on (Grid)

### ISSUE THREAD

**Issue by litJL** [telerik/kendo-angular#2325]
**The bug**
When adding an event listener for scrolling, the function that has been given will only shoot when onCapture is set to true.

**To reproduce**
When adding an event listener for scrolling, set onCapture to false or leave it out completely.

When using the scrollbar of the table some text will be logged in the console.
https://stackblitz.com/edit/angular-wqyxbg?file=app/app.component.ts

**Expected behavior**
The given function should shoot with onCapture turned off aswell.

**Environment**
 - OS: Windows
 - Browser: Chrome
 - Version: 75.0.3770.80

**Comment by tsvetomir** [comment]
This behavior is by design - scroll events will not bubble up to the document, if they're already handled.

What would you like to execute in the scroll handler? We provide a dedicated event when the Grid is scrolled to the bottom for implementing [Endless Scrolling](https://www.telerik.com/kendo-angular-ui/components/grid/scroll-modes/#toc-endless-scrolling).
