### ISSUE TITLE
toODataString returns an invalid string when using case insensitive search

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2334]
**Describe the bug**
When implementing a case insensitive search using the ignoreCase property of the FilterDescriptor:
`        {field: 'Description', value: "B", operator: "contains", ignoreCase: true}`

the returned query string is invalid:
`$skip=0&$top=100&$filter=contains(tolower(Description),'B')`

it should be:
`$skip=0&$top=100&$filter=contains(Description,tolower('B'))`

**To Reproduce**
Check the following example:
https://stackblitz.com/edit/angular-e7lkbz-tuspww?file=app/app.component.ts

Click the "Custom Filter" button and check the browser console where we get a server side 500 error.

**Comment by tsvetomir** [comment]
The [OData spec](http://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part2-url-conventions/odata-v4.0-errata03-os-part2-url-conventions-complete.html#_Toc371341779) specifies that tolower must be applied to the field name, not to the value:
`$filter=tolower(CompanyName) eq 'alfreds futterkiste'`

Furthermore, the sample OData service seems to be case-insensitive and returns the same result for these two queries:
* https://odatasampleservices.azurewebsites.net/V4/Northwind/Northwind.svc/Categories?$skip=0&$top=100&$filter=contains(Description,tolower(%27B%27))&$count=true
* https://odatasampleservices.azurewebsites.net/V4/Northwind/Northwind.svc/Categories?$skip=0&$top=100&$filter=contains(Description,%27B%27)&$count=true

**Comment by tsvetomir** [comment]
The case-insensitivity might be due to the collation used on the SQL Server, see [this discussion on StackOverflow](https://stackoverflow.com/a/47076443/25449) and https://github.com/OData/ODataSamples/issues/66. It should be case-sensitive according to the spec.

The server error seems unexpected. It might be the case that `tolower` is not part of the service tests, as the service is already case-insensitive.

I consider this issue to be specific to the example service. Closing as won't fix.
