### ISSUE TITLE
MaskedTextBox valueChange with specific masked characters cursor jumps

### ISSUE THREAD

**Issue by nurlywhirly** [telerik/kendo-angular#2337]
**Describe the bug**
When using value/valueChanged (instead of ngModel) and specific Kendo Masks (C, a), the cursor jumps to the end

**To Reproduce**
https://stackblitz.com/edit/angular-t1pffk

**Expected behavior**
Cursor stays

**Browser**
 - OS: Windows 10
 - Browser Firefox 67.0.2 and Chrome 75.0.3770.90
 - Version Angular Kendo 5.2.2

**Comment by danielkaradachki** [comment]
The issue occurs because the used mask allows the default promtPlaceholder character. Once the value is set back to the component, there is no way for it to distinguish actually entered space or a prompt placeholder. You can avoid the problem by changing the default placeholder:

https://stackblitz.com/edit/angular-t1pffk-ijshdz?file=app/app.component.ts
