### ISSUE TITLE
[TreeView] Wrong parent state when children are collapsed and `CheckDirective` is used

### ISSUE THREAD

**Issue by Raisolution** [telerik/kendo-angular#2387]
Could be reproduced in the [following example](https://www.telerik.com/kendo-angular-ui/components/treeview/api/CheckMode/)

Steps to reproduce:
1. Use Mode Multiple
2. Expand the Furniture node
3. Check the Furniture node
4. Collapse the Furniture node
5. Unchecked the Furniture node - instead of clearing the checkbox, it's now ended up in intermediate state
6. Expand the Furniture node - all child are checked, but Furniture node is still in intermediate state
7. Check the Furniture node will change to correct behavior

Expected behavior: Parent state is correctly changed to `unchecked` after step 5.

Reported in ticket 1418042

Related to #2265 #2132

**Comment by tomasmejia** [comment]
I am dealing with the same bug. It should also uncheck all childs if the parent is collapsed and you uncheck it.

**Comment by cdtapay** [comment]
It's almost the end of the year. Any update on this? Thanks.

**Comment by RicardoOrtizPerez** [comment]
fuck

**Comment by midexsoftware** [comment]
It's almost end of 2021 and issue still have not been resolved.  Please expedite this.

**Comment by yanmariomenev** [comment]
Recently mentioned in - **1566016** and **1546612**.

**Comment by mbechev** [comment]
Currently, the workaround is to set the `loadOnDemand` property to _false_ (by default it is true):

https://www.telerik.com/kendo-angular-ui/components/treeview/checkboxes/#toc-preloaded-nodes

Here is an example:

https://stackblitz.com/edit/angular-mkji7f

For the cases when the children need to be loaded on demand, there isn't an available solution yet.

**Comment by svetq** [comment]
When using `[loadOnDemand]="true"` the TreeView doesn't know of its collapsed nodes. This is why, unchecking a parent will not uncheck its collapsed children.

To achieve the required behavior, we added a new property [uncheckCollapsedChildren](https://www.telerik.com/kendo-angular-ui/components/treeview/api/CheckableSettings/#toc-uncheckcollapsedchildren/). Set `[uncheckCollapsedChildren]="true"` to achieve the requirement.

The new property is available since `@progress/kendo-angular-treeview` v15.1.0.
