### ISSUE TITLE
[Editor] cleanFormatting command do not remove a formatting on a selected text.

### ISSUE THREAD

**Issue by ZbigniewKrzystanek** [telerik/kendo-angular#2403]
**Describe the bug**
A **cleanFormatting** command does not work for selected text e.g for a text with indentation, color of a text and formatting option such as H1 or quotation
Additional thing: Documentation for an editor's api contains some command that are missing e.g  cleanFormat.
 
**To Reproduce**
Code for reproduce can be found here 
https://stackblitz.com/edit/angular-bv3cj2

**Expected behavior**
A **cleanFormatting** command should reset selected text to non styled paragraph..

**Comment by valchev** [comment]
Hi @ZbigniewKrzystanek 

I tested the provided StackBlitz example. On my side the `clearFormat` command clears all the inline styles such as `bold`, `italic`, `foreColor`, and etc., but not the block styles such as changing of the `format` and `alignment`. We'll do our best to fix this as soon as possible.

**Comment by dtopalov** [comment]
The fix is available in the latest dev version of the @progress/kendo-angular-editor package (version 1.1.0 or later of the @progress/kendo-editor-common package is required).

The **cleanFormatting** command will clean the style and class attributes of block elements with inline content (paragraphs and headings so far), and has the following customizable behavior:

**blockNodeType** - if set, the paragraphs and headings will be converted to provided node type. Usecase - the headings to be converted to paragraphs to match the MS Word behavior.

**blocksInSelection** - defaults to `true` - in this case the command will handle only block elements which are in the selection and will not touch the parents. Usecase - set it to `false` to match the MS Word behavior.

**exceptMarks** - It specifies which marks to be excluded. An empty array will result in cleaning all marks. Defaults to [ state.schema.marks.link ] and will keep links only.

**Comment by dtopalov** [comment]
Released in version 2.0.1 of the **@progress/kendo-angular-editor package** (requires version 1.1.3 of **@progress/kendo-editor-common**).
