### ISSUE TITLE
Scheduler monthly view rendering issue in case of multiple recurrent events

### ISSUE THREAD

**Issue by bajzat** [telerik/kendo-angular#2419]
**Describe the bug**
The monthly view of the scheduler renders the events incorrect way if the calendar has more than one recurrent event. 

**To Reproduce**
1. https://stackblitz.com/edit/kendo-schduler-rendering-issue?file=app/app.component.ts
2. Switch to Month view
3. Navigate few months further (3-4 months usually is enough)

Result: Some of the events will be rendered with the wrong size.

**Expected behavior**
The event blocks should be rendered with the constant correct size.

**Screenshots**
issue:
![image](https://user-images.githubusercontent.com/1759750/62361349-84529c00-b523-11e9-91cc-4c41e6fd0530.png)

switching between weekly and monthly view fix the issue
![image](https://user-images.githubusercontent.com/1759750/62361377-916f8b00-b523-11e9-9bba-af61e6b0c3ff.png)

**Browser**
 - OS: Windows 10
 - Browser Chrome, EDGE
 - Version latest Kendo packages

**Comment by tom94zoe** [comment]
I have the same issue (that events are using multiple slots) wihtout the usage of recurring events

**Comment by dtopalov** [comment]
@bajzat the observed behavior seems to be caused by daylight-saving time adjustments, specific to the particular timezone - event 4 start and end dates are created using the Europe/Minsk timezone, and the event slots are incorrect when switching between months with daylight saving to ones without - for example from October to November. Events are displayed correctly again when switching back to daylight saving - for example from March to April.

Events are always displayed correctly when the Scheduler timezone matches the one of the events:

https://www.telerik.com/kendo-angular-ui/components/scheduler/api/SchedulerComponent/#toc-timezone

https://stackblitz.com/edit/kendo-schduler-rendering-issue-9tw7ex?file=app/app.component.ts

@tom94zoe can you please check whether setting the Scheduler timezone accordingly resolves the problem on your end too? If not, please send us a similar example where the issue can be observed, so we can inspect it further. Thank you in advance.
