### ISSUE TITLE
[Editor] When clicking the Editor the first toolbar button element is clicked as well

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2448]
**Describe the bug**
If the Editor is wrapped within a label and we click the label or Editor, then the first button element of the toolbar will be clicked.

**To Reproduce**
Check the following example:
https://stackblitz.com/edit/angular-5zpt6e-s5uyxd?file=app/app.component.ts

**Comment by PetarMetodiev** [comment]
`<kendo-editor>` is quite a complex component which makes its interoperability with the native `<label>`  difficult. Since submitting this issue, we have developed [`<kendo-label>`](https://www.telerik.com/kendo-angular-ui/components/labels/label/#toc-label-directive) which works as expected. Here is a [sample StackBlitz](https://stackblitz.com/edit/angular-rvmnul?file=app/app.component.ts).
With that in mind, we recommend using `<kendo-editor>` in conjunction with `<kendo-label>` instead of `<label>`.
