### ISSUE TITLE
Locals is incredibly large and makes up half the size of all other node_modules combined

### ISSUE THREAD

**Issue by Godrules500** [telerik/kendo-angular#2453]
Is there a way to have the telerik-angular-intl package only include the locals that I need or am using? The locals takes up over half of the size of all of my other node_modules combined, so this would be very useful for me as this application is only needed for the United States. I don't need all 171 mb of locals.

**Comment by tsvetomir** [comment]
There's currently no option to get a subset of the locales. Please, note that this does not affect the application bundle size, although it takes up local resources.

We've opted to include the locale data for simplicity—both from maintenance and usage standpoint. While 200MB seems excessive, the download size is under 20MB and the package is likely to be cached due to relatively infrequent releases. To put the number into perspective, an empty Angular CLI project weighs in at more than 300MB. We will reconsider if this proves to be a problem going forward. 

A partial workaround is to set up a `postinstall` script to clean up all locale data in `package.json`:
```js
"scripts": {
  "postinstall": "npx rimraf ./node_modules/@progress/kendo-angular-intl/locales",
  ...
}
```
