### ISSUE TITLE
[Dialog] using "width" and "[width]" got the different width

### ISSUE THREAD

**Issue by lon-yang** [telerik/kendo-angular#2475]
**Describe the bug**
After upgrade to `@progress/kendo-angular-dialog@4.1.0`, the width setting by `width="500"` are got no width unless changed to `[width]="500"`

**To Reproduce**
https://stackblitz.com/edit/angular-5hwyqi

**Expected behavior**
Whether it is `width = "500"` or `[width] = "500"` setting, the actual width should be '500px`

**Browser**
 - OS: Windows
 - Browser: Chrome
 - Version: 76.0.3809.132

**Comment by Raisolution** [comment]
Hi @lon-yang,

The reason for this change is the fact that in `v4.1.0` the dimensions of the Dialog could [now be set as both number and string](https://www.telerik.com/kendo-angular-ui/components/dialogs/api/DialogComponent/#toc-width) (which allows using any type of unit, not just pixels). The expression `width="500"` is treated by Angular components as a string and was previously working basically as a side effect, because the component did not differ between number and string input type and just treated it as pixel value. Currently string values are treated "as is" and applied directly. If persisting the previous behavior is a must, I would suggest using `width="500px"` instead.
