### ISSUE TITLE
DateTime picker doesn't work

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#2487]
**Describe the bug**
It's not working. When I select seconds I expect that dialog closes and value changes, but I can not change the value.

**To Reproduce**
Open your demo in Chrome (latest)

**Expected behavior**
Value in editor is changed.

**Screenshots**
![DateTimePicker](https://user-images.githubusercontent.com/1589573/65215611-5d89fe00-daae-11e9-9d9e-c9809e73e6a1.gif)

**Browser**
 - OS: Win
 - Browser: Chrome
 - Version: Version 76.0.3809.132 (Official Build) (64-bit)

**Additional context**
-

**Comment by dimitar-pechev** [comment]
@MaklaCof, the **DateTimePicker** resolves the selected value and closes the popup only after a valid date is selected and the **Set** button is clicked. The issue here is with the example in the **Material** theme - the **Set** button is hidden in the iframe if you don't scroll. We'll update this and other example windows that are not large enough.

![datеtimepicker](https://user-images.githubusercontent.com/18740853/65227320-182af800-dad1-11e9-9437-4370e630bec8.gif)

**Comment by dimitar-pechev** [comment]
We've merged the changes in the docs, making the example iframes larger. The website will be updated with the latest changes probably sometime next week. Thanks for pointing out the issue, @MaklaCof.
