### ISSUE TITLE
popupsettings width auto not applied when virtualization active in kendo-combobox 

### ISSUE THREAD

**Issue by T4YoO** [telerik/kendo-angular#2498]
**Describe the bug**
When virtualization is activated in a kendo-combobox, the popupSettings width=auto is not working anymore.

**To Reproduce**
https://stackblitz.com/edit/angular-cyrdk2?file=app/app.component.ts

**Expected behavior**
The popup width should automatically adapt to content

**Browser**
 - Browser Chrome
 - Version 77.0.3865.90

**Comment by tapopov** [comment]
Hello @T4YoO 
This behavior is expected, because there is no way of knowing how wide the content is, as it is not rendered yet. Adjusting the width of the popup so it fits the initial content does not guarantee proper results and constantly resizing the popup while scrolling (and therefore rendering new content) would be really confusing. While we won't change the behavior, we'll make sure it is properly documented as a limitation.
