### ISSUE TITLE
[Editor] Non-breakable spaces in the value are trimmed

### ISSUE THREAD

**Issue by valchev** [telerik/kendo-angular#2510]
**Describe the bug**
Non-breakable spaces in the value are trimmed.

**To Reproduce**
See the following example: https://stackblitz.com/edit/angular-jlzuvn

**Expected behavior**
The `&nbsp;` should not be trimmed.

**Comment by Sniipe** [comment]
any updates on this?

**Comment by Raisolution** [comment]
Hi @Sniipe 

The issue was caused by one of the Editor dependency packages and the fix is already available in it. Reinstalling the `@progress/kendo-angular-editor` package and it's dependencies should fix the problem. Here is the [updated version of the example](https://stackblitz.com/edit/angular-jlzuvn-bh6ajv?file=app/app.component.ts).
