### ISSUE TITLE
Kendo grid string filter ignoreCase property removed on filter reset

### ISSUE THREAD

**Issue by lucasheight** [telerik/kendo-angular#2532]
**Describe the bug**
1. When using default row filtering on a string field the ignoreCase property initially is available of the filter object.
2. Clearing the filter the searching again, the ignoreCase property is not present on the filter object.
3. Adding another character to the search the ignoreCase property returns again.

This is causing some issues on OData api's in conjunction with ToOdataString from kendo-data-query.

**To Reproduce**
1. Fire up this [Stackblitz](https://stackblitz.com/edit/angular-jrkxkk?file=app/app.component.ts).
2. Expand the console log.
3. Search for product, **note the log.**
4. Clear filter.
5. Search for product again. **Note the log (ignoreCase property does not exist)**.
6. Search for product again. **ignoreCase Property is back again.**

**Expected behavior**
I would expect the ignoreCase property to remain in all cases of using the filter.

**Browser**
 - OS: win 10
 - Browser chrome
 - Version latest

**Additional context**
## Work around
Manually add the ignoreCase property back to the filter object on dataStateChange event.

**Comment by dtopalov** [comment]
Hi @lucasheight,

By design, the Grid does not add an actual actionable **ignoreCase** option with **true**/**false** value to the FilterDescriptors in the state object, coming from the user interaction with the Grid filtering UI.

When there is an initial filter object provided, it is kept until the respective filter is cleared, but after clearing the filter, and typing a new one, you can confirm that the value of the **ignoreCase** property is always undefined (regardless of whether it is present or not).

To add an **ignoreCase** option to the FilterDescriptors reliably, the developer will need to do so manually in the **filterChange**/**dataStateChange** event handler before processing the data, or passing the state to a remote service (exactly like you mentioned in the Workaround section of the post).
