### ISSUE TITLE
Scrollview with auto scroll based on the time(interwell)

### ISSUE THREAD

**Issue by ChiranjeeviKandukuri** [telerik/kendo-angular#2620]
**To submit requests for new components and features, please use our [Feedback Portal](https://feedback.telerik.com/kendo-angular-ui).**

Hi,

Is there any support in kendo angular scrollview, we need to give some interwell based on that scroll should be happen by default(with out click on the arrows) and when you hover on the scrollview it should be pause,like bootstrap carousel.

Thanks,
Chiranjeevi

**Comment by Raisolution** [comment]
Hi @ChiranjeeviKandukuri,

Currently this functionality is not supported out of the box, but it could be easily simulated by enabling the [endless property](https://www.telerik.com/kendo-angular-ui/components/scrollview/api/ScrollViewComponent/#toc-endless) of the Scrollview and invoking the [next method](https://www.telerik.com/kendo-angular-ui/components/scrollview/api/ScrollViewComponent/#toc-next) in a setInterval call.

For further assistance with the implementation, feel free to open a [support ticket](https://www.telerik.com/account/support-tickets).

In order to consider this for a built in functionality, please log a request in on our [Feedback Portal](https://feedback.telerik.com/kendo-angular-ui), so we could track the demand for it.

**Comment by ChiranjeeviKandukuri** [comment]
Hi, 
can we change the animation slow for scrollview?
Thanks,
Chiranjeevi

**Comment by Raisolution** [comment]
Hi @ChiranjeeviKandukuri,

For any specific implementation questions, please open a [support ticket](https://www.telerik.com/account/support-tickets). This repository is intended for bug reports only.
