### ISSUE TITLE
Datepicker fires blur event even when readonly is true

### ISSUE THREAD

**Issue by woodi3** [telerik/kendo-angular#2642]
**Describe the bug**
When the datepicker is set to readonly=true, the blur event still fires. 

**To Reproduce**
Stackblitz below copying the readonly datepicker from the kendo documentation page.
https://angular-1hprkv.stackblitz.io

**Expected behavior**
If readonly is set to true on datepicker, the blur event shouldn't fire.

**Browser**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 78.0.3904.108

**Comment by dimitar-pechev** [comment]
Read-only elements should still be focusable ([ref - check out the section on **Attribute interactions**](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly)), thus the **DatePicker** will emit `focus` and `blur` events when the corresponding actions occur. It's the same with a native input element ([see example](https://stackblitz.com/edit/angular-qmvztg)). So, this is the expected behavior and we don't plan on changing it.

If you don't want the **DatePicker** to be focusable, use its `disabled` property.
