### ISSUE TITLE
[Grid] Cannot fire selection event when using label in template

### ISSUE THREAD

**Issue by lon-yang** [telerik/kendo-angular#2668]
**Describe the bug**
Cannot fire selection event when using label in template

**To Reproduce**
https://stackblitz.com/edit/angular-wkytjm?file=app/app.component.ts
```html
<kendo-grid-column field="ProductName" title="Name" width="250">
  <ng-template kendoGridCellTemplate let-dataItem>
    <label>{{ dataItem.ProductName }}</label>
  </ng-template>
</kendo-grid-column>
```

**Expected behavior**
Fire the selection event as normal

**Screenshots**
![1](https://user-images.githubusercontent.com/9428909/71945076-b8cc3180-3200-11ea-9c20-840a1763f466.gif)

**Browser**
 - OS: Windows
 - Browser: Chrome
 - Version: 79.0.3945.79

**Comment by inikolova** [comment]
This outcome is intended - by design we prevent the built-in Grid  behaviour when the actual click target in the Cell Template is a focusable element.

However, you could use the generic **_click_** event for the <label> and manually click the cell.
https://stackblitz.com/edit/angular-wkytjm-ckdnlj?file=app/app.component.ts
