### ISSUE TITLE
Kendo combobox template parse error

### ISSUE THREAD

**Issue by vinaykannambadi** [telerik/kendo-angular#2669]
enabling virtualization as per the documentation here: https://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/virtualization/  is leading to template parse error.
![image](https://user-images.githubusercontent.com/14233684/71964412-897aec00-3223-11ea-9a24-3b3d6114b552.png)

can someone guide us on this

**Comment by dimitar-pechev** [comment]
You are probably using an older version of the **DropDowns** package.

As the problem is related to your project setup and not to the component, I'd ask you to [open a support ticket](https://www.telerik.com/account/support-tickets) if you want further assistance on the topic. This repository is for bug reports only.

**Comment by vinaykannambadi** [comment]
Hi @dimitar-pechev  thank you for your response. yes i was able to find out the cause from this https://github.com/telerik/kendo-angular/issues/2428.

one more thing is there any way to implement virtualization for kendo-combobox, using "@progress/kendo-angular-dropdowns--v3.5.6 " ?

**Comment by dimitar-pechev** [comment]
@vinaykannambadi, no - the feature is implemented in **v4.1.0** and there is no way to use it in older versions.
