### ISSUE TITLE
[Calendar] activeViewDateChanged strange behavior

### ISSUE THREAD

**Issue by PeterStaev** [telerik/kendo-angular#2704]
**Describe the bug**
The `activeViewDateChanged` is triggered very strangely. 
* When you scroll with the mouse wheel over the calendar seems it is triggered but for the previous month for example when October is visible it is triggered with 09/30. 
* When you change the months either by clicking on the scroll on the left or by going to the year view and selecting a month it is not triggered at all. 

**To Reproduce**
https://stackblitz.com/edit/angular-nkysva?file=app/app.component.ts
Scroll over the month or select a month and notice the log. 

**Expected behavior**
When you mouse scroll the value should be the currently visible month. When you select a month, the event should be triggered. 

**Browser**
 - OS: Windows10
 - Browser: Chrome
 - Version: 79

**Additional context**

**Comment by PeterStaev** [comment]
Seems if you set `[navigation]="false"` it works much better!

**Comment by dimitar-pechev** [comment]
@PeterStaev, the `activeViewDateChanged` provides info for the currently rendered period in the virtualized scrollable container. That's why the date is sometimes in a previous month/period - the active view date is the first date of the first rendered period, which is not necessarily the currently visible period.

We're considering adding a `scroll` event which should provide data what is the currently visible period. 

Closing this thread, as we're already tracking the issue here #2663.
