### ISSUE TITLE
kendo-popup -> OnPush -> not aligned correctly on first run

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#2781]
Just see: 
https://stackblitz.com/edit/angular-he4vwr

it is an example with OnPush change detection strategy, nothing else. On the first run, you see popup not well aligned (see image attached). After one click or window resize you could see that popup restores his correct position.

![image](https://user-images.githubusercontent.com/5664195/75665942-3fd3de00-5c75-11ea-9269-93d477828458.png)

**Comment by mbechev** [comment]
As a workaround, you can use [markForCheck](https://angular.io/api/core/ChangeDetectorRef#markForCheck) to explicitly marks the view as changed in **ngAfterViewInit** hook:
https://stackblitz.com/edit/angular-vl63ck-cazyu3?file=app/app.component.ts

**Note** that the issue is not reproduced in Angular 9.

**Comment by meriturva** [comment]
In my case is still present on angular 9 and it is related to animation. If I disable animate property on popup everything works great. I will wait for this fix and then I will try to reproduce more accurately issue, Reproduce issue with our complex layout is really difficult in that case.
Again thanks.

**Comment by mbechev** [comment]
Hi @meriturva,
Please find the attached Angular 9 project and check the Popup behavior:
[test-popup.zip](https://github.com/telerik/kendo-angular/files/4343728/test-popup.zip)
Extract the zipped file and use the following commands to run the application:
- npm install
- ng servelo

**Comment by gregservera** [comment]
This continue to occur using @progress/kendo-angular-popup@5.0.0. It's a real issue for us.

Do you plan to resolve it?

**Comment by arsenlol** [comment]
There is an [Output ](https://www.telerik.com/kendo-angular-ui/components/popup/api/PopupComponent/#toc-positionchange)called `positionChange`, and it happened so that when I assign a handler to it, then it will notice alignAnchor value and render in proper place initially. I was not using onPush, but you can try to put `markForCheck `or `detectChanges ` there.

```
<kendo-popup
    ...
    (positionChange)="test($event)"
    ...
```

```
test(event) {
    console.log(event);
    // this.cdr.markForCheck()
}
```

**Comment by stnikolova** [comment]
The issue is no longer reproducible using the latest (v13) **@progress/kendo-angular-popup** version https://stackblitz.com/edit/angular-8tuhvr
