### ISSUE TITLE
[SplitButton] - Cannot change item disable state after button has been initialized

### ISSUE THREAD

**Issue by vivek201** [telerik/kendo-angular#2806]
**Runnable Example**
https://stackblitz.com/edit/angular-4xwqlq

**Describe the bug**
Cannot disable an item in the split button after button has been created

**To Reproduce**
1. Click the split button to confirm that the button is initially enabled
2. Click the button `Disable items` to change the property `disabled` to true
3. The item in the split button is not disabled

**Expected behavior**
The item in the split button is disabled

**Screenshots**
![image](https://user-images.githubusercontent.com/12758783/76946524-424c5e00-692c-11ea-8abe-fa9bf9af44b5.png)

**Browser**
 - Browser: All

**Comment by Raisolution** [comment]
Hi @vivek201 

The Angular change detection mechanism won't detect the updated disabled property, as it not an input of the SplitButton component. To address the case, update the whole data collection, in order to disable the button. Here is [the updated example](https://stackblitz.com/edit/angular-4xwqlq-zugkzi?file=app/app.component.ts) of this.
