### ISSUE TITLE
[DropDownButton] Angular 9 .k-state-focused class does not disappear 

### ISSUE THREAD

**Issue by AnnaTkachenko** [telerik/kendo-angular#2807]
**Describe the bug**
When you open DropDown with DropDownButton and click outside of DropDown or click DropDownButton - .k-state-focused class still there and button.k-button aria-expanded="true". 

(It could happend because of some change detection changes between Angular 8 and 9)

**To Reproduce**
1 Run Angular 9 application;
2. Click DropDownButton;
3. Click outside of DropDownButton or click DropDownButton ;
4. Check DropDownButton classes - .k-state-focused still there 

**Expected behavior**
When I click outside of DropDownButton this button should detect it and work as in Angular 8 version [in Stackblitz example from Doc](https://www.telerik.com/kendo-angular-ui/components/buttons/dropdownbutton/).

**GIF with problem**
![kendo-dropdown-button-bug](https://user-images.githubusercontent.com/26151759/76972705-a6285400-6937-11ea-8553-c76aa861e0de.gif)

**Comment by PetarMetodiev** [comment]
Hi Anna,

Whenever the `DropDownButton` is clicked(both when closed or opened), it should receive `.k-state-focused`. This is by design.

Regarding the issue with it retaining `.k-state-focused` after being closed when clicked outside - we were unable to reproduce that. [Here is a sample StackBlitz](https://stackblitz.com/edit/angular-bqrdxe). We tried it locally too(both on MacOS and Windows) but still could not reproduce it.

Having said that, we cannot consider this a bug. Please provide runnable reproducible example so we can reassess the issue.

**Comment by cluetjen** [comment]
Problem exists only with change detection OnPush.

https://angular-sw14k1.stackblitz.io

Steps to reproduce:
* Click any of the dropdown buttons
* Click somewhere in white space (NOT another button)
* Class k-state-focused is still assigned

Expected:
* Class should be removed

It works as expected if you remove changeDetection: ChangeDetectionStrategy.OnPush

**Comment by preslavapetrova1** [comment]
The fix is now available in the latest official version `kendo-angular-buttons v5.4.3`
