### ISSUE TITLE
Grid: master-detail -> add a class where master row is opened/expanded

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#2809]
When we have a grid with details we have the main tr with class: k-master-row
The main problem is that we don't have any `css` selector when the master row is opened.

Is it possible to have a one more class named for example: k-master-row-expanded ?

**Comment by dtopalov** [comment]
Ho @meriturva,

Currently this functionality is not supported out of the box, but it could be easily achieved by using the [new Grid expansion directive](https://www.telerik.com/kendo-angular-ui-develop/components/grid/master-detail/expanded-state/) and the [rowClass callback](https://www.telerik.com/kendo-angular-ui-develop/components/grid/styling/#toc-rows) to provide the desired class to the expanded rows.

In order to consider this for a built in functionality, please log a request in our [Feedback Portal](https://feedback.telerik.com/kendo-angular-ui), so we could track the demand for it.

**Comment by meriturva** [comment]
Added request here: https://feedback.telerik.com/kendo-angular-ui/1458507-master-detail-grids-add-a-css-class-when-master-row-has-detail-opened

**Comment by dtopalov** [comment]
@meriturva Thank you for submitting the feature request. We will track the customer demand in the Feedback portal, and will consider adding this enhancement based on the interest.

**Comment by samir-kamble** [comment]
Example does not work. Please help

**Comment by meriturva** [comment]
@samir-kamble actually example on stackblitz works correctly!
