### ISSUE TITLE
Kendo Editor breaks on populating when html contains thead tag inside table

### ISSUE THREAD

**Issue by deepak-dhull-01** [telerik/kendo-angular#2844]
When we are passing `[value]="someHTML"`
and `someHTML `contains `table tag with thead.`
kendo editor fails in loading.

**Comment by mbechev** [comment]
Hi @deepak-dhull-01,

The fix is available in [dev ](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/)version of the package (v1.0.7):
https://stackblitz.com/edit/angular-wpnfmx?file=app/app.component.ts

Please keep in mind that the **thead**, **th**, **tbody** elements will not be visualized in the Editor as they are currently not supported. Internally we have logged an enhancement issue regarding these elements.

**Comment by deepak-dhull-01** [comment]
Thanks @mbechev :)
