### ISSUE TITLE
Column menu button us not focused when the header is draggable

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#2882]
**Describe the bug**
When the Grid header is draggable (e.g. grouping or reordering functionality is enabled) the column menu button is not focused when it is clicked.

![Screenshot (53)](https://user-images.githubusercontent.com/33104481/81405915-45e8ae00-9141-11ea-90dd-61dcb91a6d5c.png)
![Screenshot (53)](https://user-images.githubusercontent.com/33104481/81406008-74ff1f80-9141-11ea-983c-1601c7dfad40.png)

**To Reproduce**
Open grid Column Menu. 
https://stackblitz.com/edit/angular-9eowqv?file=src/app/app.component.ts

**Comment by dtopalov** [comment]
Fixed in the latest version of the `@progress/kendo-angular-grid` package:

https://stackblitz.com/run/?file=app/app.component.ts

**Comment by dtopalov** [comment]
Since the last accessibility and keyboard navigation enhancements related to the Column Menu, the issue seems to be partially resolved when no template is used:

https://stackblitz.com/edit/angular-upu3d6-ra2sse?file=app/app.component.ts

When the menu is opened, the focus goes to the first inner element, `Escape` brings the focus back to the menu icon.

However, there is a discrepancy in the behavior when a Column Menu template is used. We are planning a separate enhancement which will allow consistent behavior regardless of whether a template is used or not.
