### ISSUE TITLE
Calendar: month view rendering has wrong first day of the week

### ISSUE THREAD

**Issue by EricSch** [telerik/kendo-angular#293]
I think, the calendar control doesn't respect the first day of week and renders always "Sun, Mon, Tues" instead of "Mon, Tues, .." in my case.

The month and day names are translated correctly.

**Comment by ggkrustev** [comment]
Hi @EricSch, thanks for reporting this issue.
It seems that the Calendar component doesn't shuffle the weekday names based to the first day of week value. Hence it always shows 'Sunday' as first week day, although the days below *are actually shuffled accordingly*.

We will address the issue immediately and will release a fix later today. Will update the thread once the fix is live.

**Comment by ggkrustev** [comment]
@EricSch, please give `@progress/kendo-angular-dateinputs@0.3.6`a try.

**Comment by EricSch** [comment]
@ggkrustev Thank you. Will do, please give me until tomorrow

**Comment by EricSch** [comment]
@ggkrustev The calendar is now rendered correctly, thank you.
But suddenly the scrolling (mouse and keyboard) doesn't work anymore. Where there any changes?

**Comment by ggkrustev** [comment]
@EricSch, no not all. We only shuffled the headers (week day names). All other logic is unchanged. Could you provide a plunker?

**Comment by EricSch** [comment]
I tried to find out which version is served via CDN. Is it also the last one?

**Comment by ggkrustev** [comment]
Nope, the CDN version (the one hosted on www.telerik.com/kendo-angular-ui) is an older one.
I suppose that my request for plunker repo is not very adequate :). 

I prepared a simple Github repo that includes the latest versions of Kendo Calendar for Angular:
https://github.com/ggkrustev/ng2-test-demo | master branch

It seems to work just fine on my end. Could you modify it in order to demonstrate the issue?

**Comment by EricSch** [comment]
Yes, it works. Even when I add my "DatePicker" (Calendar/Popup combination). 
The problem has to be on our side. I'm a bit clueless right now, need to go back step by step, was has changed. There are so many moving parts in our app. :)
Thanks again.

**Comment by EricSch** [comment]
![image](https://cloud.githubusercontent.com/assets/25437/22928166/4e5a26e6-f2b5-11e6-8d96-6e24e73d95de.png)

There is my Issue. The left calendar is scrollable, the right one doesn't. Trying to find out the difference beside the selected date.
