### ISSUE TITLE
[Editor] Error is thrown when <colgroup> or <col> are used

### ISSUE THREAD

**Issue by PetarMetodiev** [telerik/kendo-angular#2942]
**Describe the bug**
An error is thrown when the value of the editor contains `<colgroup>` or `<col>` tags:
```
ERROR TypeError: Cannot read property 'nodeType' of null
```

**To Reproduce**
https://stackblitz.com/edit/angular-ananox?file=app/app.component.ts

**Expected behavior**
No error should be thrown when using `<colgroup>` or `<col>`.

**Comment by mbechev** [comment]
The fix is available in [dev ](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/)version of the package:
https://stackblitz.com/edit/angular-slvjlu?file=app%2Fapp.component.ts

The **colgroup** and **col** elements will not be visualized in the Editor as they are currently not supported. Internally we have logged an enhancement issue regarding these elements.

**Comment by siyka-marinova** [comment]
The fix is now available in the latest official version `kendo-angular-editor v.1.2.0`
