### ISSUE TITLE
Combobox value has been cleared after blur

### ISSUE THREAD

**Issue by lon-yang** [telerik/kendo-angular#2944]
**Describe the bug**
Combobox value has been cleared after blur. Because `filterChange` fired again after select vaue and passed an empty value.

Package version >= `4.2.6`

**To Reproduce**

https://stackblitz.com/edit/angular-fn69z2-sqruor

**Expected behavior**
`filterChange` event not fired after value selected.

**Screenshots**
![1](https://user-images.githubusercontent.com/9428909/84346613-f6cfe600-abe2-11ea-8bb7-c5de1ed09425.gif)

**Browser**
 - OS: Windows
 - Browser: Chrome
 - Version: 80

**Additional context**
The version below 4.2.6 works fine

**Comment by dimitar-pechev** [comment]
This is actually the correct behavior by design - as the options list can be opened via the toggle button, the list of options should not remain filtered after a value is selected. [Related to this bug fix](https://github.com/telerik/kendo-angular/issues/2572).

If this is not the desired behavior in your specific use case, you can omit filtering the data set when the `filterChange` event value is an empty string and a selected value is present. [Here's an example](https://stackblitz.com/edit/angular-cqhffk).

Alternatively, you can [enable custom values](https://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/custom-values/) and entries that are not present in the data set will not be discarded.

If you need help implementing this, please open a support ticket.
