### ISSUE TITLE
Method distinctPrimitive performs five times more often than expected

### ISSUE THREAD

**Issue by Berezhnyk** [telerik/kendo-angular#2948]
There is an issue with the Multi-Checkbox Menu Filtering example.
Method distinctPrimitive performs five times more often than expected. This causes problems with large amounts of data.

1) Run the example provided in the official documentation
2) Click the filter button (distinctPrimitive calls five times)
3) Select any filter item (distinctPrimitive calls five times)

Here is the runnable StackBlitz: https://stackblitz.com/edit/angular-offpgh

Expected behavior: 
Method distinctPrimitive runs once (per change)

**Comment by dtopalov** [comment]
Hi @Berezhnyk 

This is Angular-specific behavior related to running multiple checks and change detection cycles in development mode (and also when there is a function call in the template).

Here is the updated example with enabled production mode, and binding the data input to a component field rather than to a function call:

https://stackblitz.com/edit/angular-offpgh-xw7psi?file=app/app.component.ts

**Comment by Berezhnyk** [comment]
Thanks for the explanation!
