### ISSUE TITLE
Kendo-Editor cursor pointer at end of text when using two-way binding value

### ISSUE THREAD

**Issue by nevraydin** [telerik/kendo-angular#2997]
**Describe the bug**
When I use `[(value)]` with kendo-editor and after typing on any line, cursor pointer is at end of text. 

**To Reproduce**
Stackblitz link: https://stackblitz.com/edit/angular-wqfvhi

**Expected behavior**
Cursor pointer's position should not change.

**Comment by PetarMetodiev** [comment]
Hi Nevra,

Thanks for reporting this issue. We will be looking into it but in the meantime I can suggest two workarounds:

1. Use `[(ngModel)]` instead of `[(value)]`. Here is a sample StackBlitz - https://stackblitz.com/edit/angular-wqfvhi-epjwhh
2. Use `[value]` in tandem with `(valueChange)`. Again, here is an example - https://stackblitz.com/edit/angular-wqfvhi-rj9tpi

I hope this helps.

**Comment by nevraydin** [comment]
Hi Petar,

When I use `[(ngModel)]` it works, thank you.

**Comment by Raisolution** [comment]
Fix available in `v2.2.0`
