### ISSUE TITLE
Angular Popup collision isn't working.

### ISSUE THREAD

**Issue by shyam1992** [telerik/kendo-angular#3000]
**Describe the bug**
The popup goes outside the viewport when it is placed at the right of the screen. Even the anchor position and popup position properties aren't helping.

**To Reproduce**
The anchor is the right most element of the screen and the popup is placed after that. The styling for the container is relative positioning with display:flex

**Expected behavior**
The popup to be visible inside the screen.

**Screenshots**
<img width="1002" alt="Screenshot 2020-07-14 at 6 59 14 PM" src="https://user-images.githubusercontent.com/6847851/87431416-3c2d6c00-c604-11ea-90a5-01d9d7b701c4.png">

**Browser**
 - OS: [ Mac Os]
 - Browser [Chrome]
 - Version [latest]

**Comment by dtopalov** [comment]
Hi @shyam1992,

I tried to replicate the described scenario and problem, but could not:

https://stackblitz.com/edit/angular-yduef3-bqdsou?file=app/app.component.ts

The Popup is shifted to the left to fit the page, but is still visible.

Can you please modify the example above, or share a similar isolated runnable project where the undesired behavior can be observed so we can inspect it further, and try to determine whether there is an issue on our end that we can address? Thank you in advance.

**Comment by shyam1992** [comment]
@dtopalov ,
Please find the url where the issue has been reproduced.

https://stackblitz.com/edit/angular-yduef3-zra4eh?file=app%2Fapp.component.scss

Thanks for the quick reply, hope I will get the resolution soon.

**Comment by dtopalov** [comment]
Hi @shyam1992,

Thank you for the demo. The issue seems to be caused by adding a an element with absolute position within the Popup. This prevents its dimensions from being calculated properly, and this is why the collision does not reposition it back in the viewport. To avoid this, either remove the absolute positioning of the inner element:

https://stackblitz.com/edit/angular-yduef3-izcgn5?file=app%2Fapp.component.scss

... or place the whole custom class on the **kendo-popup** element instead:

https://stackblitz.com/edit/angular-yduef3-gc3hfn?file=app%2Fapp.component.html

As this repo is for bug reports only, and the issue is related to a custom styling and scenario-specific implementation, I can suggest opening a [support ticket](https://www.telerik.com/account/support-tickets) if you have further questions, or need any assistance with specific scenario implementations or configurations.

**Comment by shyam1992** [comment]
Thanks for your help @dtopalov , moving the class to Kendo-popup helped a bit.
