### ISSUE TITLE
Any sample on using server side Paging,Filtering,Sorting with WebAPI2

### ISSUE THREAD

**Issue by nssidhu** [telerik/kendo-angular#303]
I have large Table from and want to perform server side, paging, filtering & sorting with WebAPI 2(API controller or Odata)
looking for any example .

**Comment by rkonstantinov** [comment]
I'm afraid we do not have such example. You could take a look at [this help article](http://www.telerik.com/kendo-angular-ui/components/grid/data-binding/data-binding/) on how to use [toODataString](http://www.telerik.com/kendo-angular-ui/components/dataquery/api/toODataString/) in order to serialize Grid's paging and sorting descriptors to OData spec.

Also please be aware that this repo is for bug reports with the components. If you need technical support assistance you could: 
- post your question on [SO](http://stackoverflow.com/questions/tagged/kendo-ui-angular2). 
- we offer private support through [Your Account](https://www.telerik.com/account/support-tickets) on telerik.com.
