### ISSUE TITLE
Notification: closable and hideAfter combination

### ISSUE THREAD

**Issue by Sonaryr** [telerik/kendo-angular#3049]
In our use case I would like to combine the closable and hideAfter properties for the kendo-angular-notification.
But once you add the closeable property, the hideAfter property is ignored.

I did however found a way to mimic this behaviour by storing the `NotificationRef` and calling `notifciation.close()` myself after the given time, but I would rather have this done by the framework itself.

**Comment by mbechev** [comment]
Hi @Sonaryr, 

The reported behavior is expected. In general, the **closable** property is used, when the Notification should appear until the user closes it manually, using the 'x' button rendered on the right side.

When setting the **closable** option to true, then the **hideAfter** functionality is overwritten, in order to prevent closing the notification without user interaction. 

To close such notification programmatically, use hide method of the **NotificationRef**:
https://stackblitz.com/edit/angular-spdzhx?file=app/app.component.ts
