### ISSUE TITLE
Kendo Angular Grid : Blank space in the end when you resize(reduce) any column.

### ISSUE THREAD

**Issue by niranjan1991** [telerik/kendo-angular#3059]
Kendo Angular Grid: Blank space in the end when you resize(reduce) any column.

If the column is getting resized then content from the column should get fit with the remaining space, but it is showing white space.

You can see the whole data in the tool-tip but not in the actual column. (PFA for better understanding)

Requesting to provide any solution where huge content will get good fit after resizing the column as well 

![Screenshot (58)](https://user-images.githubusercontent.com/16316438/93214136-6b866380-f782-11ea-82bb-4d3c281e239c.png)

**Comment by dtopalov** [comment]
Hi @niranjan1991,

This is the expected behavior, as described in the following documentation section:

**Comment by LaniMoo** [comment]
After much searching for a solution for this, I saw that there is a "disclaimer" in the official documentation and that there are a few suggested workarounds, but I don't understand why it isn't built-in behavior for other columns to auto-resize in order to prevent the white space. I can't think of any table I've ever interacted with in any website or program that shows a white space when columns are resized. All other grids behave like this when resizing: https://examples.bootstrap-table.com/#extensions/resizable.html

It's awkward to explain to my higher-ups and user-base that the white space is "normal" behavior when they complain that it looks odd. 

Sorry for the rant... I'm just wondering if there's something I'm missing, like a limitation or something that makes this impossible, or an existing setting that prevents this, since it seems there are no plans to address this at all from what I've seen. If not, would it make sense for me to request this in the Feedback Portal? Appreciate any input, thanks!
