### ISSUE TITLE
Scheduler : workWeekStart/End not working in timeline view

### ISSUE THREAD

**Issue by Felx-B** [telerik/kendo-angular#3090]
**Describe the bug**
Hi,
I'm trying to use kendo scheduler views with custom `workWeekStart` and `workWeekEnd` values, and it seems not to work, either on scheduler or on views.

**To Reproduce**
https://stackblitz.com/edit/angular-kendo-scheduler-workweek

**Expected behavior**
It should restrict view to selected week days

**Browser**
 - OS: Windows
 - Browser Chrome
 - Version 86

Thank you

**Comment by Felx-B** [comment]
A better solution would be adding a `timeline-work-week` view

**Comment by gkarapeev** [comment]
Hi @Felx-B.

Thank you for taking the time to log this issue.

Indeed, as you have already pointed out, the desired behavior can be expected from a TimelineWorkWeekView component, analogous to the existing WorkWeekView component. The TimelineWeekView is working as expected, but it only greys-out the non-working weekdays.

I have created a feature request for that on your behalf in our feedback portal - [you can access it here](https://feedback.telerik.com/kendo-angular-ui/1491790-add-a-kendo-scheduler-timeline-work-week-view-component).

We prioritize planning and immplementing new features based on user demand, so in order to push it forward, be sure to give it your vote.

Many thanks,
Georgi
