### ISSUE TITLE
Grid height is applied to the content instead of the whole widget

### ISSUE THREAD

**Issue by PeterStaev** [telerik/kendo-angular#310]
I'm setting the height for example to 400. When I inspect the widget its actual height is 449 = 400 from the content + 47 from the header + 2*1 from the header borders. I think it is much more logical when I set the height of the widget the whole widget to be set to that height and then internally the content to be resized accordingly taking into account headers, footers and borders.

**Comment by tsvetomir** [comment]
Thanks for reporting this issue. It's a known limitation of the current implementation that we hope to fix soon.

**Comment by meriturva** [comment]
I guess it is fixed now! Height input has to be height of whole area...right?

**Comment by tsvetomir** [comment]
No, it's not fixed yet. Sorry!

**Comment by meriturva** [comment]
@tsvetomir ops...sorry!

**Comment by gyoshev** [comment]
The problem has been fixed in the latest grid and theme packages. The grid now accepts arbitrary heights set through its `height` property:

    <kendo-grid [style.height.px]="200" />
    <kendo-grid [style.height]="'100%'" />

Setting `[height]="200"` has the same effect as setting `[style.height.px]="200"`, so this is a breaking change -- grids that are currently using `height` will become smaller, as the grid chrome is included in the  grid size.
