### ISSUE TITLE
Kendo-Angular-Editor crashing on pressing Enter in the end of paragraph

### ISSUE THREAD

**Issue by FunInfinity** [telerik/kendo-angular#3105]
Kendo Angular editor is failing with error when I try to enter a new paragraph while I'm in the end of any paragraph (not at the beginning - I mean inside of < p >< /p >)

To reproduce:
Open any editor, e.g. in manual https://www.telerik.com/kendo-angular-ui/components/editor/
Navigate to first example, put cursor on the end of first paragraph (after word  "manipulation.") and press Enter

Result:
- Paragraph is not added
- Console is showing error : "Can not convert <> to a Fragment (looks like multiple versions of prosemirror-model were loaded)"

Expected result:
- New paragraph should be added

**Comment by dtopalov** [comment]
Hi @FunInfinity,

Indeed, currently there is an issue related to loading the correct dependencies in our new documentation site that caused the described error. The problem is not in the Editor code itself, and using it in a regular Angular project should not cause such problems. We will do our best to resolve the documentation examples issues as soon as possible.
