### ISSUE TITLE
Window - keep the scroll position when opened via Angular service

### ISSUE THREAD

**Issue by kunajs** [telerik/kendo-angular#3145]
**Describe the bug**
Nowadays, when the browser's content is scrolled and the window is opened via angular service, the scroll position is changed to kendoWindowContainer position.
Is there a way how to keep the scroll position in the same place where the button is? To change kendoWindowContainer position is not a solution because we could have multiple elements which open the kendo window (each on different scroll position... and I know that only the last kendoWindowContainer is used).
The goal is at least to keep the scroll position as the click target position, or better: not to scroll anywhere.

**To Reproduce**
Here is example on Stackblitz: https://stackblitz.com/edit/angular-re7brh
Click on the button and see that the content is scrolled up.

**Expected behavior**
Not to scroll anywhere, keep the current scroll position.

**Browser**
 - OS: Windows 10
 - Browser: Chrome
 - Version 86.0.4240.198

**Comment by mbechev** [comment]
Hi @kunajs,

Indeed the Window position depends on where the **kendoWindowContainer** is defined. When the component is shown, the page is scrolled since the rendered Window is focused at that moment.

To avoid this behavior the developer can programmatically set the [top ](https://www.telerik.com/kendo-angular-ui/components/dialogs/api/WindowComponent/#toc-top) property of the Window, depending on the scroll position. Here is an example demonstrating the suggestion:

https://stackblitz.com/edit/angular-re7brh-finw1b

**Comment by AnilBhandare09** [comment]
1) We add top property before open the windowthen top property is not set
2) we set top property after open the kendo window first-time top property is not working, second time its working fine
