### ISSUE TITLE
DropDownList is not accessible with keyboard when used as filter in Grid

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3167]
see #1598 
**Describe the bug**
Using DropDownList as a custom filter in Grid is not accessible with the keyboard:

![image](https://user-images.githubusercontent.com/33104481/103894009-eccd8180-50f6-11eb-8689-01a3bedc2618.png)

**To Reproduce**
1. Click the `Tab` key to reach the DropDownList.
2. Items cannot be selected with keyboard.

https://stackblitz.com/edit/angular-xhkusv

Reported in private support threads - **1483160** and **1483313**.

**Comment by dimitar-pechev** [comment]
This issue is specific to the DropDownList and not the Grid. In the provided example, the component `defaultItem` is bound to a property getter which returns a new object reference on every change detection cycle (e.g. when the arrow down key is clicked). And as the `defaultItem` is one of the properties that define the component state, every time it's regenerated, the state gets updated as well and the internal selected index is reset to the currently selected item before value change is resolved. Seems to work on a closed dropdown probably due to race conditions.

In general, the DropDownList does not support binding state props (`data`, `value`, `defaultItem`, etc.) to getters which return new objects references on each call, as in some cases constantly comparing the previous and the current object/array value could result in poor performance.

The way to go here is to bind the `defaultItem` to a field which gets updated only when it's needed. [Here's an example](https://stackblitz.com/edit/angular-xhkusv-crkjul?file=app%2Fdropdownlist-filter.component.ts).

```ts
public defaultItem: any;

public ngOnChanges(changes: SimpleChanges): void {
    if (changes.textField || changes.valueField) {
      this.defaultItem = this.getDefaultItem();
    }
}

public getDefaultItem(): any {
    return {
      [this.textField]: "Select item...",
      [this.valueField]: null
    };
}
```
