### ISSUE TITLE
When filter is applied and user unchecks a checkbox in a row, the grid unchecks 1 row below the intended row. 

### ISSUE THREAD

**Issue by robertochupin** [telerik/kendo-angular#3169]
Issue Description:
When filter is applied and user unchecks a checkbox in a row, the grid unchecks 1 row below the intended row. 

Intended Result:
When filter is applied, the row that has its checkbox unchecked should uncheck and hide. Also, it should not uncheck any other checkboxes in other rows.  

StackBlitz link: 
https://stackblitz.com/edit/angular-ustoz9-ctestr?file=app%2Fproducts.ts

Steps:

1. Click on checkboxes:
![image](https://user-images.githubusercontent.com/72090790/104057264-793f7900-51b7-11eb-9309-ceda536014bb.png)

2. Set filter for "Discontinued" to True.
![image](https://user-images.githubusercontent.com/72090790/104057387-b7d53380-51b7-11eb-8334-97789193abe2.png)

3. Uncheck the Second Row's Checkbox and you will see that it does uncheck and hide it. However, it unchecks the row below it.
![image](https://user-images.githubusercontent.com/72090790/104057520-e94dff00-51b7-11eb-820b-89cedc82e74c.png)

![image](https://user-images.githubusercontent.com/72090790/104057569-fc60cf00-51b7-11eb-9fe8-5f9bf445c288.png)

Let me know if any more details are needed.

Thanks

**Comment by mbechev** [comment]
Hi @robertochupin, 

By default, the Grid tracks changes by the index of the data item and that allows not to destroy the rows when performing data operations. However, that behavior can be controlled via the [trackBy ](https://www.telerik.com/kendo-angular-ui/components/grid/api/GridComponent/#toc-trackby) method of the Grid. Basically, it should return the **dataItem** in order to suit the requirements for your use case.

Please check the updated example.

https://stackblitz.com/edit/angular-ustoz9-5wvf1e

**Comment by robertochupin** [comment]
That fixed it ! thank you :)
