### ISSUE TITLE
Invalid HTML is produced when using bullets in Editor

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#3176]
**Describe the bug**
Invalid HTML is produced when new bullet is added and then deleted

**To Reproduce**
  1. Open [this demo](https://www.telerik.com/kendo-angular-ui/components/editor/).
  2. Add a new bullet by pressing ENTER at the end of the existing list
  3. Then press Backspace
  4. `<p></p>` is inserted between `<li>` tags.

```
broken in v2.0.0
```

**Comment by nstoychev** [comment]
The produced HTML is actualy valid. The empty paragraph has been appended to the previous list item in case the user wants to remove the list-item only. The same behavior can be seen in the ProseMirror's [Setting up an editor](https://prosemirror.net/examples/basic/) demo. I assume that this behavior is by design.
