### ISSUE TITLE
headerClass not working 

### ISSUE THREAD

**Issue by satish10105** [telerik/kendo-angular#3197]
I need to apply the style  for all Header 

[headerClass] --> is not working (Class name displaying in inspect but style not coming)
<style>
.myClass {
  padding:3px 3px;
  white-space:normal;
  background-color: red;
}
</style>
<kendo-grid-column  field="name" [headerClass]="myClass" title="Name"></kendo-grid-column>
        <kendo-grid-column field="isGeneric" [headerStyle]="{'padding':'3px 3px','white-space': 'normal'}"  title="Generic">
          <ng-template kendoGridCellTemplate let-dataItem>
            <span>
              <mat-icon *ngIf="dataItem.isGeneric" [color]="'accent'">done_outline</mat-icon>
            </span>
          </ng-template>
        </kendo-grid-column>

 [headerStyle]  is working fine 
<kendo-grid-column  field="name" [headerStyle]="{'padding':'3px 3px','white-space': 'normal'}"  title="Name"></kendo-grid-column>
        <kendo-grid-column field="isGeneric" [headerStyle]="{'padding':'3px 3px','white-space': 'normal'}"  title="Generic">
          <ng-template kendoGridCellTemplate let-dataItem>
            <span>
              <mat-icon *ngIf="dataItem.isGeneric" [color]="'accent'">done_outline</mat-icon>
            </span>
          </ng-template>
        </kendo-grid-column>

**Comment by dimitar-pechev** [comment]
@satish10105, the class is probably missing in the mark-up due to incorrect configuration. In the above shared code snippet, you are binding the column `[headerClass]` to the class property `myClass`. If the latter is not defined in your component, it will be evaluated as `undefined` and no class will be rendered subsequently, [Here's a working example](https://stackblitz.com/edit/angular-qndbp4), where it's show-cased how to bind to a class value correctly either through a class prop or directly in the template.

![image](https://user-images.githubusercontent.com/18740853/106703717-7f2c4c80-65f3-11eb-8cee-59f4a157bf50.png)

![image](https://user-images.githubusercontent.com/18740853/106703641-51df9e80-65f3-11eb-95fe-8c085510abdb.png)

If you need further help, please open a support ticket. This repo is for bug reports only.
