### ISSUE TITLE
Focused cell position is not pronounced with JAWS reader

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3207]
**Describe the bug**
Using **JAWS** screen reader, the focused cell position is not pronounced (e.g. _row 3, column 2_). 

**NVDA** reader works as expected.

**To Reproduce**
https://stackblitz.com/edit/angular-tkzckk

**Comment by tsvetomir** [comment]
Fixed in the [development builds](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/), snippet is updated. The Grid now renders the `aria-rowindex` attribute regardless of the `navigable` setting.

JAWS only announces the column and row index when focusing the Grid initially. The column name is announced only when the user navigates to a different column. Navigating between rows only announces values. Presumably, this is to reduce noise with repetitive announcements.

In any case, the cell content can be wrapped in an element with a custom `aria-label` by defining a [cell template](https://www.telerik.com/kendo-angular-ui/components/grid/columns/templates/#toc-cell-template).

**Comment by mbechev** [comment]
Fixed in [v5.03](https://www.telerik.com/kendo-angular-ui/components/grid/changelog/#4637d3db-26d0-5f2b-abd6-6c1d2f0bd88c)
