### ISSUE TITLE
100% Stacked Bar Chart group element goes out of svg bounds for certain data constellations

### ISSUE THREAD

**Issue by beyerl** [telerik/kendo-angular#3236]
**Describe the bug**
When using the 100% Stacked Bar Chart in Angular Kendo UI, the group element displaying the series is not contained within the svg as expected. This leads to the impression, that the relations between the series are displayed wrongly. The error only occurs, if just a single category is used inside the bar chart and if the first series of the category has a much larger value than the other series. In the example above, the error occurs with the following values: 933, 25, 117. If the order is changed to e.g. 25, 933, 117, the error disappears. The series with value 933 seems to be display much to small in relation to the other series. This is the case, because the whole group containing all the series transgresses the border of the surrounding svg. The relations between the series are actually correct, but a huge part of the 933 series is not visible, because it's rendered outside the svg.

**To Reproduce**

Go to https://stackblitz.com/edit/angular-t7qzvv-dhoer8?file=app%2Fapp.component.ts.

For further analysis:
Inspect the chart svg in chrome devtools. The group containing the series transgresses the bounding rectangle of the svg it is contained in.

**Expected behavior**
The group should be contained within the svg and the relations between the values of the sereis should be displayed properly.

**Browser**
 - OS: Windows 10
 - Browser: Current Firefox and Chrome

**Additional context**
We are business customers of Kendo UI, owning five developer licences. This is not the first time, we cannot use a component, because it is buggy. Same happend with the date range component. Sorry, but I'm getting a bit underwhelmed.

**Comment by stnikolova** [comment]
@beyerl  Thank you for the detailed feedback. We are going to prioritize the issue and look into it further.

**Comment by stnikolova** [comment]
The reported behavior is the default for the Bar Chart component’s [`valueAxis`](https://www.telerik.com/kendo-angular-ui/components/charts/api/ChartComponent/#toc-valueaxis) settings and prevents the automatic axis range from snapping to zero. This way the data portions could easily be differentiated when there are values far from `0`. In order to force the automatic axis range to snap to zero, the [`narrowRange`](https://www.telerik.com/kendo-angular-ui/components/charts/api/ValueAxis/#toc-narrowrange) option of the [`valueAxis` ](https://www.telerik.com/kendo-angular-ui/components/charts/api/ValueAxis)input property should be set to `false`.

The following example demonstrates the `narrowRange: false` option: https://stackblitz.com/edit/angular-t7qzvv-gffqyj
