### ISSUE TITLE
CldrIntlService throws NoCurrencyDisplay with locale zh

### ISSUE THREAD

**Issue by P-H-F** [telerik/kendo-angular#326]
When trying to use the `CldrIntlService.parseNumber` or the `CldrIntlService.formatNumber` function for the locale `zh` the following error message is thrown:
```javascript
NoCurrencyDisplay: 
    Cannot determine currency display information. 
    Please load the locale currencies data. 
    The default culture does not include the all currencies data.
```

### Plunker
http://plnkr.co/edit/W2MXEMqpCEeAlxBITSKN?p=preview

**Comment by danielkaradachki** [comment]
It seems that we do not correctly determine the default currency for this locale due to the chronological order of the region currencies. We will look into this. For now I can suggest to explicitly specify the currency:

http://plnkr.co/edit/QWeKwoRKKD42ar4bCuEg?p=preview

I will follow up here once the problem has been fixed.

**Comment by danielkaradachki** [comment]
The problem should now be fixed. Please try updating the kendo-intl package.

**Comment by P-H-F** [comment]
Thank you!
