### ISSUE TITLE
[Grid] Incorrect column widths after resizing and hiding columns

### ISSUE THREAD

**Issue by PeterStaev** [telerik/kendo-angular#3275]
**Describe the bug**
When you have a columns that are dynamically shown/hidden from code and when you resize a column and then hide some columns, the column widths get totally messed up and does not have anything with the fixed widths nor with the resized widths. 

**To Reproduce**
https://stackblitz.com/edit/angular-ferlbb?file=app/app.component.ts

1. Press Show Columns button
2. Resize the Product Name column (either increase or decrease the width, it doesn't matter)
3. Press the Hide Columns button

You will see that all the columns get an increased width, although it is not needed. I suspect they get resized proportionally so that they fit the scrollable width w/o taking into consideration that the hidden columns no longer are taking space, Because the more columns you have to the right that are getting hidden, the larger the columns become. 

**Expected behavior**
Columns should not get expanded width. 

**Screenshots**

**Browser**
 - OS: Mac/Windows
 - Browser: Chrome
 - Version 89

**Additional context**

**Comment by tsvetomir** [comment]
As a workaround, use `ngIf` to hide the columns, [see updated snippet](https://stackblitz.com/edit/angular-ferlbb-mnqinl?file=app/app.component.ts).

**Comment by PeterStaev** [comment]
@tsvetomir that does not work. In your snippet you forgot to reverse the logic of the flag, so at the start all the columns are visible and that's why it works. See [here](https://stackblitz.com/edit/angular-ferlbb-twjbqu?file=app/app.component.ts) where the flag is corrected.

**Comment by preslavapetrova1** [comment]
@PeterStaev the described behavior has been fixed. The expected behavior is that when all column widths are explicitly set and the cumulative column width is less than the available Grid width, the remaining width is distributed evenly between all columns. However, when the hidden columns are shown, the previously defined widths will be set again. This is also documented in the [Column Widths](https://www.telerik.com/kendo-angular-ui-develop/components/grid/columns/width/) article as a second bullet point.
