### ISSUE TITLE
[Grid] with multiselect on, only 1 selectedRows is counted

### ISSUE THREAD

**Issue by patrickritskes** [telerik/kendo-angular#3297]
**Describe the bug**
When you have a Kendo Grid with multiple selection on, and check more then 1 checkbox, only 1 selectedRows is counted everytime:

this.is the console log from the selectionChange Event:
```
{
  "deselectedRows": [],
  "selectedRows": [
    {
      "dataItem": {
        "ProductID": 3,
        "ProductName": "Aniseed Syrup",
        "SupplierID": 1,
        "CategoryID": 2,
        "QuantityPerUnit": "12 - 550 ml bottles",
        "UnitPrice": 10,
        "UnitsInStock": 13,
        "UnitsOnOrder": 70,
        "ReorderLevel": 25,
        "Discontinued": false,
        "Category": {
          "CategoryID": 2,
          "CategoryName": "Condiments",
          "Description": "Sweet and savory sauces, relishes, spreads, and seasonings"
        }
      },
      "index": 2
    }
  ],
  "ctrlKey": true,
  "shiftKey": false
}
```

**To Reproduce**
Setup a Kendo Grid with multiselect on, example from the Telerik site itself:
https://www.telerik.com/kendo-angular-ui/components/grid/selection/persisting/#toc-selecting-all-items

Click on the corresping stackblitz to see it happen when you console.log the event

**Expected behavior**
I expect to see a Array with all the selected grid rows, when you check more then 1 checkbox

**Comment by mbechev** [comment]
Hi @patrickritskes,

In order to get all selected rows, handle [selectedKeysChange ](https://www.telerik.com/kendo-angular-ui/components/grid/api/SelectionDirective/#toc-selectedkeyschange) event:

https://stackblitz.com/edit/angular-svrmjn

In case you need any further assistance regarding this case I want to encourage you to [open a support ticket](https://www.telerik.com/account/support-tickets) and we will gladly assist ad this repo is for bug reports only.

**Comment by patrickritskes** [comment]
@mbechev great!! thank you, I guess I missed that part in the docs!
