### ISSUE TITLE
[TileLayout] Adding new tile to the array of items doesn't update indexes

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3349]
**Describe the bug**
Adding a new tile to the array of items doesn't update indexes. This will cause resizing and reordering issues.

**To Reproduce**
1. Remove the first tile by clicking the remove button
2. Add a new tile by clicking the Add Item button
3. Try to resize the newly added tile to colSpan 2 or reorder
https://stackblitz.com/edit/tilelayout-remove-item-from-list-hhyjxf?file=app%2Fapp.component.ts

**Workaround**
Update the items array indexes when adding a new item
https://stackblitz.com/edit/tilelayout-remove-item-from-list-cb9c8v?file=app%2Fapp.component.ts

**Expected behavior**
To update the items array indexes properly and resize/reorder the newly added item without any issues

**Comment by ciiara** [comment]
The described behavior is actually to be expected. That is because the array holding the tiles is of a reference type.

Angular's change detection does not get triggered when a reference variable is mutated. The reason is that even though its contents have changed, the object instance stays the same.

In regards to the specific case in question:
In order for Angular to detect the change in the array, the developer could replace the already existing array passed to the _ngFor_ structural directive with an entirely new array. In the [second StackBlitz](https://stackblitz.com/edit/tilelayout-remove-item-from-list-cb9c8v?file=app%2Fapp.component.ts) example from the initial comment that is what [_map()_](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) does.

I am closing this thread as it does not pertain to a bug in the component.
