### ISSUE TITLE
kendo-fileselect disappears when angular formcontrolname is used multiple times

### ISSUE THREAD

**Issue by webmandman** [telerik/kendo-angular#3379]
**Describe the bug**
<kendo-fileselect></kendo-fileselect> works fine out of the box. But when in the same html angular component there also exist multiple(2 or more) "formControlName" directives  (doesn't matter if inside the same form element or outside) the kendo element disappears. See stackblitz. 

**To Reproduce**
https://angular-brxabn.stackblitz.io

**Expected behavior**
The kendo element should not disappear.

**Screenshots**
![image](https://user-images.githubusercontent.com/991677/125544713-f4fc69e9-b2c1-4519-98ac-362d1b7b77a6.png)

**Comment by mbechev** [comment]
Hi @webmandman,

Could you please fork the demo and send us the URL of the example as demonstrated in the following screencast:
https://screenrec.com/share/7EPCfbWhKZ

Thanks.

**Comment by webmandman** [comment]
This is my forked demo https://angular-brxabn.stackblitz.io/

**Comment by mbechev** [comment]
> This is my forked demo https://angular-brxabn.stackblitz.io/

Yes, I am able to see the reported issue, but we need to debug the code that produces the end result. That is why I am asking for the full URL of the demo. 

However, I managed to extract the unique URL and see the code:

https://stackblitz.com/edit/angular-brxabn

However the reported issue is caused by the following lines:
```ts
 template: `
    <mat-checkbox formControlName="day2">Day 1</mat-checkbox>
    <mat-checkbox formControlName="day1">Day 1</mat-checkbox>
  `
```

Indeed **formControlName** property must be used only inside \<form> tags as described in the following article:
https://angular.io/api/forms/FormControlName#description

```html
<form>
   <mat-checkbox formControlName="day2">Day 1</mat-checkbox>
   <mat-checkbox formControlName="day1">Day 1</mat-checkbox>
</form>
