### ISSUE TITLE
Dialog - Action property that indicates it closes dialog

### ISSUE THREAD

**Issue by djarekg** [telerik/kendo-angular#341]
There should a property for action buttons (i.e. close: true) that specifies if the action button closes the dialog. This would be helpful in cases where there is not additional action required in the result callback.

**Currently**
```
const dialog = this._dialogService.open({
    title: 'Error',
    content: 'Failed to save.',
    actions: [
        { text: 'Ok' }
    ]
});
dialog.result.subscribe(() => dialog.close());
```

**Proposed**
```
this._dialogService.open({
    title: 'Error',
    content: 'Failed to save.',
    actions: [
        { text: 'Ok', close: true }
    ]
});
```

**Comment by gyoshev** [comment]
@djarekg a great suggestion, this should simplify common scenarios. Maybe the default value of the property should be `true`, as most use cases don't require that the dialog remains open.

**Comment by djarekg** [comment]
Agreed that true should be default.

**Comment by gyoshev** [comment]
As it turns out, the said functionality is already in place. When opening the dialog through the `DialogService`, all actions automatically close the dialog, no need to subscribe to the result for that. Preventing this can be achieved through custom actions. All this is [shown in the examples](http://www.telerik.com/kendo-angular-ui/components/dialog/service/#toc-usage) in the documentation.
