### ISSUE TITLE
[Grid] How can i disable loading skeleton when using virtual scrolling

### ISSUE THREAD

**Issue by hizliemre** [telerik/kendo-angular#3449]
It seems to default behavior when using virtual scroll. Can I disable this behavior?

**Comment by dtopalov** [comment]
Hello @hizliemre,

Displaying the built-in or a custom loading skeleton is the default behavior when using virtual scrolling, and the `loading` option is set to `true`. To disable the loading skeleton, the developer can omit binding the `loading` input. A custom loading indicator could be displayed instead of the Grid built-in one.

If you need further assistance with applying the discussed approach or have other questions regarding using the Kendo UI for Angular components or customizing them, please open a [support ticket](https://www.telerik.com/account/support-tickets), as this repository is for bug reports only.
