### ISSUE TITLE
[DateTimePicker] opens popup at current date

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#3470]
**Describe the bug**
When using the DateTimePicker in Angular 9+ applications then the popup opens where the current date is disregarding the selected date. The issue is reproducible only when using Angular versions greater than 8.

**To Reproduce**
Please see the following attached proejct:
[datepickers.zip](https://github.com/telerik/kendo-angular/files/7351308/datepickers.zip)

**Expected behavior**
The popup should open where the selected value is.

**Comment by aldrashan** [comment]
Any update yet?
A lot of our users are annoyed by this.

**Comment by aldrashan** [comment]
Seeing how this issue still hasn't been fixed, I've went and tracked down the error myself.

Inside the datetimepicker.component.ts file, edit the following inside the template:

![image](https://user-images.githubusercontent.com/20169019/157414540-74482c7e-15ca-4f49-99d4-b85fd81781df.png)

The [focusedDate] input has to be above the [(value)] input.
The CalendarComponent uses a setter for the focusedDate @Input field, which is triggered by both the [focusedDate] Input itself and it's manually called inside the [value] input setter function.
The value input setter function actually has to be the last one to call public set focusedDate(focusedDate:Date), otherwise the calendar will open at the focusedDate's value (or 'today' if no value) again.

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds).
