### ISSUE TITLE
[Kendo Grid] [Mozilla Firefox] Horizontal scroll not working when DIR = RTL 

### ISSUE THREAD

**Issue by feffo982** [telerik/kendo-angular#3476]
Using Mozilla Firefox version 88.0 for Linux Mint 64 bit, the grid does not show the horizontal scrollbar when in RTL mode. 

LTR Version:
![ltrgrid](https://user-images.githubusercontent.com/33452606/137935040-0a421cb2-495b-454a-b2e9-59a07aa69f73.png)

RTL Version:
![rtlgrid](https://user-images.githubusercontent.com/33452606/137935065-f8a30f68-a2e2-4a84-badd-e6e3d006b9a3.png)

**Comment by mbechev** [comment]
Hi @feffo982,

We are closing this issue as part of our backlog triage. We will open it again if an example demonstrating the bug was provided.

In case any further questions come up, you can [activate a trial license](https://www.telerik.com/kendo-angular-ui) and open a [support ticket](https://www.telerik.com/account/support-tickets).
