### ISSUE TITLE
TileLayout inside absolutely positioned element - dragging

### ISSUE THREAD

**Issue by kunajs** [telerik/kendo-angular#3492]
**Describe the bug**
If TileLayout component is placed inside absolutely positioned element and I want to reorder or resize it by dragging, the position of dragged element is wrongly set.

**To Reproduce**
Here is the stackblitz example: [https://stackblitz.com/edit/angular-kwfj5f](https://stackblitz.com/edit/angular-kwfj5f)
1) try to drag the tile to some position OR try to resize the tile
2) the tile jumps to absolute position offset by absolute position of the parent: 
![image](https://user-images.githubusercontent.com/39991506/140512611-96438654-026c-4493-9636-921ae9d0530e.png)

**Expected behavior**
The element should copy the position of the mouse cursor and not jump somewhere else.

**Browser**
 - OS: Win 10
 - Browser Chrome
 - Version 95.0.4638.69

**Comment by kunajs** [comment]
One more problem, which is related to this, is when I place some clickable element inside `kendo-tilelayout-item-header`. Because the position is moved on mousedown, the click event is not finished (mouseup is not fired because the mouse pointer is in initial position, but the target element is not there anymore - it has been moved).

**Comment by dtopalov** [comment]
Hello @kunajs,

Indeed, this is a known limitation of the TileLayout component which will be documented accordingly. The only currently known workarounds are to remove the absolute/relative positioning of the parent, and use margin/padding instead:

https://stackblitz.com/edit/angular-kwfj5f-kfguxv

https://stackblitz.com/edit/angular-kwfj5f-txmf7r

You can also support, comment, and track the following feature request in our Feedback portal:

https://feedback.telerik.com/kendo-angular-ui/1542096-tilelayout-resizing-and-reordering-in-absolute-relative-positioned-containers

**Comment by kunajs** [comment]
Hi and thanks for an answer.

But I am not satisfied with it. The position of the dragged item is offset **NOT with the offset of the parent container**, but with the offset relative to the whole page.

I have the structure of the page layout for example top header, side menu, footer and body (position absolute) and within the body there is some absolutely positioned div (e.g. top 50%, left 300px), in which I need the TileLayout component. It is hard to imagine that I need to rework the whole page layout (which is in fact much more complex than in the example) only because dragging is not working within your component.

It means that your solution is not suitable for me. It would not be a problem to set the padding/margin for the parent container only, but not the whole structure.

I prepared example: [https://stackblitz.com/edit/angular-kwfj5f-wls6a8](https://stackblitz.com/edit/angular-kwfj5f-wls6a8)
- see div with css class `some-complex-nested-structure`, which represents the complex nested hierarchy within many parent elements.

I hope you do not expect that your solution is the right way to solve this bug.

Regards, kunajs

**Comment by schase-nfocus** [comment]
Here's what I did as a hack workaround: raise an event on the container during mouse-in and allow any parent component to subscribe to the event, adjust position by using ngClass with a style of position: unset or whatever works for you, then on mouse-out set the boolean to false.  I can't fathom how this component could have been released with such a known issue...

**Comment by AN-BC** [comment]
@schase-nfocus I think that is an interesting workaround. We are encountering the same issue in our memberjunction open-source CDP product we're aiming to release this month into 1.0. If you have a code sample you can share of your workaround it would be greatly appreciated as we plan to tackle this bug and either implement this workaround or replace the Kendo Tile Layout component with something else. We are on the very latest Kendo UI Angular release and this bug is still in there.

@dtopalov any updates on a patch to an upcoming release? It says unplanned on this issue from what I can see.

**Comment by slavenai** [comment]
Hi @AN-BC ,

This was previously discussed in a private support thread, however I will provide some information here as well for visibility.

Since [v13.5.0](https://www.telerik.com/kendo-angular-ui/components/changelogs/kendo-angular-ui/#v13.5.0), the Kendo UI for Angular TileLayout supports dragging when nested inside containers with `position: relative`.Dragging and resizing when the component is nested inside an absolute positioned element, as well as resizing in relatively positioned container are still considered limitations. We've closed this issue since we are already tracking the [mentioned feedback](https://feedback.telerik.com/kendo-angular-ui/1542096-tilelayout-resizing-and-reordering-in-absolute-relative-positioned-containers) item in our Feedback Portal.
