### ISSUE TITLE
TabStrip 'tabSelect' Event not fired

### ISSUE THREAD

**Issue by sgampe** [telerik/kendo-angular#3503]
**Describe the bug**
After updating @progress/kendo-angular-layout from 6.1.8 to a newer version, the tabSelect event is not fired when selecting a tab programmatically.

That's weird because in the changelog (https://www.telerik.com/kendo-angular-ui/components/layout/changelog/) of version 6.2.0 you wrote:

"tabSelect event is emitted when selectTab method is invoked".

With 6.1.8 it's working, but the bug came with 6.2.0.

**To Reproduce**
Click the select tab button here:
- 6.1.8: https://stackblitz.com/edit/angular-gjn6hz-9y4qvj
- 6.2.0: https://stackblitz.com/edit/angular-gjn6hz

**Expected behavior**
selectTab method triggers the tabSelect event

**Browser**
 - OS: Windows
 - Browser Firefox 94, Chrome 95

**Comment by Raisolution** [comment]
Hi @sgampe 

The behavior prior to version `6.2.0` was unintentional and is considered a bug. This is why the statement `tabSelect event is emitted when selectTab method is invoked` is listed under the `Bug Fixes` section of the changelog.

In general, we strive to fire events in the Kendo UI for Angular suite only before/after user triggered actions or at any other occasion the developer cannot control (e.g. at animation end). This is not the case when a component API method is invoked, as this is intentional and one has full control over the logic to be executed along with it.
