### ISSUE TITLE
Gantt cannot be installed via schematics (ng add ...) in an Angular 9 app

### ISSUE THREAD

**Issue by yousafnawaz** [telerik/kendo-angular#3519]
An attempt to install the Gantt via ng add @progress/kendo-angular-gantt results in the following error:

ng add @progress/kendo-angular-gantt
Your global Angular CLI version (13.0.3) is greater than your local version (9.0.7). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
Installing packages for tooling via npm.
Installed packages for tooling via npm.
File **node_modules/@progress/kendo-angular-/package.json** does not exist.

**Comment by mbechev** [comment]
Hi @yousafnawaz,

Indeed the warning message is expected in this case because your local app CLI version is lower than your global CLI version. 

The experienced issue is not related to any specific Kendo UI for Angular component installation. The same warning will appear each time when other _ng_ commands are used in this case.

To stop that warning, the developer needs to locally install a specific angular CLI version that matches the global one.

**Comment by yousafnawaz** [comment]
Hi @mbechev, 
Error is on last line  
**File node_modules/@progress/kendo-angular-/package.json does not exist.**
I am getting this only for kendo gantt module. all other modules I use install successfully.

**Comment by mbechev** [comment]
Hi @yousafnawaz,
 
I just skipped the last line, sorry about that. I am reopening the issue.

**Comment by dimitar-pechev** [comment]
Tested it out with `@angular/cli@9` and works fine on my end. Might be an issue with the local environment. As it doesn't look like a problem with the schematics but rather with the environment, I'd suggest you open a support ticket, where you could share a list of dependencies and if needed send over a runnable project.
