### ISSUE TITLE
[Grid] Form control value is not marked as selected in the Combobox component

### ISSUE THREAD

**Issue by destus90** [telerik/kendo-angular#3532]
**Describe the bug**
Combobox resets its value to null when editing a cell in the grid. 

**To Reproduce**

1. Go to https://stackblitz.com/edit/angular-p4raun?file=app%2Fapp.component.ts
2. Click on the grid row.
3. Observe that the selected item in the combobox is empty.

**Expected behavior**
The grid value should be selected in the combobox.

**Comment by mbechev** [comment]
Hi @destus90,

The observed behavior is indeed caused by the specific custom configuration and especially when assigning the ComboBox data. At the time of assigning the form control value, the ComboBox is empty and has no data. 

The developer could consider replacing the **setTimeout** function:

```ts
import { of } from 'rxjs';

this.data = of([
     { name: 'Small', id: 1 },
     { name: 'Medium', id: 2 },
     { name: 'Large', id: 3 },
     { name: 'Chai', id: 10 },
]);
```

If any further assistance is required of this case, please open a [support ticket](https://www.telerik.com/account/support-tickets) as this repository is for bug reports only.

**Comment by destus90** [comment]
`setTimeout` is just an imitation of a real http call to fetch data. From your comment I understood that we shouldn't display a kendo-editor until the dropdown's data is fetched.
