### ISSUE TITLE
[Grid] SelectionDirective: selectedKeys should have 2-way binding 

### ISSUE THREAD

**Issue by Rus7am** [telerik/kendo-angular#3533]
**Describe the issue**

[SelectionDirective](https://www.telerik.com/kendo-angular-ui/components/grid/api/SelectionDirective/) input [selectedKeys](https://www.telerik.com/kendo-angular-ui/components/grid/api/SelectionDirective/#toc-selectedkeys) should have **2-way binding** (mentioned [here](https://github.com/telerik/kendo-angular/issues/634#issuecomment-307707699)) in the documentation and examples like [this](https://www.telerik.com/kendo-angular-ui/components/grid/selection/#toc-toggling-the-selection-functionality).

**Comment by tsvetomir** [comment]
The directive emits a [`selectedKeysChange` event](https://www.telerik.com/kendo-angular-ui/components/grid/api/SelectionDirective/#toc-selectedkeyschange), technically supporting two-way binding. The unusual thing about it is that the Grid will mutate the `selectedKeys` array in-place. That's why the examples are functioning even with one-way binding.

We're revising this behavior across all components as altering the provided array is unexpected. As a result, getting the updated selection will require the use of two-way binding. This is evident in the [TreeView development builds](https://www.telerik.com/kendo-angular-ui-develop/components/treeview/selection/) where the changes are already applied.

This will be a breaking change and we'll try to bundle it with #3502, but it may not be ready on time. For the time-being our recommendation is to use two-way binding so the code remains compatible with the updated version. We'll update the documentation examples to match.

Closing this as we're already tracking this issue in https://github.com/telerik/kendo-angular/issues/3165.
