### ISSUE TITLE
[DatePicker] Datepicker has display errors

### ISSUE THREAD

**Issue by theConsite** [telerik/kendo-angular#3547]
**Describe the bug**
Datepicker does not display January
Month selector glitches after a while of scrolling

**Expected behavior**
January displayed
Mong selector working correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/31901782/149959806-2a500220-36be-488b-8783-f8383125779b.png)
![image](https://user-images.githubusercontent.com/31901782/149959839-f969afa5-00fe-4907-87ca-1f5118ca208f.png)

**Browser**
 - OS: Windows 10
 - Browser Chrome, Edge
 - Version Chrome 97.0.4692.71, Edge unknown

**Additional context**
Error appears on @progress/kendo-angular-dateinputs^5.1.0, and @progress/kendo-angular-dateinputs^5.3.0, i didn't test other versions

**Comment by yanmariomenev** [comment]
Hi @theConsite,

About the displaying of January - The described layout is by design so that the end user is notified which year is beginning while scrolling, the first month naturally being January. The full name of the month is also displayed in the Calendar header. This can be modified with the NavigationItemTemplateDirective:

https://stackblitz.com/edit/angular-eqrjzu?file=src%2Fapp%2Fapp.component.ts

As for the Navigation bar scrolling, it is indeed a bug on our side and a proper label is added.

![chrome_a4qeJJ64AJ](https://user-images.githubusercontent.com/49076727/186175370-6cc2d7ce-9bcc-4a33-a659-5ffe1aa7790c.png)

**Comment by JoomFX** [comment]
Please feel free to reopen the issue if needed.
