### ISSUE TITLE
[Tooltip] Undisclosed Breaking Change

### ISSUE THREAD

**Issue by eluchsinger** [telerik/kendo-angular#3549]
According to the [changelog ](https://www.telerik.com/kendo-angular-ui/components/tooltips/changelog/#7c9a5784-bbda-5826-bcf4-4bb8df1044f3) for the tooltips component, the switch from `3.0.3` to `3.1.0` introduces a breaking change because only the themes v5 are supported.

This change should in my opinion trigger a breaking change for the Tooltip component, because updating the minor version is not safe anymore (following [Semantic Versioning](https://www.telerik.com/kendo-angular-ui/components/installation/up-to-date/)).

**Comment by Raisolution** [comment]
Hi @eluchsinger,

Thank you for noticing this discrepancy and for reporting it. We did not publish a major version of the `kendo-angular-tooltip` package, because it is working as expected with versions `4.x.x` of the themes too. We only wanted to indicate that it is compatible with version 5, but not that this theme version is _required_. Thus, the issue is on our end and only related to the wrong changelog.

With that being said, we published a new version `3.1.4` which contains a corrected backlog and indicates that the package is working with both major versions of the themes. It will soon be live on the website too.
