### ISSUE TITLE
[TextArea] Resizable options not working properly

### ISSUE THREAD

**Issue by preslavapetrova1** [telerik/kendo-angular#3555]
**Describe the bug**

The `resizable` options of the TextArea are not working properly after R1 2022 updates. 

**To Reproduce**

1. Open this demo https://www.telerik.com/kendo-angular-ui/components/inputs/textarea/sizing/#toc-setting-the-resize-directions.
2. Try the different resize options.
3. For the auto-resize set the `resizable` option to `auto`.

**Expected behavior**
The TextArea container should be resized according to the resizable options: `horizontal`, `vertical`, `both`, `auto`.

**Comment by Raisolution** [comment]
Fix available in `v8.0.2` of the `kendo-angular-inputs` package.

**Comment by michaelmarcuccio** [comment]
This is broken again in v8.0.9. With a direct example from your page:
[https://www.telerik.com/kendo-angular-ui/components/inputs/textarea/sizing/#toc-auto-resizing](https://www.telerik.com/kendo-angular-ui/components/inputs/textarea/sizing/#toc-auto-resizing)

**Comment by Raisolution** [comment]
Hi @michaelmarcuccio 

To address the problem in question, we had to include additional styles in the `kendo-themes`. I suppose it is reproducing on your end, because the theme was not updated while the Inputs package was. I recommend using themes version `5.2.0` or newer.

Here is a stackblitz example with the latest versions of the two - https://stackblitz.com/edit/angular-vngvsf?file=app%2Fapp.component.ts

P.S. The problem is reproducing in the documentation for the same reason (version discrepancies). The working example can be observed in[ the develop version of the docs](https://www.telerik.com/kendo-angular-ui-develop/components/inputs/textarea/sizing/#toc-auto-resizing). It will be live next week. Please excuse us for this discrepancy.
