### ISSUE TITLE
ColorPicker acts strangely when used with ngFor directive.

### ISSUE THREAD

**Issue by luminela** [telerik/kendo-angular#3603]
**Describe the bug**
The **kendo-colorpicker** component has a strange behaviour when used with *ngFor directive. The color picker will close immediately as soon as gradient is clicked, making it impossible to pick the desired color properly. This problem does not occur if the component is not used with an *ngFor directive.

**To Reproduce**
[StackBlitz example](https://stackblitz.com/edit/angular-jswpci?file=app/app.component.ts)

**Expected behavior**
Color Picker popup should not close while trying to select a color.

**Additional Information**
* StackBlitz example uses Angular v9, but it happens with Angular v13.2 as well.

**Comment by Raisolution** [comment]
Hi @luminela 

The reason for the observed behavior lies in the Angular framework itself, namely - by default when a change detection is triggered inside an ngFor loop, Angular updates the view and redraws its content. Since interacting with the ColorPicker gradient triggers a change detection, the view is getting updated, which leads to the unexpected closing of the popup.

Possible workaround for this scenario is to use the ngFor [trackBy option](https://angular.io/api/core/TrackByFunction), which after each change detection compares it's previous and current value to determine whether the content inside the ngFor view should be redrawn or not.

Here is the [updated version of the example with trackBy included](https://stackblitz.com/edit/angular-jswpci-sqdsph?file=app/app.component.ts).
