### ISSUE TITLE
Upload: Possibility to clear the file list

### ISSUE THREAD

**Issue by EricSch** [telerik/kendo-angular#361]
My use case is the following:
I have an upload control inside a modal dialog. The user is able to upload files.
When files are uploaded or when the dialog is closed and reopened, the file or files should be removed.

I tried to call `removeFilesByUid` in the success event, but then an error was thrown in the `FileMap.setFilesState` method.
And I don't see a method to clear the filelist or reset the upload control, preferably in the open event of the dialog.
Did I miss something?

**Comment by Raisolution** [comment]
Hi @EricSch,

the reason for this behavior is that the success event is fired before the files are set as successfully uploaded (because the event is preventable, which allows setting them as failed). I would suggest to add a setTimeout call in the event handler:
```
  onSuccess(e: SuccessEvent) {
    let uid = e.files[0].uid;
    
    if(e.operation === "upload") {
      setTimeout(() => {
        this.myUpload.removeFilesByUid(uid);
      });
    }
  }
```

Thank you for posting this. We will inspect the case in order to give more user friendly message, when such scenarios occur. I wish you a great day!
