### ISSUE TITLE
[DropDownList] Using dropdownlist with popupSettings = { appendTo: component } does not open the popup

### ISSUE THREAD

**Issue by vasilvalchanov** [telerik/kendo-angular#3614]
## I'm submitting a...

* Regression report 

## Current behavior

Using dropdownlist with popupSettings = { appendTo: component } does not open the popup.

## Expected behavior

Using dropdownlist with popupSettings = { appendTo: component } should open the popup.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-zscwrr?file=app/app.component.ts

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version 99.0.4844.51
- Firefox version 98.0
- Edge version 99.0.1150.36

System:
- TypeScript version: 4.5.5
- Node version: 14.15.5 and NPM version: 6.4.11
- Platform:   Windows

**Comment by yanmariomenev** [comment]
Hi @vasilvalchanov,

Thank you for the feedback.

Indeed it seems the behavior seems to be a bug on our side with the appendTo functionality. I will mark this issue as duplicate because another one was created to describe all the DropDowns components that are affected.
 Feel free to subscribe to the following issue: https://github.com/telerik/kendo-angular/issues/3738
