### ISSUE TITLE
<kendo-grid-command-column> can not make the "sort" to take effect

### ISSUE THREAD

**Issue by mjbin** [telerik/kendo-angular#363]
![image](https://cloud.githubusercontent.com/assets/3965629/23743758/d9f1d87c-04ec-11e7-8318-b6f6c999632d.png)
 
when i used the "kendo-grid-command-column" label, the sort didn't take effect,but the 'kendo-grid-column' label made it normal. i need help

**Comment by rkonstantinov** [comment]
I'm not sure I understood your question, could you please clarify? What you do? What is the current and what is the expected behavior? A plunkr demonstrating the issue will be appreciated.

Please note that only data-bound (those that have field option set) columns are sortable. Command column is not sortable as it is not associated with the data.
