### ISSUE TITLE
Changes in CSS are not reflected in charts

### ISSUE THREAD

**Issue by repolevedavaj** [telerik/kendo-angular#3650]
**Describe the bug**
The charts module caches all relevant CSS rules while rendering the first chart in the `ThemeService`. Changes to CSS (e.g. in case a Stylesheet is added dynamically) are therefore never taken into account even if a chart is re-created afterwards. 

**To Reproduce**
Example: https://stackblitz.com/edit/angular-ppatw7-md5xwu?file=src%2Fapp%2Fapp.component.ts

**Expected behavior**
Changes to CSS are reflected in rendered charts.

**Additional context**
We load the Kendo-UI theme stylesheet dynamically, based on the current context.

**Comment by repolevedavaj** [comment]
I understand that this is possibly a performance optimization, but I could not find any hint in the documentation for this behavior. At least there should be a possibility to clear the cache and reload the CSS rules.

**Comment by Raisolution** [comment]
Hi @repolevedavaj 

The current behavior is considered expected, because the Chart component is not aware of the dynamic styles change. As this repository is for bug reports only, please open a [support ticket](https://www.telerik.com/account/support-tickets) if further assistance is needed regarding this configuration.
