### ISSUE TITLE
Extending DialogContentBase with a directive is not possible anymore

### ISSUE THREAD

**Issue by MelvilQ** [telerik/kendo-angular#3671]
After updating kendo-angular-dialogs from 5.2.3 to 7.0.0 our app does not render anymore and we get the following error in the console:

``Error: NG0903: Directives cannot inherit Components. Directive DialogBaseComponent is attempting to extend component DialogContentBase``

DialogBaseComponent is the base class for our all our dialog components:

```typescript
@Directive() // not @Component because this is an abstract base class
export class DialogBaseComponent extends DialogContentBase implements AfterViewInit {
  // ...
}
```
There is no breaking change documented that it is not possible anymore to extend DialogContentBase like this.

What is your recommendation to resolve this issue? Do we have to use `@Component({template: ''})`? It seems to work but it looks dirty.

**Comment by preslavapetrova1** [comment]
Hi @MelvilQ, 

Migrating our packages to [Ivy](https://docs.angular.lat/guide/ivy) required all base classes that are extended by a class decorated with some Angular decorator (@Component, @Directive, etc.) to be also decorated accordingly. This is why we needed to decorate the DialogContentBase class. We chose the @Component decorator because by design the custom dialog content is meant to be a component with its own template (where the actual content is defined).

Changing the decorator of the class, extending the DialogContentBase, to @Component should resolve the described problem and allow the developer to continue using the respective custom Dialog content. The following documentation section demonstrates this approach:

https://www.telerik.com/kendo-angular-ui/components/dialogs/dialog/service/#toc-content-component
