### ISSUE TITLE
[MultiSelect] itemDisabled is not invoked for custom items

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#3714]
**Describe the bug**

1. `itemDisabled` callback is not invoked for custom added items ( not present in [data] list ) 
2. when filter does not find anything disabled item is enabled

**To Reproduce**

1. https://codesandbox.io/s/billowing-platform-h4ihdv?file=/src/app/app.component.ts
2. https://codesandbox.io/s/gallant-breeze-ywfb4n?file=/src/app/app.component.ts

**Expected behavior**

1. `itemDisabled` callback should be invoked for custom added items. 
2. disabled items should not get enabled

Broken in 
  ```
v7.0.2
  ```

**Comment by stnikolova** [comment]
The `itemDisabled` callback is specifically invoked on **list options** (ones that are part of the drop-down list), as noted in [our documentation](https://www.telerik.com/kendo-angular-ui/components/dropdowns/multiselect/disabled-items/). In order to be able to add custom items and disabled them, they should be added as part of the list options as demonstrated in this example: https://stackblitz.com/edit/angular-jsstxp
