### ISSUE TITLE
ComboBox allowCustom broken

### ISSUE THREAD

**Issue by sigVince** [telerik/kendo-angular#373]
Hello,

I have updated my kendo-dropdowns package this morning to fix https://github.com/telerik/kendo-angular/issues/368

I have updated from 0.27.0 to 0.33.1

It works well overall but I have discovered a new issue, when using allowCustom on combobox, and typing a custom text, I get an error on blur:
`EXCEPTION: Error in ./e class e - inline template:2:12 caused by: Expected initial value of type Object. See http://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/#toc-value-selection`

Plunkr here:
http://plnkr.co/edit/iLqfDHCiCV4I9Qt5oip2?p=preview

Btw, the plunker you get from the doc is broken too, but with a different error message
http://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/#toc-allow-for-custom-values

**Comment by valchev** [comment]
@sigVince 

The problem occurs because the `valueNormalizer` function is not provided. When the component operates with complex data and values, the `valueNormalizer` function is mandatory.
For more information see: http://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/custom-values/#toc-object-values

I have to admit that the error which pops up is awkward, as it does not clearly states that the configuration is invalid. We will fix this!

I was not able to spot on the broken example from the docs. I believe that the link is not correct, could you please re-send it?

**Comment by sigVince** [comment]
@valchev 

Thanks for the info about valueNormalizer. It's weird because my code worked in 0.27.0. Or at least it did not crash, maybe it failed silently and gave the illusion that it worked... I'll work on it on my side and give you feedback.

About the example, I'm talking about the basic example on the overview page : http://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/

Click on "Open as plunkr", you'll get a broken plunkr (the bug doesn't seem to be directly related to the combobox component).

**Comment by valchev** [comment]
@sigVince

We made changes in the `valueNormalizer` that are not compatible with the previous versions of the package. Since the package is still in beta version, the major version is not bumped.

The main difference is that now the `valueNormalizer` function receives `Observable<string>` as an argument and is expected to return a single normalized value wrapped as `Observable` that will be further processed by the component. The change was required in order to support scenarios where the value is normalized asynchronously.

The issue you encountered with, occurs because the "default" `valueNormalizer` logic was changed. If the `valueNormalizer` is not provided, the default one will return the string that the user entered. In this way the developers don't have to write extra code for the most basic scenario where the ComboBox is bound to a list of string values.

What happens in your case is that the default normalizer returns string while the component expects value of object type. In such scenarios the component should throw invalid configuration error, during the initialization, to notify the developer that in this scenario the `valueNormalizer` is mandatory.

For more information check the [custom values topic](http://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/custom-values/).

We will also investigate and fix the "Open as Plunkr" issue. Thanks for bringing it to our attention.

**Comment by tapopov** [comment]
Quick update. The error in Plunkr comes from the fact that the `FormsModule` is not imported and the checkbox in the example relies on it for the `ngModel` binding. Importing `FormsModule` from `@angular/forms` should fix this. It's already in our to-do list and should be fixed soon.

**Comment by sigVince** [comment]
I have updated my component with valueNormalizer and it's working now. Indeed a configuration error message would be better.

Also, I know that this is a RC version and breaking changes can occur, but it would be nice to list them in the [changelog](http://www.telerik.com/kendo-angular-ui/components/dropdowns/changelog/) (like [Angular](https://github.com/angular/angular/blob/master/CHANGELOG.md) does). I first went there when I had this issue yesterday, and read all notes between 0.27 and 0.33 but found nothing about allowCustom.

Anyway, thanks to both of you for your quick answers.

**Comment by tsvetomir** [comment]
We'll start highlighting breaking changes in the changelog and add [discussion topics](https://github.com/telerik/kendo-angular/issues?q=is%3Aopen+is%3Aissue+label%3A%22Breaking+Change%22) for them. Hopefully, this will give them better visibility.

Thanks!
