### ISSUE TITLE
All Date Inputs - Days of the week labels - broken styles

### ISSUE THREAD

**Issue by krzysztof-raciniewski** [telerik/kendo-angular#3759]
**Describe the bug**
Days of the week labels - broken styles

**To Reproduce**
1. Go to Kenod UI for Angular documentation > Date Inputs > Date Picker > Overview
2. Select Date Inputs > Date Picker > Overview
3. Click on the calendar icon

https://www.telerik.com/kendo-angular-ui/components/dateinputs/datepicker/

**Expected behavior**
Day names should be aligned

**Screenshots**
![image](https://user-images.githubusercontent.com/7010367/187933839-a4fe8546-782e-4471-8418-1a9f82016e4f.png)

**Browser**
 - All browsers

**Comment by PaskalevStoyan** [comment]
Hi @krzysztof-raciniewski,

this is a known issue and its already fixed in the dev version of the Date Inputs Package. This can be seen in our develop documentation site - https://www.telerik.com/kendo-angular-ui-develop/components/dateinputs/datepicker/ 

To obtain the development builds, refer to the following article in our documentation:

https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/

**Comment by krzysztof-raciniewski** [comment]
Thank you @PaskalevStoyan
