### ISSUE TITLE
Kendo Grid virtual scroll displays white spaces

### ISSUE THREAD

**Issue by notetosiraj** [telerik/kendo-angular#3773]
**Describe the bug**
Kendo grid displays white space on every page change scroll events

**To Reproduce**
scroll the grid to trigger next page change event .

https://stackblitz.com/edit/angular-pemkhm-kjacox?file=src%2Fapp%2Fapp.component.ts

**Expected behavior**
instead of white space ,data has to be  display

**Browser**
 - OS: [windows 10]
 - Browser [Chrome]
 - Version [105.0.5195.102]

[StickyVirtualScrollIssue.webm](https://user-images.githubusercontent.com/51027104/190614765-0fdfec6f-e471-464c-ae2b-049e15d8477b.webm)

**Comment by mbechev** [comment]
Looks relevant to https://github.com/telerik/kendo-angular/issues/3772

**Comment by slavenai** [comment]
The observed behavior is caused by a specific in the remote service used in the example (https://odatasampleservices.azurewebsites.net/V4/Northwind/Northwind.svc/). As this is a public sample service, it returns limited amount of records, and when this amount is less than the set pageSize, the described discrepancy appears. We apologize for the caused inconvenience, and will update the documentation example accordingly. Please check out the [updated demo](https://stackblitz.com/edit/angular-sd89hc-1xq6gx?file=src%2Fapp%2Fapp.component.ts).

**Comment by slavenai** [comment]
We've updated all examples that utilize the mentioned remote service, e.g.:
https://www.telerik.com/kendo-angular-ui/components/grid/scroll-modes/virtual/#toc-virtualization-with-remote-data
