### ISSUE TITLE
[DropDownList] Using getter method to set the defaultItem breaks the navigation of the component

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3808]
**Describe the bug**
When using a getter method to set the defaultItem of the component it breaks the keyboard navigation. Other DropDowns package components might also need to be checked for this behavior.

This was originally reported from the following Grid demo:
https://www.telerik.com/kendo-angular-ui/components/grid/filtering/filter-row/#toc-custom-filter-row-components

**To Reproduce**
1.  Open - https://stackblitz.com/edit/angular-t38vbj?file=src%2Fapp%2Fapp.component.ts
2.  Try to navigate the component when the popup is opened

**Comment by svetq** [comment]
The demonstrated behavior is caused due to the getter function returning new instances of the object each time it is called. (Using a function in an Angular template is not a recommended approach, indeed). Still, returning the same object instance from the function yields the expected behavior: https://stackblitz.com/edit/angular-t38vbj-2hmvv2
