### ISSUE TITLE
Dot is removed from the filter field after entering

### ISSUE THREAD

**Issue by maksymSliushchynskyiBv** [telerik/kendo-angular#3835]
## I'm submitting a...

* Bug report 

## Current behavior
Dot is instantly removed from the filter field after entering

## Expected behavior
I suppose that this is filter field validation, so maybe there is have to be bigger pause before validating

## Minimal reproduction of the problem with instructions
Steps: 
- just type "0." or "1." in filter field and dot will be instantly removed (or you can try to enter "21.35" value because it is in this list)
- if it is not reproduced just clear filter field and try again

Example:
https://angular-vmedgf.stackblitz.io

## Environment

Package versions:
  Problem is reproducible on demo site.

Browser:

- Chrome (desktop) version 106.0.5249.91 (Official Build) (64-bit)

System:
- TypeScript version: 4.8.4
- Node version: v16.17.0
- NPM version: 8.15.0
- Platform:  Windows

**Comment by maksymSliushchynskyiBv** [comment]
Thanks!
But there is one more example that also looks strange for me:
- Enter "1." (dot will be removed instantly, so now we have only "1")
- Enter dot after "1" again and now it will not be removed

Is this correct behavior?

**Comment by slavenai** [comment]
Hi @maksymSliushchynskyiBv ,

The observed behavior is expected due to the following reasons:
- When there is no initial filter value, typing `1.` will produce a FilterDescriptor by the respective field with value `1`. The Grid data will then be filtered accordingly after the default or preconfigured delay.
- The next time the user types in the input, the filter descriptor already has a value `1`, and typing `.` does not change the filter value, thus no new filter descriptor is created and the user can continue typing until the filter numeric value is different from `1`.

**Comment by HarryTrue** [comment]
> Hi @maksymSliushchynskyiBv ,
> 
> The observed behavior is expected due to the following reasons:
> 
> * When there is no initial filter value, typing `1.` will produce a FilterDescriptor by the respective field with value `1`. The Grid data will then be filtered accordingly after the default or preconfigured delay.
> * The next time the user types in the input, the filter descriptor already has a value `1`, and typing `.` does not change the filter value, thus no new filter descriptor is created and the user can continue typing until the filter numeric value is different from `1`.

Hi @slavenai,
To you first point, I guess it makes sense when Filter is used for grid itself. However, when column filter is in question, the grid data doesn't get filtered while you are typing, but only when you hit "apply" button. So it makes no sense to remove dot(.) after any delays or no delays.
