### ISSUE TITLE
The Editor toolbar state isn't being refreshed which causes UI issues

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3947]
**Describe the bug**
It seems that the toolbar doesn't update its state and that can be observed in our live examples with the bold or insert link button:

![chrome_Whvw6vFKpn](https://user-images.githubusercontent.com/49076727/224277378-71d096cb-cd27-4689-a7e0-b4788c7dd412.gif)

**To Reproduce**
1. Open:
https://stackblitz.com/edit/angular-awvjvt-pm232p?file=src%2Fapp%2Fapp.component.ts

2. Interact with the editor content to see that the state of the tooltip doesn't update correctly as shown in the above recording.

**Comment by KimBum** [comment]
This can also easily be reproduced on the [documentation page](https://www.telerik.com/kendo-angular-ui/components/editor/tools/#toc-built-in-tools) for the editor itself. Using version 12.0.0 this is also still not fixed.

**Comment by KimBum** [comment]
Some investigation on our end turned up, that things work fine, as long as you don't group the buttons of the toolbar with the respective group component. That component is needed however for proper spacing/styling, so not a fully feasible workaround.

**Comment by KimBum** [comment]
Is there any reason this is part of a "breaking change" version? There is no documentation on the official Kendo website, saying what changes I can expect from the other packages when updating 🤔

**Comment by slavenai** [comment]
Hi @KimBum ,

Since January all packages share a single Changelog and are released with an unified version. Thus, a major version in one package results in major version for all. Here is a list of all `v13.0.0` changes:

https://www.telerik.com/kendo-angular-ui/components/changelogs/kendo-angular-ui/#v13.0.0

The three separate lists are the introduced bug fixes, features and breaking changes respectively. We are currently working on adding descriptive headers above each list, similar to the ones for [v12.0.0](https://www.telerik.com/kendo-angular-ui/components/changelogs/kendo-angular-ui/#v12.0.0).
