### ISSUE TITLE
[Scheduler] Font size different than 16px cause gap

### ISSUE THREAD

**Issue by gorijordane** [telerik/kendo-angular#3969]
**Describe the bug**
When the font-size is different than 16px, in the week view, a small gap will be created, and amplified with each resource (see screenshot below)
![Sans titre](https://user-images.githubusercontent.com/78923551/230121814-9b389998-283a-4288-91b8-87eef65dd2f7.png)

**To Reproduce**
Reproduce [here](https://stackblitz.com/edit/angular-mcqdtu) with changing font-size of the scheduler in the DOM via F12.

**Expected behavior**
The scheduler to adapt its style with any font-size

**Comment by JoomFX** [comment]
I'm not able to reproduce the issue.

I tested it with different font sizes and everything works as expected.
[This Stackblitz example](https://stackblitz.com/edit/angular-mcqdtu-t7whzz?file=src/app/app.component.ts) shows that there is no gap when the font size is set to 18px.
And [this Stackblitz example](https://stackblitz.com/edit/angular-mcqdtu-ltsxwb?file=src/app/app.component.ts) shows that there is no gap when the font size is set to 22px.

It is normal to see some border misalignments if the font-size is being modified via the browser console (inspect element) because there are some places where the width of the element is being calculated dynamically and added as an inline style at load time.

![console](https://user-images.githubusercontent.com/7753940/234629020-e30fe940-2fce-4913-b7ee-4937a20a0c8c.png)
