### ISSUE TITLE
[Grid] Selecting and dragging text fires an error

### ISSUE THREAD

**Issue by georgi-sla** [telerik/kendo-angular#4004]
**Describe the bug**
When the user selects the text inside the Grid component, holds the mouse key for a little bit on the mousedown, and then tries to move the text, multiple errors are being shown on the console. 

**To Reproduce**
1. Create a simple Grid component. 
2. Select text from some of the cells in the component. 
3. Left click on the selected text and hold the left mouse key slightly longer. 
4. Try to relocate the selected text
5. Check the browser console. 

Please, check the following StackBlitz demo: https://stackblitz.com/edit/angular-hs5izn, or any other Grid demo.

**Expected behavior**
Dragging the text in this case should be unsuccessful but no errors should be thrown on the console. 

**Screenshots**
![image](https://github.com/telerik/kendo-angular/assets/108671673/7690ef62-2394-4631-9e3b-9819a7d47dcf)

To gain a better understanding of the exact behavior, please check out the attached screen recording.

https://github.com/telerik/kendo-angular/assets/108671673/8e6001ce-a797-4b0e-83e6-8c9694e29507

**Comment by sky0matic** [comment]
Already told support about this, but this also happens when dragging a row from a grid to another one using Telerik's knowledge base here : https://www.telerik.com/kendo-angular-ui/components/knowledge-base/drag-drop-between-grids/

Which results in the drop taking a lot of time to happen, because of all the errors popping up..

**Comment by slavenai** [comment]
Issue is fixed in v13.0.0 of the Grid package.
