### ISSUE TITLE
[Label] Wrong position for label in horizontal form

### ISSUE THREAD

**Issue by schreibse** [telerik/kendo-angular#4059]
**Describe the bug**
Label not displayed correctly for horizontal forms if content not provided with text property

**To Reproduce**

https://angular-rbpmgb.stackblitz.io

https://stackblitz.com/edit/angular-rbpmgb?file=src%2Fapp%2Fvertical-form.component.ts

see example horizontal-form, label for 'Full name'.

`<kendo-label [for]="userName">Username</kendo-label>`
Label does not have correct position

Compare with other labels that use the text input, e,g, Card number:

`<kendo-label [for]="email" text="Email" [optional]="true"></kendo-label>`
Card Number has correct position

![image](https://github.com/telerik/kendo-angular/assets/30500338/788fb73e-388a-4755-843f-a72847b38292)

**Expected behavior**
Position of label is correct for horizontal forms if content is not provided by text input property

**Screenshots**

**Browser**
 - OS: Windows 11
 - Browser Firefox
 - Version 115.0.2 (64-bit)

**Additional context**
Progress packages 13.2.0

Temp fix:
.k-form-horizontal kendo-label label {
  margin-top: -18px;
}

**Comment by JoomFX** [comment]
If a `label` needs to be rendered via the Kendo Label component, then the `text` property has to be used. Otherwise an empty `label` is being rendered, hence the issue you experience:

![label](https://github.com/telerik/kendo-angular/assets/7753940/a0dbab2f-2c5a-4aa3-8e3d-27c43be2372f)

As this repository is for bug reports only, I am closing this issue. Please use our [support system](https://www.telerik.com/account/support-tickets) if you need any further assistance with specific configuration or setup.
