### ISSUE TITLE
[Scheduler] eventClass input of the Scheduler causes performance issues

### ISSUE THREAD

**Issue by shaizel** [telerik/kendo-angular#4094]
**Describe the bug**
In the Scheduler component, the only way to assign a class to events is using the eventClass input, accepting a function.
This creates a major performance issue since this function is called repeatedly for all the events currently on the scheduler with every mouse move or click.

**To Reproduce**
See the example for using the eventClass input.
If you place a console log inside the function, it's being called hundreds of times when the mouse is moved over the scheduler.

**Expected behavior**
There should be a better way to assign classes to events without using a function in the template.
For instance, an input that accepts a name of a field from the event object that contains the class name that should be assigned to it.

**Screenshots**
Having only 3 appointments on the scheduler and moving the mouse over the scheduler several times gets the following results:
![image](https://github.com/telerik/kendo-angular/assets/25416352/83c2cad6-cfd4-4bb2-bf07-3d007347dd6c)

**Browser**
All

**Comment by svetq** [comment]
Hi, @shaizel, it is our standard practice to allow developers to set dynamic classes at elements to which they don't have access. For this purpose, a callback is needed to allow access to all properties of the corresponding event data item. Indeed, we could think of an enhancement so that the eventClass callback is executed once per event or when a property of the event data item is changed.

As this repository is for bug reports only, we are closing this thread. If you need assistance with specific scenario setup or component configuration, please open a ticket in our [support system](https://www.telerik.com/account/support-tickets).

If you would like to suggest an enhancement, please use our Feedback Portal to log feature requests with brief explanation of the use case and what the benefit of the suggested improvement would be:

https://feedback.telerik.com/kendo-angular-ui/
