### ISSUE TITLE
Unable to select any option in kendo-dropdownlist with grouped data

### ISSUE THREAD

**Issue by jivkopiskov** [telerik/kendo-angular#4109]
**Describe the bug**
When using a getter for data property in kendo-dropdownlist, which changes references between calls, you are unable to select any dropdown item. This behavior can only be reproduced when using grouped data.

**To Reproduce**
https://codesandbox.io/s/eager-napier-sdxthd?file=/src/app/app.component.ts

**Expected behavior**
You should either get an error (or warning) or it should work like in the non-grouped data case

**Browser**
 - OS: Windows
 - Browser Chrome
 - Version (latest, 13.5.0)

**Comment by svetq** [comment]
The demonstrated behavior is expected and indeed caused due to the getter function returning new instances of the array each time it is called. (Using a function in an Angular template is not a recommended approach, indeed). Returning the same array instance from the function yields the expected behavior:
https://codesandbox.io/s/modest-curran-dwrpsz?file=/src/app/app.component.ts

The same behavior is observed when using not grouped data.
