### ISSUE TITLE
Sparkline Chart tooltips flickering when browser is zoomed out

### ISSUE THREAD

**Issue by pferencgit** [telerik/kendo-angular#4120]
**Describe the bug**
When browser is zoomed out Sparkline Chart tooltips are flickering while moving the mouse over them.
Probably connected to the flickering problem, the tooltip issue also prevents click events from firing over the sparkline.

**To Reproduce**
https://codesandbox.io/p/sandbox/elated-lehmann-q4rdfh

1. Open the above sandbox link in Chrome, Firefox or Opera
2. Open the application test page in a new window
3. Zoom out the browser to 67% or 50%
4. Reload the page, keeping the zoom level reduced
5. Move your mouse over the sparkline chart and see the tooltips flickering
6. If the flickering issue is not reproduced, further reduce the zoom level and repeat steps 4 and 5
7. In the sandbox example there's a click event handler attached to the SPAN containing the sparkline, incrementing a counter
8. When the tooltip flickering is reproduced, see how the click event is not always fired when clicking on the sparkline chart

**Expected behavior**
Tooltips and mouse events should work the same regardless the browser zoom level.

**Screenshots**

**Browser**
 The issue was tested and reproduced with the above method in the latest versions of Chrome, Firefox and Opera.

**Comment by yanmariomenev** [comment]
The flickering seems to be caused due to the border styles added to the Chart component:
```
<kendo-sparkline
        [data]="data"
        style="width: 150px; height: 20px; border: 1px black solid;"
```
To avoid such flickering, the developer would need to add the border to an outer element or the [chartArea](https://www.telerik.com/kendo-angular-ui/components/charts/api/SparklineComponent/#toc-chartarea) property of the Sparkline component:

https://codesandbox.io/s/agitated-surf-kj42cg?file=/src/app/app.component.ts

```
<kendo-sparkline
        [chartArea]="{ border: { dashType: 'solid', width: 1 } }"
        [data]="data"
```
