### ISSUE TITLE
[Grid] Selection directive's selectedKeys property not updating

### ISSUE THREAD

**Issue by ehayn-sei** [telerik/kendo-angular#4122]
**Describe the bug**
If I'm using a selection directive I can see changes being made via selectedKeysChange. However, if I look directly at the directive's selectedKeys property, it always seems to be empty.

**To Reproduce**
Use a kendo grid and apply a selection directive to it. Attempt to read from the directive's selectedKeys property directly after a selection change.

https://stackblitz.com/edit/angular-3uuae8-p1xab3?file=src%2Fapp%2Fapp.component.ts

**Expected behavior**
I'd expect the selectedKeys property on the directive to update as selections are made.

**Browser**
 Chrome

**Comment by slavenai** [comment]
Hi @ehayn-sei ,

This behavior is expected and by design. The Grid emits a [`selectedKeysChange`](https://www.telerik.com/kendo-angular-ui/components/grid/api/SelectionDirective/#toc-selectedkeyschange) event so mutating the array is not expected. Getting the updated selection will require the use of two-way binding.
