### ISSUE TITLE
[Dialog] Overlay

### ISSUE THREAD

**Issue by gultyayev** [telerik/kendo-angular#4136]
There is a problem with current Dialog. When it's used as a component - it inserts the content right in the place where the `<kendo-dialog>` is defined. However, this causes overlap issues. These are easily solved by having the dialog attached next to the app root node.

There is a possibility to define a `kendoDialogContainer` to fix the above mentioned issue. But it requires using a service to utilize the container which makes it sorts of inconvenient to use as I have to replicate the rest of the component's behaviors.

It would be nice if KendoDialogComponent would be attached in a separate DOM node next to the app root just like Angular Material/CDK overlays do.

Or, at least have an ability to set `[useContainer]="true"` so that the component would use the `kendoDialogContainer` internally.

**Comment by Raisolution** [comment]
Hello @gultyayev 

This looks like a similar request to https://github.com/telerik/kendo-angular/issues/1403. The described behaviour is by design in the Dialog component.

As the current repository is for bug reports only, please log this as a feature request in our [feedback portal](https://feedback.telerik.com/kendo-angular-ui).
