### ISSUE TITLE
Piping Does Not Work In kendoGridEditTemplate

### ISSUE THREAD

**Issue by yanbu0** [telerik/kendo-angular#416]
Piping a date to format it does not work inside a kendoGridEditTemplate.  See attached pic.  Note that it does work inside a kendoGridCellTemplate, but mixing edit and cell templates inside the same grid gives unexpected results.
![image](https://cloud.githubusercontent.com/assets/26099646/24272350/cd8c5f54-0fd1-11e7-940b-39f8a27a0921.png)

Code:
![image](https://cloud.githubusercontent.com/assets/26099646/24272269/582742e2-0fd1-11e7-9c7f-88c072ddaf2a.png)

**Comment by yanbu0** [comment]
I worked around this by using Reactive forms editing and setting the two other columns to non-editable, but not sure that will always be possible.

**Comment by rusev** [comment]
We are not sure how to replicate this behavior. I've created a quick example using both [kendoDate pipe](http://www.telerik.com/kendo-angular-ui/components/internationalization/api/DatePipe/) and [Angular data pipe](https://angular.io/docs/ts/latest/api/common/index/DatePipe-pipe.html) and seem to work properly.

http://plnkr.co/edit/tYcB68zDVLbrHtcDhBXJ?p=preview

Can you modify the example so that it replicates the behavior you describe?

**Comment by yanbu0** [comment]
I think this was my fault.  Had a weird combination of things going on in my grid, including a non-editable column with only a kendoGridEditTemplate template.  I think this is working as it should.  My bad!
