### ISSUE TITLE
MultiColumnComboBox dropdown displays in the incorrect position

### ISSUE THREAD

**Issue by schase-nfocus** [telerik/kendo-angular#4170]
**Describe the bug**
Using Kendo Angular components to supplement Angular Material. When using the MultiColumnComboBox within an Angular Material dialog box opened from an element in the viewport when the viewport is scrolled down (for example, Y position is > 0), the dropdown values display in the wrong location due to positioning.

**To Reproduce**

Here is a StackBlitz example:  https://stackblitz.com/edit/angular-vuvdew?file=src%2Fapp%2Fapp.component.ts

  1. Use the example from https://www.telerik.com/kendo-angular-ui/components/dropdowns/multicolumncombobox/value-binding/
  2. Open it in StackBlitz by using the **OPEN IN STACKBLITZ** button.
  3. Add Angular Material + CDK and Theme
  4. Position a button far down in the viewport so you have to scroll to get to it.
  5. Have the button (click) event open a material dialog.
  6. The dialog contains the example from Step #1.
  7. My example shows 2 buttons where each position opened from the combobox fails to display in the correct position.

**Expected behavior**
The popup from the dialog containing the values should appear in the correct position. In this case, simply below the combobox.

**Screenshots**

![image](https://github.com/telerik/kendo-angular/assets/106712531/cfde56fc-89bb-49d5-b7bf-0223d1838a24)

**Browser**
 - OS:  Windows 10
 - Browser Chrome 119

**Comment by stnikolova** [comment]
Hi @schase-nfocus,

Sometimes using other third-party libraries can cause random UI issues with our components. Please use the [popupSettings](https://www.telerik.com/kendo-angular-ui/components/dropdowns/api/DropDownListComponent/?_gl=1*9s85by*_ga*OTMyODgyNTY4LjE2NzM5NDkwNzA.*_ga_9JSNBCSF54*MTcwNDI2OTQyNy42ODYuMS4xNzA0Mjg5MDkwLjYwLjAuMA..*_gcl_au*MzMzOTU5ODA0LjE2OTY4MjU3NjU.#toc-popupsettings) `appendTo` option and bind it to the component. That will avoid the detaching in your specific use case scenario.

https://stackblitz.com/edit/angular-vuvdew-yg9xgy?file=src%2Fapp%2Fapp.component.ts

Another option would be to use our [Dialog or Window](https://www.telerik.com/kendo-angular-ui/components/dialogs/get-started/) component instead of the Material version.

If you have any questions related to customizing our components to fit custom scenario requirements, please open a ticket in our [support system](https://www.telerik.com/account/support-tickets).

Thank you in advance.
