### ISSUE TITLE
MultiSelect won't scroll until an item is selected when used within a kendoGridFilterCellTemplate

### ISSUE THREAD

**Issue by jstransparity** [telerik/kendo-angular#4178]
**Describe the bug**
When using a customised KendoMultiSelect within a grid filter cell template, the dropdown list won't scroll until an item has been selected.

**To Reproduce**
Run the following stackblitz and try to scroll down in the Category filter.
https://stackblitz.com/edit/angular-vbfe4a-vuuqbg

**Expected behavior**
The dropdown list should scroll whether an item is selected or not.

**Additional context**
We are implementing the custom multiselect within the filter cell template as we want to trigger the filterChange event only when the dropdown is closed. When we tried this directly within the filter cell template, it broke change detection.

**Comment by stnikolova** [comment]
Hi @jstransparity,

The described behavior is not an issue with the Kendo UI for Angular Multiselect component, but rather with the customizations in the provided example, particularly the `selectedValues` getter. It seems that the problem is caused because the value is constantly re-evaluated and the content is re-rendered.

If you need help or have any questions related to customizing our components to fit custom scenario requirements, please open a ticket in our [support system](https://www.telerik.com/account/support-tickets).

Thank you in advance.
