### ISSUE TITLE
[DropDownList] Cannot clear the component value when valuePrimitive is set to true

### ISSUE THREAD

**Issue by georgi-sla** [telerik/kendo-angular#4203]
**Describe the bug**
Currently, when the DropDownList component is bound to complex data and the valuePrimitive property is set to true, trying to programmatically reset the value does not clear the value in the DropDownList.

**To Reproduce**
1. Create a DropDownList component.
2. Set the valuePrimitive property to true.
3. Programmatically clear the value of the component.

Please, check out the following StackBlitz demo: https://stackblitz.com/edit/angular-gue7wn-ethzdj

**Expected behavior**
 Programmatically resetting the value that is bound to the DropDownList should reflect the changes in the component.

**Comment by tswetti** [comment]
The [value](https://www.telerik.com/kendo-angular-ui/components/dropdowns/api/DropDownListComponent/#toc-value) in the StackBlitz example is not cleared programmatically because the new value ('') is not present in the data. To clear the value, set it to `null` - https://stackblitz.com/edit/angular-gue7wn-a8wbyn?file=src%2Fapp%2Fapp.component.ts
