### ISSUE TITLE
 grid filter input for decimals removes dot(.) sometimes

### ISSUE THREAD

**Issue by HarryTrue** [telerik/kendo-angular#4253]
Typing a decimal number in a grid filter input for number type removes dot sometimes.

Can be reproduced in this grid: https://www.telerik.com/kendo-angular-ui/components/grid/filtering/filter-menu/

**Comment by slavenai** [comment]
Hi @HarryTrue ,

This behavior is expected and by design. The Grid waits 500ms before building the filter descriptor and executing the filter operation. To customize the default delay, use a filter template with [NumericFilterCellComponent](https://www.telerik.com/kendo-angular-ui/components/grid/api/NumericFilterCellComponent/) or [NumericFilterMenuComponent](https://www.telerik.com/kendo-angular-ui/components/grid/api/NumericFilterMenuComponent/) and set their [filterDelay](https://www.telerik.com/kendo-angular-ui/components/grid/api/NumericFilterCellComponent/#toc-filterdelay) property accordingly.

This repository is for bug reports only. If you need assistance with specific scenario setup or component configuration, please open a ticket in our [support system](https://www.telerik.com/account/support-tickets).

**Comment by HarryTrue** [comment]
@slavenai,

How can filter be executed before clicking on a "filter" button to apply the filter?

![reen-recording-3-26-2024-6-57-30-pm](https://github.com/telerik/kendo-angular/assets/54777563/aaa1d19b-c0f3-461c-b39b-4978c5e5ce30)
