### ISSUE TITLE
[Scheduler] Events render incorrectly when kendoSchedulerMonthDaySlotTemplate and kendoSchedulerMultiWeekDaySlotTemplate are used

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#4269]
**Describe the bug**
It seems that the events take into consideration both template heights and render the events based on that high. This will result in an undesired rendering where the events are no longer visible or in the wrong position. For the rest of the slot templates that render in other views, the events are rendered correctly.

**To Reproduce**
Open the following example and adjust the height inside the slot template:
https://stackblitz.com/edit/angular-qv9ruh-vabkry?file=src%2Fapp%2Fapp.component.ts
```
            <ng-template kendoSchedulerMonthDaySlotTemplate let-date="date">
                <div class="test month" style="height: 50%">{{ date | kendoDate }}</div>
            </ng-template>
```

**Expected behavior**
The events rendering should not rely on the template dimensions.

**Comment by ldamis** [comment]
It's not about time to consider to solve it?
It has been reported 2 months ago.

**Comment by tswetti** [comment]
The `kendoSchedulerMonthDaySlotTemplate` positions the events below it by design. This ensures the date remains clearly visible. The behaviour can be observed in other Schedulers and Calendars, such as Google Calendar and Microsoft Outlook Calendar. To prevent the template from pushing the events down, wrap its content in a `<div>` element with `height: 0`:
https://stackblitz.com/edit/angular-qv9ruh-ksxthn?file=src%2Fapp%2Fapp.component.ts
