### ISSUE TITLE
Grid column width attribute

### ISSUE THREAD

**Issue by simon11196** [telerik/kendo-angular#427]
Is there a way to use 'em' instead of 'px' in the width attribute?

Currently, we have to set the style, the header style and the footer style attribute.

Is there a way to use only one attribute for header-style, footer-style and style attribute?
current version:

    <kendo-grid-column title="ID" 
        [style]="{'width': '10.0em'}" 
        [headerStyle]="{'width': '10.0em'}" 
        [footerStyle]="{'width': '10.0em'}">
    </kendo- grid-column>

suggestion:

    <kendo-grid-column title="ID"
        [width]="{'width': '10.0em'}">
    </kendo- grid-column>

**Comment by gyoshev** [comment]
Currently the `width` of the column does not take units other than pixels, since it affects the table width when a column is locked. However this can be resolved by using calculated CSS widths like `calc(100px + 10em)`. If this does not cause any problems with the grid layout, it is an enhancement worth considering.

**Comment by tsvetomir** [comment]
There are no plans for accepting units other than pixels at the moment. The values are used in internal calculations and this is unlikely to change.
