### ISSUE TITLE
Vulnerability in pdfjs-dist affecting @progress/kendo-angular-pdfviewer

### ISSUE THREAD

**Issue by Robhox** [telerik/kendo-angular#4377]
Hello,

I am encountering a high severity vulnerability issue in the pdfjs-dist package, which is a dependency of @progress/kendo-angular-pdfviewer.

**Vulnerability Details**

Package: pdfjs-dist
Affected versions: <=4.1.392
Severity: High
Issue: PDF.js is vulnerable to arbitrary JavaScript execution upon opening a malicious PDF.

**Dependency Chain**

@progress/kendo-angular-pdfviewer
    Depends on: @progress/kendo-pdfviewer-common
        Depends on: pdfjs-dist (vulnerable versions)

**Reproduction Steps**

Install @progress/kendo-angular-pdfviewer in a project.
Run npm audit to see the vulnerability report.

**Expected Behavior**

A resolution to the vulnerability, either by updating the pdfjs-dist package to a non-vulnerable version or by removing the dependency if it is no longer necessary.

**Environment**

Node version: v18.18.0
npm version: 10.8.2
@progress/kendo-angular-pdfviewer version: 16.5.0

Thank you for your attention to this matter. Please let me know if further information is required.

**Comment by yanmariomenev** [comment]
Our team is aware of the vulnerability and in version [16.0.0](https://www.telerik.com/kendo-angular-ui/components/changelogs/kendo-angular-ui/#v16.0.0) of our components the following workaround was implemented:
```
    let params: DocumentInitParameters | TypedArray | ArrayBuffer = {
        verbosity: 0
        isEvalSupported: false
    };
```
Which is provided in - https://github.com/advisories/GHSA-wgrm-67xf-hhpq

Our team is also working on updating pdfjs to a version above 4.1.392, but there are some breaking changes and it will take a bit of time to implement the newer version.

I will be closing this issue due to the workaround implemented in version 16.

**Comment by yanmariomenev** [comment]
I will reopen this thread as a place for people to subscribe and receive updates on which Kendo UI for Angular version includes a PDF.js version above 4.1.392.

**Comment by Raisolution** [comment]
`pdf-js` version has been updated in the latest dev version of package in order to mitigate the vulnerability.

The fix will also be included in the next official release.
