### ISSUE TITLE
Calendar: Calendar stops scrolling in specific scenarios

### ISSUE THREAD

**Issue by EricSch** [telerik/kendo-angular#439]
This is a strange behavior, which we have in our app, but I couldn't reproduce it in a stripped down Angular app.

We have an Calendar inside a popup. It works as expected when the value isn't set. As soon the value is saved and set as [value], the calendar stops scrolling, I can't change the month, scrolls only around the 'value'-date. We are using the latest calendar version.

```
    <div class="input-group">
        <input type="text" [id]="name" [value]="formattedValue" class="form-control" readonly [placeholder]="placeholder" #datepicker (click)="toggle()"/>
            <span class="input-group-addon gemo icon-arrow-down3 cursor-pointer" (click)="toggle()"></span>
    </div>
    <kendo-popup [id]="name" *ngIf="show" [anchor]="datepicker" [animate]="false">
        <kendo-calendar [value]="value" [disabled]="disabled" (valueChange)="handleCalendarChange($event)"></kendo-calendar>
    </kendo-popup>

    public get value(): Date {
        if (!this.control) {
            return null;
        }

        let currentValue = this.control.value;
        if (!DateUtilities.isValidDate(currentValue)) {
            return null;
        };

        return new Date(currentValue);
    }
```
I attached a video to see the behavior.
[2017-03-31_14-10-30.zip](https://github.com/telerik/kendo-angular/files/885538/2017-03-31_14-10-30.zip)

Do you have any idea? A hint how to debug or what to check?

**Comment by ggkrustev** [comment]
@EricSch, indeed the described behavior is quite strange. I'm also out of ideas what could cause such erroneous behavior.

The best thing that I could suggest is to create a simple plunker with the custom functionality and then start adding the custom code/CSS from your application until the calendar breaks. Thus we will be able to review the repro demo and find a fix for the depicted issue.

**Comment by EricSch** [comment]
Like to share my findings. After stripping down the project, I found the problem.

```
    public get value(): Date {
        if (!this.control) {
            return null;
        }
        let currentValue = this.control.value;
        if (!DateUtilities.isValidDate(currentValue)) {
            return null;
        };
        return new Date(currentValue);
    }
```
This it's the property which I bind to the value property of the kendo-calendar. As return value, I return always a new Date object.  It seems, this triggers always a new binding, even when the currentValue hasn't changed.

**Comment by ggkrustev** [comment]
@EricSch, indeed setting a new instance of the same date will always trigger a new binding. Basically, the change detector of the component compares the values by reference, which in this case is new.
I'm not sure how this affects the calendar though. I'll really appreciate a runnable demo in this case.

**Comment by EricSch** [comment]
@ggkrustev  My intention was to convert the control value, if it would be a string. And I have a demo, but prefer not to post here. Other way for sending it?

**Comment by ggkrustev** [comment]
@EricSch, you can try to open a support ticket within our (Telerik) ticketing system and post the project there. It will be visible only to Telerik employees there.

**Comment by EricSch** [comment]
@ggkrustev  Ok, I uploaded the project, Issue 1102213.

**Comment by ggkrustev** [comment]
@EricSch, thanks, I'll continue the discussion there.

**Comment by ggkrustev** [comment]
Hi @EricSch,

*This is a quote from the answer in the support thread.*

Indeed, the widget becomes unresponsive once value is selected. This is caused by the `value` getter, which returns new instance every time. The instance will force the Angular to re-set the component value, which in turn resets scroll position.

As you probably know, the Angular zone listens to many events (scroll is one of them) and once they are triggered, a new change detection cycle is run. In other words on calendar scroll, the Angular performs a check, calls `value` getter, gets new instance and resets Calendar value, which in turn tries to return the initial scroll position.

The solution is to return the `control.value` (the same instance) directly. 

    public get value(): Date {
    if (!this.control) {
        return null;
    }
 
    let currentValue = this.control.value;
    if (!InputDatePickerComponent.isValidDate(currentValue)) {
        return null;
    };
 
    **return currentValue;**
    }

This will help the Angular to determine that there is no change and hence keep Calendar unchanged too. Please keep in mind that the Calendar will clone the passed date to avoid mutating the passed instance. That being said, you shouldn't be worried to pass the instance directly.

As a side note, the `value` getter is called on every scroll. Hence I would suggest you to extract the logic somewhere else and keep the `value` just a simple Date property.

**Comment by EricSch** [comment]
Hi @ggkrustev, thank you for this comprehensive answer. Glad the problem is identified and solved
