### ISSUE TITLE
[Dropdowns] PopupSettings width/height does not work

### ISSUE THREAD

**Issue by PeterStaev** [telerik/kendo-angular#4414]
### Description

Setting the drop down's popup settings width/height to a fixed value does change the popup at all. Seems the values are completely ignored. Seems the issue is related to all similar widget (experience the problem for both DropDownList and Multiselect)

### Steps To Reproduce

https://stackblitz.com/edit/angular-w7k58q?file=src%2Fapp%2Fapp.component.ts%3AL9

### Actual Behavior

Popup is the default width/height. 

### Expected Behavior

Popup is resized based on the set values. 

### Browser

Chrome

### Browser version

latest

### OS type

Windows, MacOS

**Comment by tswetti** [comment]
Hi @PeterStaev,

The width of the Popup does not change in the provided example because it is smaller than the min-width, which is the width of the DropDownList. To be able to set smaller values, reduce the [min-width](https://developer.mozilla.org/en-US/docs/Web/CSS/min-width) CSS property of the [kendo-popup](https://www.telerik.com/kendo-angular-ui/components/popup/api/popupcomponent).

The height of the Popup does not change visually because of the height of the list. Set the [listHeight](https://www.telerik.com/kendo-angular-ui/components/dropdowns/api/dropdownlistcomponent#listheight) property as well to modify the list.

Please see the following StackBlitz example that demonstrates both suggestions:
https://stackblitz.com/edit/angular-w7k58q-5snqb5?file=src%2Fapp%2Fapp.component.ts

For assistance with implementing specific scenarios or configurations, please open a [support ticket](https://www.telerik.com/account/support-tickets).

Thank you for your feedback. We will work on improving our documentation about the popupSettings.
