### ISSUE TITLE
How to add a gradient color to the area chart.

### ISSUE THREAD

**Issue by ShefaaAbed** [telerik/kendo-angular#4455]
Hello, I try to add a gradient color like this:
linear-gradient(98.3deg, rgb(0, 0, 0) 10.6%, rgb(255, 0, 0) 97.7%);
to my kendo area chart but it does not work, so any help please?

    <kendo-chart-series>
      <kendo-chart-series-item
        type="area"
        [data]="[56, 140, 195, 46, 123, 78, 95]"
        [line]="{ style: 'smooth', width: 4, color: '#8FD458' }"
      >
      </kendo-chart-series-item>
    </kendo-chart-series>

**Comment by mbechev** [comment]
Hi @ShefaaAbed,

Since this repository is dedicated solely to bug reports, please open a  [support ticket](https://www.telerik.com/account/support-tickets) if you need assistance with specific scenarios or configurations. The support team is available and ready to help troubleshoot or provide guidance tailored to your needs
