### ISSUE TITLE
Dropdown with OnPush detection strategy doesn't close when clicked outside

### ISSUE THREAD

**Issue by jvielrco** [telerik/kendo-angular#447]
Hi,

I have an issue when I set the detection strategy to OnPush, the dropdown doesn't close when I click anywhere outside the dropdown.
Plunkr : http://plnkr.co/edit/AMZ9UjABUpFEK9ku5ZCG?p=preview

**Comment by valchev** [comment]
Hi @jvielrco 

This is a known scenario. Currently the components that are part of the dropdowns package does not work well with the OnPush strategy because they modify their state internally. For example the open/close state of the popup is changed inside the component.

One possible solution is to manually close the popup. In the next few days we will provide a `blur` event that can be used to detect when the popup should close.

I will investigate further the behaviour with OnPush detection strategy, but at present I cannot commit if and when we will be able to provide support for it.

**Comment by tsvetomir** [comment]
@Birxdk reported an issue with the selected value as well:

> Hi,
For the DropDownList, When setting the to: ChangeDetectionStrategy.OnPush
The selected value from the dropdown isn't set until a second click on the page.
Example:
http://plnkr.co/edit/bfzcJnzBPvY1I3wx6nJe

**Comment by jvielrco** [comment]
Hi, do you have a better idea now, when you will eventually support OnPush strategy ?

**Comment by siyka-marinova** [comment]
Fix is available now in kendo-angular-dropdowns v.1.1.2
