### ISSUE TITLE
API for grid loading indicator

### ISSUE THREAD

**Issue by simon11196** [telerik/kendo-angular#510]
Hello,
is there a way to access the grid component loading indicator?

![image](https://cloud.githubusercontent.com/assets/21359517/25609440/95594d8c-2f1f-11e7-8329-2edd00dadd94.png)

**Comment by tsvetomir** [comment]
What do you mean by access? Do you want to use this loading indicator outside the grid?

**Comment by simon11196** [comment]
I want to trigger the pdf exporting state (when its locked and loading) manually for other operations.

**Comment by tsvetomir** [comment]
Thanks for the clarification. We'll consider adding an API for that.

@rkonstantinov do you think this should be an

**Comment by simon11196** [comment]
Hello, are there any updates?

**Comment by Hemadri-befree** [comment]
Hello ,
How to add loading indicator in grid??

**Comment by tsvetomir** [comment]
No updates yet, but this is something we're looking to solve soon after the January release.

**Comment by Hemadri-befree** [comment]
hello,
Angular 2, In grid how to column recordable?? means drag and drop columns (rearrangement).

**Comment by tsvetomir** [comment]
The [Column Reordering](https://www.telerik.com/kendo-angular-ui-develop/components/grid/columns/reordering/) feature has been published in the develop channel. :beers: go to @rusev

**Comment by Hemadri-befree** [comment]
can't bind to 'reorderable' since it isn't a known property of 'kendo-grid'.
see attachment 
![error](https://user-images.githubusercontent.com/30682945/34636426-f7ec3aa2-f2c6-11e7-80ea-962106191c59.png)

**Comment by tsvetomir** [comment]
You need to be using the [dev build](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) to get the column reordering feature.

**Comment by Hemadri-befree** [comment]
still, it's not working. - 'reorderable' properties not working...
**error:** Can't bind to 'reorderable' since it isn't a known property of 'kendo-grid'.
1. If 'kendo-grid' is an Angular component and it has 'reorderable' input, then verify that it is part of this module.
2. If 'kendo-grid' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this mess

**Comment by Hemadri-befree** [comment]
Hell,
Hoe to change my grid and filter message display

**Comment by tsvetomir** [comment]
@Hemadri-befree this issue tracker is for logging defects and suggestions. Please open a support ticket for questions regarding the component usage.

**Comment by anagram92** [comment]
"@tsvetomir do you think it's better to control the loading indicator with a property or a method?"

This would be the best solution since is very flexible for us users. It would be even more awesome if it was possible to make it at a single row level too, for example, if you click on a button/check box to edit the row, and the row showed a loader during the request process.

**Comment by simon11196** [comment]
Are there any updates?

**Comment by tsvetomir** [comment]
The latest versions introduce a [loading](https://www.telerik.com/kendo-angular-ui/components/grid/api/GridComponent/#toc-loading) property to control the built-in loading panel. See [Data Binding Basics](https://www.telerik.com/kendo-angular-ui/components/grid/data-binding/) for an example.
