### ISSUE TITLE
routerLink support/extended properties to panel bar item model

### ISSUE THREAD

**Issue by whizkidwwe1217** [telerik/kendo-angular#54]
Do you have plans to support routerLink in a panel bar when items are added programmatically? I tried implementing the PanelbarItemModel with new properties but these properties were not carried over to the arguments that are passed to the **onChange** event. See images below:

![image](https://cloud.githubusercontent.com/assets/1977391/19380265/08ba8eec-9229-11e6-86f7-c2962992f18e.png)

![image](https://cloud.githubusercontent.com/assets/1977391/19380334/6bd1b4ce-9229-11e6-94fb-934907eddddd.png)

![image](https://cloud.githubusercontent.com/assets/1977391/19380398/baa69da8-9229-11e6-9b49-f2a0a3817755.png)

**Comment by vladimirivanoviliev** [comment]
We will try including this property before the first official release. Thank you for your feedback.

**Comment by tsvetomir** [comment]
The **routerLink** property is supported on the PanelBar items. See [the Routing demo](http://www.telerik.com/kendo-angular-ui/components/layout/panelbar/routing/).

**Comment by saluqi** [comment]
This is still a problem. I can set the routerLink only in the html. If I use a query to populate the panel bar items, they use the PanelBarItemModel class which does not have a routerLink property.

This is a snippet of code from [https://www.telerik.com/kendo-angular-ui/components/layout/panelbar/data-binding/](url):

`private queryItems(): void {
        this.http
            .get(`${this.BASE_URL}/Categories`)
            .pipe(map(response => response['value']))
            .subscribe(categories => {
                this.categoriesView = categories.map(item => {
                    const data = <PanelBarItemModel>{
                        title: item.CategoryName,
                        id: item.CategoryID,
                        children: []
                    };

                    this.queryChildItems(item.CategoryID)
                        .subscribe(products => {
                            data.children = products.map(product => {
                                return <PanelBarItemModel>{ title: product.ProductName };
                            });
                        });

                    return data;
                });
            });
    }`

When I look at the definition of PanelBarItemModel, there is no routerLink property.

Using the expand event doesn't work either, because again it passes the same PanelBarItemModel object that does not have a routerLink.
