### ISSUE TITLE
Dialog is not positioned correctly 

### ISSUE THREAD

**Issue by consigliory** [telerik/kendo-angular#574]
I just clean install dialog packages 

    "@progress/kendo-angular-buttons": "^1.0.0",
    "@progress/kendo-angular-dateinputs": "^1.0.1",
    "@progress/kendo-angular-dialog": "^1.0.0",
    "@progress/kendo-angular-dropdowns": "^1.0.8",
    "@progress/kendo-angular-inputs": "^1.0.2",
    "@progress/kendo-angular-intl": "^1.0.0",
    "@progress/kendo-angular-l10n": "^1.0.0",
    "@progress/kendo-theme-default": "^2.37.0",

and dialog is out of screen.  
We are currently considering to get commercial license of kendo but this kind of issues is disturbing. 
On website is says that kendo angular is production ready. This kind of issues says opposite. Does your team even test it before releasing next builds? How can we make sure that it is stable build error free at least this kind of error free. I found simular issue and one of suggestion was to look at theme builder and it is fine there. But it is not fine there. It is located in wrong place. Do you have any automated tests?

**Comment by gyoshev** [comment]
@consigliory We could not reproduce it in the latest versions of the packages, as shown in [this plunkr snippet](http://plnkr.co/edit/1jQBAlAfCguhpn0ewZTn?p=preview). There has been a similar problem caused by a version mismatch between the Dialog component and the theme version, which has been long resolved, and is pending in a ThemeBuilder update.

If the problem persists, please provide a sample that reproduces the problem.

**Comment by consigliory** [comment]
you cannot reproduce it in plunker because it does not preview as mobile device (ios). But it was and still is an issue which you can easily reproduce on your demo site if click on bottom of page was it helpful and choose no. then it will come with dialog and this dialog does not feet into the screen. Same issue on theming app you implemented. So there is no much effort you need to do to find this issue. If it was opensource project this kind of issues is accepted but this is commercial product. So all my questions is still open. The library you provide looks like have tons of useful controls but if with each next release you will introduce that level of bugs controls not useful and is liability (each release we have to wait for fixes and cannot trust that is it still works). css styles for popup is not rocket science and responsive is a must. So that is why I asking about automated tests and fixed versions so we can trust that this release from kendo is minor and no breaking changes should be there.

**Comment by gyoshev** [comment]
Based on your message, I could infer that there is an issue with the display of the dialog on small screens. If the dialog content is cropped, this may be caused by the Dialog `min-width` of `450px`,  which will be reconsidered. If that is the issue you wanted to highlight, you can workaround it by adding the following style on the page: `.k-dialog { min-width: 0; }`. See this [updated plunker](http://plnkr.co/edit/x5SGBZs2H2ZRDpAQO2sn?p=preview).

As a side-note, plunker snippets can be opened on mobile devices in "fullscreen" mode:
![image](https://cloud.githubusercontent.com/assets/90405/26670151/3bc08b58-46b9-11e7-8dcb-2489b6c39b75.png)
A QR code replaces the preview frame to allow scanning instead of typing URLs.

As another side-note, the "submit feedback" dialog on the documentation site is not an Angular dialog, as the documentation site is not an Angular app.
