### ISSUE TITLE
DropDownList popup is jumping while scrolling up and down the page

### ISSUE THREAD

**Issue by dzmitrykarnitski** [telerik/kendo-angular#590]
Hi,

DropDownList popup is jumping when user scrolls the page up and down. The issue can be reproduced in all browsers, depending on the number of items. The issue is well noticeable in IE11 browser with almost any number of items. However, Chrome performing well even with 300 items, but with 1000 items you can see the issue.

Steps to reproduce:
1) Click on the dropdown to open the popup.
2) Start scrolling up and down the page.

ER: Dropdown popup must should not change its position.
AR: Dropdown popup is moving up and down. 

Plnkr: http://plnkr.co/edit/POcjHPRsErYcgWYqJDw6?p=preview

UPD: It seems that the issue because of the Popup component:
http://plnkr.co/edit/0TcABD4MDmR71x9BsLCL?p=preview

Thanks!

**Comment by ggkrustev** [comment]
Hi @dzmitrykarnitski, 

indeed, the Popup component is responsible for its re-position on page scroll. This is required, because the element is 'detached' from its anchor (dropdownlist in this case). Because the reposition is done on scroll or window resize, we decided to _throttle_ the the component repositioning. Thus we reduce the rendering load and makes the page a bit more responsive.

The specific code that does this is:

```
const observables = parents.map(p => Observable.fromEvent(p, "scroll").auditTime(FRAME_DURATION));

//subscriber is defined here

this.subscription = Observable.merge(...observables).subscribe(subscriber);
```
where the `FRAME_DURATION` is:

```
export const FRAME_DURATION = 1000 / 60; //1000ms divided by 60fps
```

I fully understand that the popup jumps up and down a bit, but we do believe that the throttling is just required in this case. The other option is just to close the popup on close, approach used in Kendo UI for jQuery, but this introduces UX issues.

If you believe that we should expose this throttling compensation as an option, would it be possible to post your idea in our UserVoice portal?

http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback

This will help us to gather community feedback and decide whether to schedule the desired functionality for concrete implementation.

**Comment by ggkrustev** [comment]
Will close the thread due to inactivity. Please feel free to post any additional details if needed.
