### ISSUE TITLE
kendo-theme-bootstrap error

### ISSUE THREAD

**Issue by josephsteve** [telerik/kendo-angular#596]
hello,
does kendo for angular supports bootstrap styling?  i followed the get started demo but instead of using the kendo-theme-default, i installed kendo-theme-bootstrap.  of course, i did npm install --save bootstrap first.  then i added @import '~@progress/kendo-theme-bootstrap/scss/all'; in the src/styles.scss.  the error i'm getting is...

> ERROR in ./~/css-loader?{"sourceMap":false,"importLoaders":1}!./~/postcss-loader?{"ident":"postcss"}!./~/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/styles.scss
> Module build failed: 
> @import "~bootstrap/scss/variables";
> ^
>      File to import not found or unreadable: ~bootstrap/scss/variables.
> Parent style sheet: /Users/josephsteveserrano/Desktop/AngularProjects/kendo-ui-app2/node_modules/@progress/kendo-theme-bootstrap/scss/_variables.scss
>      in /Users/josephsteveserrano/Desktop/AngularProjects/kendo-ui-app2/node_modules/@progress/kendo-theme-bootstrap/scss/_variables.scss (line 2, column 1)
>  @ ./src/styles.scss 4:14-189
>  @ multi ./src/styles.scss

**Comment by gyoshev** [comment]
Yes, theming the components with kendo-theme-bootstrap produces themes compatible with Twitter Bootstrap v4. At this time, the kendo-theme-bootstrap requires a specific dependency to the `bootstrap` package (as shown in the NPM `peerDependencies`), which can be installed via 

    npm install --save bootstrap@git://github.com/twbs/bootstrap.git#95f37e4c402df37db16781995ffa1592032df9c8

We are working on a way to remove the hard dependency, so that you can consume the package standalone. You can [follow the discussion](https://github.com/telerik/kendo-theme-bootstrap/issues/256) about that in the kendo-theme-bootstrap issue.
