### ISSUE TITLE
Grid with 100% height does not fit in container

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular#609]
The Grid is expanded to display all records instead of fitting in its container. See [plunkr](http://plnkr.co/edit/Bsig0MWjKSUPECT43B89?p=preview).

```html
<kendo-grid [style.height]="'100%'">...</kendo-grid>
```

**Comment by tsvetomir** [comment]
Possibly related to #545

**Comment by gyoshev** [comment]
Since the binding does not change, it is more likely related to the demo styles. In order for `height: 100%` to work, all parent elements need to have a height, and the `my-app` element does not. Here is the [fixed plunker](http://plnkr.co/edit/yJ6ABjdrQjxBSR71dUGP?p=preview).

Do we show this anywhere in the demo site?

**Comment by tsvetomir** [comment]
My mistake, setting `100%` height works fine in your snippet.
