### ISSUE TITLE
Slider: Tick title

### ISSUE THREAD

**Issue by EricSch** [telerik/kendo-angular#613]
Shouldn't show the popover of the ticks by default the value?

Here it shows 0-5 and not 5-10:
http://plnkr.co/edit/fEVlkP3rElSzOuFFAEOz?p=preview 

Thanks

**Comment by EricSch** [comment]
Any feedback? :worried:

**Comment by danielkaradachki** [comment]
Sorry for the delayed reply. Could you clarify which popover are you referring to?

**Comment by EricSch** [comment]
the popover over the ticks

![2017-06-19](https://user-images.githubusercontent.com/25437/27289101-0ff01ddc-5509-11e7-97d0-aeb6da8860a6.png)

Here the value is 7, but the popover shows 2 (the index?). I know, I can set my own title, but I showing the value, should be the default behavior

**Comment by danielkaradachki** [comment]
Thanks for clarifying. Indeed, this is a bug. We will look into it.

**Comment by siyka-marinova** [comment]
Fix for this issue is available now in the latest dev.version of the package: `@progress/kendo-angular-inputs@1.1.0-dev.201707271519`.
To install this version, run npm install `@progress/kendo-angular-inputs@1.1.0-dev.201707271519` or configure it in package.json: `"@progress/kendo-angular-inputs": "1.1.0-dev.201707271519"` and run npm install.

**Comment by tsvetomir** [comment]
Fixed in `@progress/kendo-angular-inputs@1.1.0`
