### ISSUE TITLE
Virtual Scroll in Grid has undesired behavior

### ISSUE THREAD

**Issue by xiaowvmware** [telerik/kendo-angular#622]
In virtual scroll mode, pageChang event is fired to request users to update the grid data. However, if users need to fetch from  a server with some significant delay, the grid behaves abnormally.

Use virtual scroll example in http://www.telerik.com/kendo-angular-ui/components/grid/scroll-modes/, I change pageChange method as following:

app/app.component

export class AppComponent {
    protected pageChange(event: PageChangeEvent): void {
        this.skip = event.skip;
        setTimeout(()=>{
          this.loadProducts();
        }, 3000)
    }

In fact, I add 3 seconds delay to the data refresh. If scroll beyond row 100, I will see row 1 to 10 are display again first. After 3 seconds, row 100 to row 110 are displayed.

**Comment by rkonstantinov** [comment]
This behavior is caused by the fact that the while the new data is not present and the old one is shown as the grid content is not re-rendered. This effect will be hidden once the loading panel feature is added.

Meanwhile, you could add some loading indicator yourself, using some CSS styling. Such approach is demonstrated in [this plunkr](http://plnkr.co/edit/fbqoBO0fhgeJDQLUH0As?p=preview).

**Comment by tsvetomir** [comment]
Tracking in #666
