### ISSUE TITLE
DropDownList behaves undesirable since update from 0.39.3 to 1.0.10

### ISSUE THREAD

**Issue by ibra038** [telerik/kendo-angular#625]
Demo (1.0.10): http://plnkr.co/edit/Nae4vrzXNuqVrBRBtmAJ?p=preview

In 0.39.3 I had no problems with the Plunker above.  (_I couldn't find a way to demo an older version of "kendo-angular-dropdowns" through Plunker_)
I prefer not to downgrade to a beta version. 
Is there another way of implementing the DropDownList which is in a "popdown container"?

**Comment by tsvetomir** [comment]
We had to do a complete overhaul of the Popup implementation due to significant issues like #410.

This had an unfortunate side-effect of breaking scenarios like yours where the Popup is expected to render at a particular location in the DOM. We're working to enable such scenarios again as a separate future.
