### ISSUE TITLE
Provide selectionChange event for the MultiSelect component

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#629]
A selectionChange event should be exposed, providing the item that is selected or deselected as event data. Alternatively, two events (select and deselect) can be introduced, similar to the Kendo UI for jQuery MultiSelect.

**Comment by valchev** [comment]
After offline discussion with the team we decided that `selectionChange`event will not be added for the MultiSelect component.

The reason is that the `selectionChange` event overlaps with the `valueChange` event. There is no point to duplicate the events.

The `selectionChange` event is present in the ComboBox and DropDownList components because there the selection is possible to change the selection without changing the value when the options list is opened.
