### ISSUE TITLE
Unexpected data is loaded in the ComboBox dropdown after clearing the filter value

### ISSUE THREAD

**Issue by siyka-marinova** [telerik/kendo-angular#714]
When a filter is applied and an item is selected in the ComboBox, while clearing the filter new data is being loaded and the list of items shown in the dropdown is incorrect: 
[https://www.screencast.com/t/2wjGTtt2N](https://www.screencast.com/t/2wjGTtt2N)

Steps to reproduce:
1) Open the following [plunker](http://plnkr.co/edit/CRYHiBs2brD12jqhnaLK?p=preview)
2) Insert into the Combobox a "C" and wait until the list loads all items which contain the letter "C"
3) Select the first item (Condiments) and press Enter
4) Start pressing Backspace quickly to clear the filter

Result: After the filter value is cleared, the expanded list shows only the previously selected item -  "Condiments" or the list of items that is shown when applying the letter "C" in the filter (depending on how fast you clear the filter)

**Comment by tapopov** [comment]
Related to https://github.com/telerik/kendo-angular/issues/849

**Comment by tapopov** [comment]
Upon further inspection it seems this is not related to #849. There are two reasons why the data is still filtered after clearing the ComboBox.

First, the CategoriesService ignores empty filtering criteria
```javascript
    private fetch(tableName: string, filter): any {
        let queryStr = `$skip=0&$count=true`;
        if(filter){
```
Second, server-side filtering is an asynchronous task and there is no guarantee that the order of the responses will match the order of requests. Sometimes the response for data matching "c" arrives after the response containing all data. 

We will update the examples so that the empty filter is not being ignored. Also updating the documentation regarding async tasks is probably a good idea too.

**Comment by dimitar-pechev** [comment]
The issue is no longer relevant as the problematic examples have been altered or removed.
