### ISSUE TITLE
headerClass and class value of text-right not honored

### ISSUE THREAD

**Issue by fmorriso** [telerik/kendo-angular#725]
In order to right-justify  a numeric column in a kendo-angular grid, I would expect to be able to do the following, given that Bootstrap and the kendo-theme-bootstrap are part of my application:

```html
<kendo-grid [data]="enrollmentDateCounts | async"
			>
	<kendo-grid-column field="enrollmentDate"
	                   title="Enrollment Date"
					   width="75%">
		<ng-template kendoGridCellTemplate let-item>
			{{item.enrollmentDate | date:"yyyy-MM-dd"}}
		</ng-template>
	</kendo-grid-column>
	<kendo-grid-column field="studentCount"
	                   title="Students"
	                   headerClass="text-right"
		          class="text-right"
			  width="25%">
	</kendo-grid-column>
</kendo-grid>
```
The problem is, when I look at the generated HTML in the browser, I see that the text-right is added BEFORE the other kendo styles.  It should be added AFTER the other kendo styles so that it will not be overridden by the built-in kendo td style of text-align: left.

Work-around until this bug gets fixed: 

```html
<kendo-grid [data]="enrollmentDateCounts | async"
			>
	<kendo-grid-column field="enrollmentDate"
	                   title="Enrollment Date"
					   width="75%">
		<ng-template kendoGridCellTemplate let-item>
			{{item.enrollmentDate | date:"yyyy-MM-dd"}}
		</ng-template>
	</kendo-grid-column>
	<kendo-grid-column field="studentCount"
	                   title="Students"
	                   [headerStyle]="{'text-align': 'right'}"
			   [style]="{'text-align': 'right'}"
			   width="25%">
	</kendo-grid-column>
</kendo-grid>
```

**Comment by gyoshev** [comment]
I'm afraid that the problem is not caused by this. The order of classes in the HTML has no effect over the application of styles. [See this example](https://dojo.telerik.com/UHopaF). The applied style is determined only by the CSS rule specificity. The suggested workaround applies an inline style, which has a very big specificity, rather than the class.

That said, I [could not reproduce](https://plnkr.co/edit/c4uHy2SG5UhfHSuF0v5b?p=preview) the issue with the latest builds. It might have been an issue with Bootstrap 3, where the [`text-right` class has a lower specificity](https://github.com/twbs/bootstrap/blob/v3.4.0-dev/dist/css/bootstrap.css#L1315-L1317) than ours (010 vs 011). The [Bootstrap 4 styles use `!important`](https://github.com/twbs/bootstrap/blob/v4-dev/dist/css/bootstrap.css#L8804-L8806), so the class works correctly.

**Comment by fmorriso** [comment]
Why did you close this issue? 

The order of classes DOES MATTER because of the well-known CSS "last one wins" when styles conflict.

That's why I wrote the original issue in the first place.

Why not just change Telerik so that user-specified class="value" are APPENDED after rather than PREFIXED before any built-in classes?

**Comment by tsvetomir** [comment]
Thought the issue was resolved as per @gyoshev's comment. Can you confirm if you're using the latest Bootstrap v4 release?

**Comment by dasariramacharan** [comment]
@tsvetomir I am able to replicate the issue  of headerClass not working.

Below example I am trying to use header class to wrap text which doesn't work

https://stackblitz.com/edit/angular-qndbp4-nbmrnc

**Comment by Raisolution** [comment]
Hi @dasariramacharan 

The header class is set correctly and is present in the DOM. The styles however are not being applied in the example, because the component styles are being encapsulated. You could set the `ViewEncapsulation` to `None` as [demonstrated here](https://stackblitz.com/edit/angular-qndbp4-sw5256).

For further issues and assistance please open a [support ticket](https://www.telerik.com/account/support-tickets).
