### ISSUE TITLE
Datepicker: model binding stops working after second change

### ISSUE THREAD

**Issue by arturstarodaj** [telerik/kendo-angular#742]
To reproduce
1) Pass null as model to datepicker
2) Select a date
3) Pass a new model 'false' -it is working fine
4) Select a date
5) Pass a new model 'false' - its not working anymore,

**Comment by ggkrustev** [comment]
Could you provide a runnable [Plunkr demo](https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue)? You can use our demos as a base.

http://www.telerik.com/kendo-angular-ui/components/dateinputs/datepicker/

**Comment by arturstarodaj** [comment]
@ggkrustev Here you are:
http://plnkr.co/edit/nq4JBP58aXuLldWdkvjf?p=preview

**Comment by ggkrustev** [comment]
@arturstarodaj, thank you for the demo. 

Indeed, the component is not cleared on the second `Reset` click, but this is expected. The second time, the `this.model` field will be set to `false`, but its previous value was already `false`. As a result, *no of the related components (DatePicker in this case) will be updated*, because there is **no change** in the `this.model` field.

The solution is to update the `this.model` on DatePicker change. Thus the field will be synced accordingly.

http://plnkr.co/edit/ggJQPzgFt6Lij0e5oKAf?p=preview

Please note that it will be better to reset the value, setting it to `null`, because the component expects `Date` instances (`null` is valid Date value). Setting the value to a different value type is incorrect.

I would suggest you check this blog post for more details.

https://blog.thoughtram.io/angular/2016/02/22/angular-2-change-detection-explained.html
