### ISSUE TITLE
RTL support for ComboBox drop down

### ISSUE THREAD

**Issue by badej2009** [telerik/kendo-angular#775]
Hello

I have enabled RTL mode using RTL token in providers section of my @NgModule. I have done it exactly as explaiend in: http://www.telerik.com/kendo-angular-ui/components/localization/rtl/.
The input part of the ComboBox is aligned to the right correctly.
 Unfortunately the pop up part continues to be aligned to the left: items are on the left and scroll bar is in the right. You can see this wrong behavior in your example: http://www.telerik.com/kendo-angular-ui/components/dropdowns/rtl/ (please open ComboBox's drop down).
Please give a solution.

thanks
Badej

**Comment by badej2009** [comment]
Hello Again...

I read in your site that you need a Plunker link.
Here it is:
http://plnkr.co/edit/fOddnALU4Q6Of0qWYqLb?p=preview

thanks
Badej

**Comment by valchev** [comment]
Hi @badej2009,

Thank you for bringing this to our attention. I can confirm that this is a bug in the component. We will do our best to provide a fix as soon as possible.

**Comment by badej2009** [comment]
Thank you for checking out this issue. We need this functionality desperately... Please let us know at the moment you release the fix.

Badej

**Comment by siyka-marinova** [comment]
The fix is currently available in the latest dev. version: `@progress/kendo-angular-dropdowns@1.1.3-dev.201707270755`.
To install this version, run `npm install @progress/kendo-angular-dropdowns@1.1.3-dev.201707270755` or configure it in package.json: `"@progress/kendo-angular-dropdowns": "1.1.3-dev.201707270755"` and run `npm install`

**Comment by badej2009** [comment]
Many thanks for your quick response!
Can I see this fix on your RTL demos?
 http://www.telerik.com/kendo-angular-ui/components/dropdowns/rtl/

**Comment by valchev** [comment]
The demo site does not use the dev. version of the package. The change will be visible in the RTL online demo, after the fix is released as a regular package update and the site is updated too. That process may take a few weeks.

In case you need the fix urgently, please refer to @siyka-marinova instructions and use the dev. version.

**Comment by badej2009** [comment]
I have checked the dev. version fix with an external tester. It works perfectly. Thank you!
Unfortunately we failed to use this dev. package in our real client application, because our application uses other Kendo components which belonged to official release package.
We will be glad to know when the fix is released as a regular package.

Thanks again
Badej

**Comment by tsvetomir** [comment]
Fixed in v1.1.3

**Comment by tsvetomir** [comment]
@badej2009 sorry for the delay, please give the latest official release a try

**Comment by badej2009** [comment]
Hello @tsvetomir ,

thank you for the notification.
Can I see this fix in the demo  in Kendo site?

Badej

**Comment by tsvetomir** [comment]
The latest update on the site fixes this issue.
