### ISSUE TITLE
Allow for custom attribute for dom selection

### ISSUE THREAD

**Issue by willrpike** [telerik/kendo-angular#776]
## Current behavior
Currently ElementOptions and GroupOptions and PathOptions do not contain an identifier, either class, name or id would work. 

Currently we have the property name, but it takes a path not a string .

## Expected behavior
To set a property on an element or group so that I can toggle it from the dom. 

## What is the motivation / use case for changing the behavior?
e2e tests that require clicking on charts

**Comment by danielkaradachki** [comment]
Currently we do not plan to add support for rendering attributes since SVG is not the only possible output. You could use the Surface [eventTarget](http://www.telerik.com/kendo-angular-ui/components/drawing/api/Surface/#toc-eventtarget) method to determine which drawing element was clicked. For the charts you could also use its click [events](http://www.telerik.com/kendo-angular-ui/components/charts/api/ChartComponent/#toc-events).

**Comment by willrpike** [comment]
@danielkaradachki thanks for the reply. 

To be clear, the use case would be more automated/e2e testing where I didn't care about determining which element was clicked but be able to tell selenium to click a specific element. 

`element(by.id('unique-id-for-data-point'))`

xpath is the only alternative (besides using x, y coords) that I can think of.

**Comment by danielkaradachki** [comment]
Thank you for clarifying. Given that there isn't way to do this with the current API we will consider adding support for rendering some attributes when the output is SVG(probably id since name does not make much sense in SVG).

**Comment by siyka-marinova** [comment]
This feature is now available in the latest dev. version of the kendo-drawing package: `@progress/kendo-drawing@1.3.0-dev.201708281458`. The official package will be released soon.

**Comment by siyka-marinova** [comment]
Released in: `@progress/kendo-drawing@1.3.0`
