### ISSUE TITLE
Dialog action buttons don't style correctly when content is scrollible

### ISSUE THREAD

**Issue by spintelgar** [telerik/kendo-angular#781]
**Description**
When setting a height and width of a dialog, and the content is too large for the specified dimensions, the scroll bar correctly displays, but the dialog action buttons style breaks.

Plunkr of issue made from combining form and dialog examples from official Telerik docs
http://plnkr.co/edit/rNwAy3YAjdxjOwaggcqd?p=preview. 

**Browser:**
- Chrome (desktop) version 59.0.3071.115 (Official Build) (64-bit)

**Comment by gyoshev** [comment]
Thanks for reporting this, we have confirmed this as a bug in the theme and will fix it shortly. In the meantime, you can set `flex: 0 0 auto` to the buttons container to resolve the issue:

    <kendo-dialog-actions style="flex: 0 0 auto;">

Here is the [updated plunker](http://plnkr.co/edit/i9U8JAhxlJYkeNB7SS7D?p=preview).

**Comment by spintelgar** [comment]
Thanks for the VERY quick response :)

**Comment by siyka-marinova** [comment]
Fix for this issue is now available in the latest dev. version of the kendo-theme-default package: `@progress/kendo-theme-default@2.39.0-dev.201707280706`.
To install this version, run `npm install --save @progress/kendo-theme-default@2.39.0-dev.201707280706` or configure it in package.json: `"@progress/kendo-theme-default": "2.39.0-dev.201707280706"` and run `npm install`.

**Comment by gyoshev** [comment]
Available officially in `@progress/kendo-theme-default@2.39.0`.
