### ISSUE TITLE
PopupService Using Components -> Change instance inputs -> No change detected

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#790]
Here plunker to reproduce: http://plnkr.co/edit/qaBHWGRSPpNp7ejcF9PS?p=info

I'm using Popup service Using Components http://www.telerik.com/kendo-angular-ui/components/popup/service/#toc-using-components and i just would like to change property of popup component created by service.

No way to get change on view, no way to have `ngOnChanges` life cycle called on custom popup component.

Could you please check it?

**Comment by ggkrustev** [comment]
Hi @meriturva, sorry for the delayed answer.

Indeed, the change is not applied when `markForCheck` is used. I suppose the cause is a timing issue. The changes are applied when you enforce the update. Use `detectChanges` for this task.
```
this.popupRef.content.changeDetectorRef.detectChanges();
```

Check the updated plunkr - http://plnkr.co/edit/bbrLsfSwhRv3dxZqNBPe?p=preview

**Comment by meriturva** [comment]
Thanks! it works!
