### ISSUE TITLE
Cannot assign ID attribute to kendo-combobox

### ISSUE THREAD

**Issue by kibbled** [telerik/kendo-angular#809]
Tried everything including
```
<kendo-combobox id="inputX"
<kendo-combobox [id]="'inputX'"
<kendo-combobox [attr.id]="'inputX'"
```
Neither of these propagate the ID attribute to the underlying input control.

**Comment by ggkrustev** [comment]
@kibbled, this is expected because `id` attribute is valid property of the `<kendo-combobox>` element. It will be incorrect to move the `id` value to the underlying `<input />` element.

If you would like to target the `<input />`, for styling purposes I guess, you can still use the `id` of the combobox but just target input in the CSS selector.

As a side note, the Github channel should be used only for bug reports or feature requests. If you have any questions regarding specific implementation, please either open a support thread or post your question in Stackoverflow.

**Comment by kibbled** [comment]
@ggkrustev I appreciate your response however there are other reasons for wanting to assign an ID to an element within HTML. Perhaps it's a feature request but I think Kendo controls should provide a way of setting ID of underlying control.

**Comment by ggkrustev** [comment]
Yeah, this is a valid feature request. Could you post the idea in our feedback portal?

http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback

It will be great if you elaborate more on the use case, which requires explicit attribute updates of the underlying <input/> element.

**Comment by ggkrustev** [comment]
Will close the thread as the discussion should me moved in UserVoice to collect community feedback.

**Comment by jtc10005** [comment]
I know this is closed but did anyone actually request this in the feedback portal?  My team is encountering this now, and I wanted to verify that it was added.  I searched for it but did not find it.
