### ISSUE TITLE
Intl service produces incorrect long month format for dates

### ISSUE THREAD

**Issue by SeriousLemon** [telerik/kendo-angular#838]
## I'm submitting a...

* Bug report

## Current behavior
Intl service produces incorrect long month format for dates.

## Expected behavior
Expect long month format to produce dates (for English) like January, February, March...

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/jYTAw8qaH4vOt1LOnMPE?p=preview

**Comment by danielkaradachki** [comment]
Indeed, this is a bug. Even though there isn't a an available format containing only long month name, the resolved format should use the specified type of name. We will look into it.

**Comment by SeriousLemon** [comment]
I was under the impression that `{ year: 'numeric', month: 'long' }` produced the same output i.e. `Aug 2015` but taking a look again -- it's fine. So you're right, it's not really a bug.

**Comment by danielkaradachki** [comment]
It is actually. According to the [specifications](http://www.unicode.org/reports/tr35/tr35-dates.html#Matching_Skeletons), the resolved format should automatically be expanded to fit the specified specifiers length. Currently, this does not happen for the month only because the resolved pattern uses standalone specifiers. A [fix](https://github.com/telerik/kendo-intl/commit/39df94d2c816f66281e96df489cdca1234963ec4) was pushed for the kendo-intl package and it will be available soon for kendo-angular-intl.
