### ISSUE TITLE
Kendo Grid  transform: translateY(0px);

### ISSUE THREAD

**Issue by moxival** [telerik/kendo-angular#857]
Hey guys, at some point the table sets `transform: translateY(0px);`  on `table.k-grid-table` element and that basically does not allow any use of a fixed position components, like tooltips, inside the table.

You can see the addition of this inline style here: http://www.telerik.com/kendo-angular-ui/components/grid/paging/

Also you can read on how transform creates a new containg block here: https://coderwall.com/p/2wzj-a/break-out-of-overflow-hidden-with-relative-positioned-fixed-elements

Can you not use transform on the grid rows container?

**Comment by ggkrustev** [comment]
Hi @moxival, we are aware of the `position: fixed` behavior in transformed elements and that's why we undertake a series of actions to improve Popup behavior in such containers. 

All components render the popup at the root (using PopupService), which should ensure that the popup is placed in the top stacking container element. The second step is change in the CSS styling. Now the Popup component exposes `positionMode` option that enables you to choose between `position: fixed` and `position: absolute`. This enhancement is officially released and we will upload the documentation soon. I would suggest you checking the latest versions of the aforementioned components.

**Comment by moxival** [comment]
Hi @ggkrustev thanx for the explanation, the only trouble is we are not using kendo popup but custom components that rely on position fixed.

**Comment by ggkrustev** [comment]
@moxival, I am afraid that the only feasible solution in this case is to use `position: absolute`. 

Elements with `transform` styling is quite widespread now days (consider Bootstrap for instance), which makes `position: fixed` unusable in most cases. On top of that, `position: fixed` is not supported at all in mobile browsers with zoom. If want to provide wider support on different platforms, then switching to `position: absolute` will be the best choice.

As a last resort, you can try to modify grid rows styling, but we cannot guarantee any good results with such change. Nevertheless, if `position: fixed` styling is a must, then you will need to modify all elements that use `transform` styling.

**Comment by eashi** [comment]
Is there any documentation around this feature?
