### ISSUE TITLE
kendo-datepicker shows long placeholder for date

### ISSUE THREAD

**Issue by monkeecheetah** [telerik/kendo-angular#859]
## I'm submitting a...
  * Suggestion for improvement

## Current behavior
When using datepicker and I have chosen format dd.MM.yyyy the placeholder writes "day.month.year" (in Norwegian). 

## Expected behavior
This is before date is chosen, the text is concatenated.
![image](https://user-images.githubusercontent.com/1310544/29811398-9b48fc4c-8ca3-11e7-8b69-dc5543a1c588.png)

When date is placed it looks okay.
![image](https://user-images.githubusercontent.com/1310544/29811300-472671ee-8ca3-11e7-9889-17fc7d7fad87.png)

It would be nice if the text wasnt concatenated and don't have to expand the width on input field just to fit placeholder text when finished data fits just fine.

## Minimal reproduction of the problem with instructions
Create a kendo-datepicker.
<kendo-datepicker class="form-control" formControlName="fraDato" [focusedDate]="focusedDate" [format]="'dd-MM-yyyy'" name="fraDato"></kendo-datepicker>

## What is the motivation or use case for changing the behavior?
You have to expand the width for inputfields more than you necessary just to show the placeholder when dd-mm-yyyy could be sufficient (same format as you show the picked date).

Browser:
- Chrome (desktop) version 60

**Comment by ggkrustev** [comment]
@monkeecheetah thanks for the suggestion. Indeed, showing just the format will reduce the input space required to display the placeholder. The feature actually was already planned and shortly will enter in actively development state.

Will update the thread once it is available for review.

**Comment by JaapMosselman** [comment]
But, please, don't forget localization. In Dutch I would like to see dd-mm-jjjj as placeholder.
And the same issue applies also to the TimePicker of course.

**Comment by thaoula** [comment]
Hi @ggkrustev,

Will the changes you are working on allow for custom placeholders?

This will enable us to use the placeholder as a field label ... ie. placeholder will say <Due Date> rather than date format

Tarek

**Comment by ggkrustev** [comment]
Hi @thaoula, custom (free) placeholder is still under consideration. If there aren't any implementation limitations, we will introduce it. The ongoing research will show.

**Comment by thaoula** [comment]
Hi @ggkrustev,

Thanks for your reply. 

When to do you expect Kendo UI for Angular to become fully featured. 

We have purchased a license but are forced to use different control and libraries for many use cases because of usability shortcomings.

Do you plan to open source the library or at least provide the source code so that we can just modify the library ourselves?

Quite honestly and sorry to be blunt, the current development cadence seems far to slow. 

Regards,
Tarek

**Comment by JaapMosselman** [comment]
Instructions for obtaining source code can be found here: [http://www.telerik.com/kendo-angular-ui/components/installation/source-code/](url).
I have done it to do some modifications.
Works fine

**Comment by ggkrustev** [comment]
Hi @thaoula,

There is no hesitation on our side when we want Kendo UI for Angular feature complete. The answer is as soon as possible. I am afraid, though, that I won't be able to provide a specific time frame. We are working hard to introduce new components that are better and faster than before, but this takes time. I would suggest you follow our [Roadmap](http://www.telerik.com/kendo-angular-ui/roadmap/) for more specific details on our planning or share your feature requests in our Feedback portal. This is the best way to prioritize our tasks in future.

To mitigate the shortcomings that anyone could run across we provide a temp solution showing how to [integrate Kendo UI for jQuery](). This allows uninterrupted (more or less) development until a native component is available. 

I am sorry to hear that a fallback to different libraries was required. Could you elaborate a bit more on that?

Our immediate plans don't include open sourcing Kendo UI for Angular. A valid license is required in order to use our components.

@JaapMosselman, thanks for linking the 'Obtaining the source code' article. I hope this will help to anyone that wants to access the source code of the components.

**Comment by ggkrustev** [comment]
The feature is available in the latest @dev version of `@progress/kendo-angular-dateinputs`. Just install `@progress/kendo-angular-dateinputs@1.4.0-dev.201711011505`.

**Comment by ggkrustev** [comment]
`@progress/kendo-angular-dateinputs@1.4.0` is out. Will close the thread as resolved.
Please feel free to comment if something is not OK.
