### ISSUE TITLE
Failed to build with Angular 5.0.0-beta.5

### ISSUE THREAD

**Issue by Sky4CE** [telerik/kendo-angular#874]
Problem is in `@progress/kendo-angular-dateinputs`. Due to this breaking change:
common: NgTemplateOutlet#ngOutletContext has been removed as it was deprecated since v4. Use NgTemplateOutlet#ngTemplateOutletContext instead.
![image](https://user-images.githubusercontent.com/9821633/30060726-3e048b0a-924d-11e7-9a5e-94bffa0ed687.png)

Any plans to fix this?

**Comment by ggkrustev** [comment]
Indeed, the Angular 5 removed some of hte NgTemplate context directives. We will update the the code to work with the upcoming Angular 5 official release.

**Comment by tsvetomir** [comment]
Should be fixed in v1.2.1-dev.201709291426, upgrade with `npm install @progress/kendo-angular-dateinputs@dev` to verify.

**Comment by Sky4CE** [comment]
@tsvetomir, seems like now some other part fails
![image](https://user-images.githubusercontent.com/9821633/31131150-fe9e745a-a861-11e7-8d2e-7d6efeb97388.png)

**Comment by tsvetomir** [comment]
Try upgrading the `@progress/kendo-angular-grid` to the dev version as well:
`npm install --save @progress/kendo-angular-grid@dev`

**Comment by Sky4CE** [comment]
@tsvetomir,
![image](https://user-images.githubusercontent.com/9821633/31229312-ee6fb7c8-a9e8-11e7-8513-4ebf157b0d99.png)

**Comment by tsvetomir** [comment]
The Layout package should be updated to v1.0.7, try `npm update @progress/kendo-angular-layout`

**Comment by Sky4CE** [comment]
I've tried @dev version and that error goes away, but now I have errors with non-kendo libs =(

**Comment by tsvetomir** [comment]
We'll publish Angular 5 compatible `@latest` versions on all components in a week or so.

**Comment by tsvetomir** [comment]
There are no known issues with Angular 5 RC builds at the moment, so I'll close this issue.

You'll still get npm warnings about unmet peer dependencies that will be resolved as we update the packages. These can be safely ignored.

**Comment by rgantla** [comment]
@tsvetomir could you please let us know once you get the stable version out for angular 5? we are running angular 5.0.1 currently and would love to be able to implement the grid. Please also update the documentation since the website says "full compatible with angular 5" but the documentation says otherwise.

BTW I am facing the same exact issue as @Sky4CE was, after replacing the OpaqueToken with InjectionToken in some of the files. 

I have tried updating my kendo packages as mentioned above with the commands specified but i ended up with different (earlier) versions as compared to @Sky4CE which were no good.

**Comment by tsvetomir** [comment]
@rgantla please make sure you're loading the packages from the official npm registry. See #712

**Comment by rgantla** [comment]
thanks @tsvetomir Following the post #712 solved the problem and the grid works fine!
