### ISSUE TITLE
Add autoCorrect option to TimePicker

### ISSUE THREAD

**Issue by JaapMosselman** [telerik/kendo-angular#879]
## I'm submitting a...
* Suggestion for improvement (or do you categorize this as Feature request?)

## Current behavior
When min and/or max is set, the user can just type a value outside the range. (Of course the control wil be in invalid state.)

## Expected behavior
Add autoCorrect boolean property as in NumericTextBox. When typing a value greater than max or smaller then min, the value is automatically set to max or min.

**Comment by ggkrustev** [comment]
The `autoCorrect` feature is actually under consideration. We will need to introduce several changes into DateInput component in order to provide proper auto-correction. Once this is done, DatePicker and TimePicker will get auto-correction for free.

I am afraid though that I wouldn't be able to provide specific time-frame when this will be implemented.

**Comment by JaapMosselman** [comment]
Ok, nice to know. The current control we use does not support is either, so it is not a blocking issue for the short term and does not keep us from migrating to Kendo UI (while some other issues do).

**Comment by dcarter-mhk** [comment]
Hi Kendo team, is there any update for this issue?  I see it has the "FP: Planned" label, does that mean there is a release date planned or just that this is in progress?  My team is waiting for this enhancement: https://feedback.telerik.com/kendo-angular-ui/1417908-datevalidation which you have mentioned is blocked by this issue 879.

**Comment by tswetti** [comment]
An [`autoCorrectParts`](https://www.telerik.com/kendo-angular-ui/components/dateinputs/api/dateinputcomponent#autocorrectparts) option was recently introduced to out DateInput components that contain a date. However, its purpose is to autocorrect the invalid segments of a date (see [this feature request](https://feedback.telerik.com/kendo-angular-ui/1417908-datevalidation)).
Autocorrecting date/time that is outside of the predefined range has been logged as a separate feature request in our Feedback Portal:
[https://feedback.telerik.com/kendo-angular-ui/1664386-add-option-that-restricts-the-user-to-type-value-outside-of-range](https://feedback.telerik.com/kendo-angular-ui/1664386-add-option-that-restricts-the-user-to-type-value-outside-of-range)

Feel free to upvote and follow the linked item in order to stay notified when there is any progress on the future implementation of this feature. We periodically monitor the customer demand for the logged feature requests and decide on their future implementation based on the increasing interest.

In the meantime, consider using the workaround mentioned in the description of the Feedback Portal item:
[https://stackblitz.com/edit/angular-b1e6jl](https://stackblitz.com/edit/angular-b1e6jl?file=src%2Fapp%2Fapp.component.ts)
