### ISSUE TITLE
Add the ability to select several dates in Calendar

### ISSUE THREAD

**Issue by dgroh** [telerik/kendo-angular#883]
## I'm submitting a...

* Suggestion for improvement

## Current behavior
As per docs, there is only the possibility of selecting one date:

`<kendo-calendar [value]="value"></kendo-calendar>`

## Expected behavior
As it's a calendar, I would like to select more dates, so the `value`  could be an array of dates. If I can not select several dates as I would in a normal calendar, I assume this is only a `DatePicker`.

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by MaklaCof** [comment]
And also add option to select range.

**Comment by ggkrustev** [comment]
@dgroh, do you need to select sparse dates or a specific date range? 

The `range selection` functionality is under consideration right now. The calendar will be able to display a specific [start:end] date range and its value could be updated from the UI. Most probably a specific directive will be introduced in order to enhance current calendar behavior.

Support for selecting multiple single dates (not range) is not in our short-term plan. We will consider it in future though depending on the user interest. @dgroh, if this is the required behavior, could you share your request in our [UserVoice portal](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback)? Thus more people will be able to cast their vote for it.

As to the `[value]` property type, it won't change and it will stay `Date`. Returning either Date or Array<Date> conditionally will introduce only confusion. Additional property/events will be introduced to utilize the `range selection` range.

**Comment by dgroh** [comment]
Hi @ggkrustev ,

yes we need to select only specifiy dates, not a range. The `value` property was only a suggestion, for now I don't have any better name.

I will use the UserVoice portal, but I also could try a pull-request, if this is possible???

**Comment by dgroh** [comment]
Make sense to create a directive and iterate throuout the items with `role="gridcell"` of the control looking for the dates I want to select?

**Comment by ggkrustev** [comment]
Currently, the Kendo UI for Angular is under private development, which excludes acceptance of pull requests outside the Progress organization. Sorry for that.

With regards to your last message, I suppose this will be fine. I am not sure how the selected dates (state persistance) will be combined with the Calendar as a UI, but there is numerous approach are applicable in this case. You can use anything that suits your needs.

**Comment by dgroh** [comment]
Just clarified with the team, what is really meant with this feature, is the possibility of "marking" dates, for instance for events, but not selecting those dates. in any case this is no longer a requirement for us and I'll be closing this issue.
