### ISSUE TITLE
Question about setting defaults on numerictextboxes

### ISSUE THREAD

**Issue by jamesomac** [telerik/kendo-angular#893]
## I'm submitting a
- Question

## Details
With Kendo/AngularJs there was a feature to use k-options="variableName" and set the properties for a control.

I am looking for a way to do this with the current Kendo-Angular, or ideally have a way to set defaults for all controls of a certain type on the project level.

**Comment by ggkrustev** [comment]
Hi @jamesomac,

Kendo UI for Angular provides controls that utilizes the Angular approach of writing components. There is no single option that could set arbitrary component's properties, simply because Angular does not allow such approach. 

If you would like to apply specific defaults to a Kendo component, or any component in that matter, then a high-order component should be used. The wrapping (high-order) component will set the defaults and will create the component. Of course if only defaults should be provided, then you can use a simple Angular Directive for this job.

I would strongly suggest you perusing Angular documentation.
https://angular.io/docs

If you have any further questions, please either open a support ticket or post your question Stackoverflow. Check point 3 of the `How do I...?` section:

http://www.telerik.com/kendo-angular-ui/support/

**This Github channel should used only for bug reports/enhancement request.** With that in mind, I will close this issue.
