### ISSUE TITLE
Alignment of the cursor in combobox

### ISSUE THREAD

**Issue by destus90** [telerik/kendo-angular#978]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
* In Firefox browser when select a value with large text in combobox the cursor is aligned to the right

## Expected behavior
cursor is aligned to the left

## Minimal reproduction of the problem with instructions
1. [Open a demo](http://plnkr.co/edit/CuiDWiuDdN1uydVM8Z6r?p=preview)
2. Select first value.

## Environment

Package versions: 1.2.1

Browser:
- Firefox version 55.0.3

**Comment by tapopov** [comment]
Hello @destus90 
The cursor is moved at the end of the text, which is the expected behavior in a left-to-right writing direction. I've ran the plunkr example on multiple browsers and this appears to work as expected on all of them, regardless of which item was selected and how. Would you please let me know if I am missing something?

**Comment by destus90** [comment]
@tapopov Hello. When I`m publish this issue pkg:dropdowns has version 1.2.1. Now its 1.2.2. May be it was fixed. Thx for the answer. Closed.
