### ISSUE TITLE
DatePicker min value not validated using keyboard

### ISSUE THREAD

**Issue by monkeecheetah** [telerik/kendo-angular#994]
## I'm submitting a...
* Bug report

## Current behavior
When using datepicker to choose a date and you have set a min date you can't choose a date before the min date. 

If you type with keyboard you can type any date you want.

## Expected behavior
Same behaviour as keyboard, if you type with keyboard you should not be able to pick a date before min date.

## Minimal reproduction of the problem with instructions
Use datepicker and set a min date. Type a date before min date using keyboard.

## What is the motivation or use case for changing the behavior?
Keyboard usability and universal design.

This issue is probably related to https://github.com/telerik/kendo-angular/issues/910

**Comment by ggkrustev** [comment]
@monkeecheetah, by design the min/max restriction is handled by the form range validators. That being said, the component will not forcibly restrict the input while typing. This task will be handled by the entitled min|max validator. A specific example can be seen in our documentation, Forms section:

https://www.telerik.com/kendo-angular-ui/components/dateinputs/datepicker/#toc-forms-support

The functionality you are speaking of could be achieved with additional input restriction, known as `autoCorrect` option. It is suggested here and is still under consideration:

https://github.com/telerik/kendo-angular/issues/879

I will suggest you subscribe to the mentioned Github issue, which will be updated once there is more details to be shared.

For the time being, I would suggest you implementing form validators that will restrict user input. The benefit of such approach is that the user will know what is the valid date that must be entered.

I will close the thread as it is duplicated to the #879.

**Comment by DominicSachs** [comment]
@ggkrustev 
Are there any updates on this feature?

**Comment by ggkrustev** [comment]
The `autoCorrect` functionality, if you are referring to it with the question, is still under consideration. We will update the related #879 issue when we have any updates.

**Comment by chetanmore0510** [comment]
@ggkrustev : do we have any update on autoCorrect feature for datepicker?
